package cbs.repository.account.tempinfo.dao;

import cbs.repository.account.tempinfo.model.Actcxr;
import cbs.repository.account.tempinfo.model.ActcxrExample;
import cbs.repository.account.tempinfo.model.ActcxrKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActcxrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTCXR
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    int countByExample(ActcxrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTCXR
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    int deleteByExample(ActcxrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTCXR
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    int deleteByPrimaryKey(ActcxrKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTCXR
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    int insert(Actcxr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTCXR
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    int insertSelective(Actcxr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTCXR
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    List<Actcxr> selectByExample(ActcxrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTCXR
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    Actcxr selectByPrimaryKey(ActcxrKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTCXR
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    int updateByExampleSelective(@Param("record") Actcxr record, @Param("example") ActcxrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTCXR
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    int updateByExample(@Param("record") Actcxr record, @Param("example") ActcxrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTCXR
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    int updateByPrimaryKeySelective(Actcxr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTCXR
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    int updateByPrimaryKey(Actcxr record);
}