package cbs.repository.account.maininfo.dao;

import cbs.repository.account.maininfo.model.Actact;
import cbs.repository.account.maininfo.model.ActactExample;
import cbs.repository.account.maininfo.model.ActactForOblRpt;
import cbs.repository.account.maininfo.model.ActactForPlcRpt;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ActactMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTACT
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    int countByExample(ActactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTACT
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    int deleteByExample(ActactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTACT
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    int insert(Actact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTACT
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    int insertSelective(Actact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTACT
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    List<Actact> selectByExample(ActactExample example);

    /**
     * createBy: haiyuhuang
     * modifyDate:     2010-12-24
     * remark:   按币别分组*/
    List<ActactForOblRpt> selectForObfRpt(@Param("orgidt") String orgidt,@Param("curcde") String curcde,@Param("apcode") String apcode);

    /**
     * createBy: haiyuhuang
     * date:     2010-12-24
     * remark:   按币别分组*/
    List<ActactForOblRpt> selectGrpCurcde(@Param("orgidt") String orgidt);
    /**
     * createBy: haiyuhuang
     * date:     2010-12-24
     * remark:   按科目号分组*/
    List<ActactForOblRpt> selectGrpGlcode(@Param("orgidt") String orgidt,@Param("curcde") String curcde);
    /**
     * createBy: haiyuhuang
     * date:     2010-12-24
     * remark:   按核算码分组*/
    List<ActactForOblRpt> selectGrpApcode(@Param("orgidt") String orgidt,@Param("curcde") String curcde,@Param("glcode") String glcode);
    /**
     * createBy: haiyuhuang
     * date:     2011-01-17
     * remark:   根据货币号 查询损益表报表数据*/
    List<ActactForPlcRpt> selectForPlc(@Param("curcde") String curcde,@Param("glcode") String glcode);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTACT
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    int updateByExampleSelective(@Param("record") Actact record, @Param("example") ActactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTACT
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    int updateByExample(@Param("record") Actact record, @Param("example") ActactExample example);
    
}