package cbs.repository.account.maininfo.dao;

import cbs.repository.account.maininfo.model.Actblh;
import cbs.repository.account.maininfo.model.ActblhExample;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface ActblhMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTBLH
     *
     * @mbggenerated Mon Dec 06 14:59:42 CST 2010
     */
    int countByExample(ActblhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTBLH
     *
     * @mbggenerated Mon Dec 06 14:59:42 CST 2010
     */
    int deleteByExample(ActblhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTBLH
     *
     * @mbggenerated Mon Dec 06 14:59:42 CST 2010
     */
    int insert(Actblh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTBLH
     *
     * @mbggenerated Mon Dec 06 14:59:42 CST 2010
     */
    int insertSelective(Actblh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTBLH
     *
     * @mbggenerated Mon Dec 06 14:59:42 CST 2010
     */
    List<Actblh> selectByExample(ActblhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTBLH
     *
     * @mbggenerated Mon Dec 06 14:59:42 CST 2010
     */
    int updateByExampleSelective(@Param("record") Actblh record, @Param("example") ActblhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTBLH
     *
     * @mbggenerated Mon Dec 06 14:59:42 CST 2010
     */
    int updateByExample(@Param("record") Actblh record, @Param("example") ActblhExample example);


    /**
     * createBy: haihuhuang
     * createDate: 2011-03-10
     * remark: 结清账户用*/
    @Select(" SELECT NVL(SUM(CRACCM),0)" +
            " FROM ACTBLH" +
            " WHERE ORGIDT = #{orgidt}" +
            "    AND CUSIDT = #{cusidt}" +
            "    AND APCODE = #{apcode}" +
            "    AND CURCDE = #{curcde}" +
            "    AND ERYDAT = to_date('1999-10-31','yyyy-mm-dd')" +
            "    AND ERYDAT >= #{erydat}")
    long selectCraccm(@Param("orgidt") String orgidt,@Param("cusidt") String cusidt,
                      @Param("apcode") String apcode,@Param("curcde") String curcde,@Param("erydat") Date erydat);

    /**
     * createBy: haihuhuang
     * createDate: 2011-03-10
     * remark: 结清账户用*/
    @Select(" SELECT ERYDAT,CRACCM,CRIRAT" +
            " FROM  ACTBLH" +
            " WHERE ORGIDT = #{orgidt}" +
            "    AND CUSIDT = #{cusidt}" +
            "    AND APCODE = #{apcode}" +
            "    AND CURCDE = #{curcde}" +
            "    AND ERYDAT >= #{erydat}" +
            " ORDER BY ERYDAT")
    List<Actblh> selectCompareErydat(@Param("orgidt") String orgidt,@Param("cusidt") String cusidt,
                                     @Param("apcode") String apcode,@Param("curcde") String curcde,@Param("erydat") Date erydat);
}