package cbs.repository.account.maininfo.dao;

import cbs.repository.account.ext.domain.ActnoName;
import cbs.repository.account.maininfo.model.Actoac;
import cbs.repository.account.maininfo.model.ActoacExample;
import cbs.repository.account.maininfo.model.ActoacInfo;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface ActoacMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTOAC
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    int countByExample(ActoacExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTOAC
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    int deleteByExample(ActoacExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTOAC
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    int insert(Actoac record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTOAC
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    int insertSelective(Actoac record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTOAC
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    List<Actoac> selectByExample(ActoacExample example);
    List<ActoacInfo> selectOLDACNsetRecord(@Param("oldacn")String oldacn,@Param("actnam") String actnam);
    List<ActoacInfo> selectAllRecords();
    List<ActoacInfo> selectSlpRecords();
    List<ActoacInfo> selectRegRecords();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTOAC
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    int updateByExampleSelective(@Param("record") Actoac record, @Param("example") ActoacExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTOAC
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    int updateByExample(@Param("record") Actoac record, @Param("example") ActoacExample example);
    /**
     * 查询账户号和账户名
     */
    @Select("select oldacn as accode,actnam from actani ani join actoac act on ani.cusidt = act.cusidt and ani.curcde = act.curcde and ani.apcode = act.apcode and trim(ani.oldacn) = #{accode}")
    ActnoName selectActnoNameByNo(@Param("accode") String accode);
}