package cbs.repository.account.maininfo.dao;

import cbs.repository.account.maininfo.model.Actobf;
import cbs.repository.account.maininfo.model.ActobfExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ActobfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTOBF
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    int countByExample(ActobfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTOBF
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    int deleteByExample(ActobfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTOBF
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    int insert(Actobf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTOBF
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    int insertSelective(Actobf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTOBF
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    List<Actobf> selectByExample(ActobfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTOBF
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    int updateByExampleSelective(@Param("record") Actobf record, @Param("example") ActobfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTOBF
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    int updateByExample(@Param("record") Actobf record, @Param("example") ActobfExample example);

    /**
     * zhanrui    select  for update
     * @param example
     * @return
     */
    List<Actobf> selectByExampleForUpdate(ActobfExample example);

    /*
    * createBy: haihu
    * createDate:
    * remark: πÿ±’’Àªß”√*/
    Actobf selectByPKForlock(@Param("sysidt") String sysidt,
                             @Param("orgidt") String orgidt, @Param("cusidt") String cusidt, @Param("apcode") String apcode,
                             @Param("curcde") String curcde);

}