package cbs.repository.account.maininfo.dao;

import cbs.repository.account.maininfo.model.ActvchForGlDRpt;
import cbs.repository.account.maininfo.model.Actvth;
import cbs.repository.account.maininfo.model.ActvthExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActvthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTVTH
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    int countByExample(ActvthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTVTH
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    int deleteByExample(ActvthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTVTH
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    int insert(Actvth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTVTH
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    int insertSelective(Actvth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTVTH
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    List<Actvth> selectByExample(ActvthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTVTH
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    int updateByExampleSelective(@Param("record") Actvth record, @Param("example") ActvthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTVTH
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    int updateByExample(@Param("record") Actvth record, @Param("example") ActvthExample example);

    /**
    * createBy: haiyuhuang
     * date:    2010-12-13*/
    List<ActvchForGlDRpt> selectForGlDRpt(@Param("orgidt") String orgidt,@Param("curcde") String curcde,@Param("glcode") String glcode);

    /**
     * createBy: haiyuhuang
     * date:     2010-12-15
     * remark: 按照科目，币种分类*/
    List<ActvchForGlDRpt> selectForGlCur(@Param("orgidt") String orgidt);

}