package cbs.repository.account.maininfo.dao;

import cbs.repository.account.ext.domain.ActvchModel;
import cbs.repository.account.ext.domain.BatchBookReviewVO;
import cbs.repository.account.maininfo.model.Actvch;
import cbs.repository.account.maininfo.model.ActvchExample;
import cbs.repository.account.maininfo.model.ActvchForGlDRpt;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.math.BigDecimal;
import java.util.List;

public interface ActvchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTVCH
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    int countByExample(ActvchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTVCH
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    int deleteByExample(ActvchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTVCH
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    int insert(Actvch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTVCH
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    int insertSelective(Actvch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTVCH
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    List<Actvch> selectByExample(ActvchExample example);

    /**
     * createBy: haiyuhuang
     * createDate: 2010-12-13*/
    @Select("SELECT  CURCDE,TXNAMT,SECCCY,CRNYER," +
            " TLRNUM,VCHSET,SETSEQ,RVSLBL,ORGIDT,ORGID3" +
            " FROM  ACTVCH WHERE  RECSTS = #{recsts}" +
            " ORDER  BY CURCDE,ORGIDT,TLRNUM,VCHSET,ORGID3")
    List<Actvch> selectByRecsts(@Param("recsts") String recsts);
    /**
     * createBy: haiyuhuang
     * date:    2010-12-13*/
    List<ActvchForGlDRpt> selectForGlDRpt(@Param("orgidt") String orgidt,@Param("curcde") String curcde,@Param("glcode") String glcode);

    /**
     * createBy: haiyuhuang
     * date:     2010-12-15
     * remark: 按照科目，币种分类*/
    List<ActvchForGlDRpt> selectForGlCur(@Param("orgidt") String orgidt);

    /**
     * 查询条件： private String tlrnum;         --
     *private String vchset;    --
     private String curcde;--
     private String glcode;
     private String apcode;
     private String txnamt;
     private String accode;
     private String cusidt;
     wanglichao
     * 增加查询条件：交易类型,凭证种类，及金额的范围
     */
    List<ActvchModel> selectByCondition(@Param("tlrnum") String tlrnum,@Param("cusidt") String cusidt,
                                        @Param("vchset") String vchset,@Param("curcde") String curcde,@Param("glcode") String glcode,
                                        @Param("apcode") String apcode,@Param("txnamt") String txnamt,@Param("accode") String accode,
                                        @Param("borlen") String borlen,@Param("anacde") String anacde,@Param("rvslbl") String rvslbl,
                                        @Param("minamt") String minamt,@Param("maxamt") String maxamt);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTVCH
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    int updateByExampleSelective(@Param("record") Actvch record, @Param("example") ActvchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTVCH
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    int updateByExample(@Param("record") Actvch record, @Param("example") ActvchExample example);


    /**
     * 查询待复核的记录  zhanrui 20100302
     * @param sysidt
     * @param orgidt
     * @param tlrnum
     * @return
     */
    List<BatchBookReviewVO> selectNeedReviewRecords(@Param("sysidt")String sysidt,@Param("orgidt")String orgidt, @Param("tlrnum")String tlrnum, @Param("vchset")short vchset);
    /**
     * 查询已复核的记录  zhanrui 20100302
     * @param sysidt
     * @param orgidt
     * @param tlrnum
     * @return
     */
    List<BatchBookReviewVO> selectReviewedRecords(@Param("sysidt")String sysidt,@Param("orgidt")String orgidt, @Param("tlrnum")String tlrnum, @Param("vchset")short vchset);

    /**
     * 复核数据
     * @param record
     * @return
     */
    List<Actvch> reviewRecord(@Param("record") Actvch record);
}