package cbs.repository.account.maininfo.dao;

import cbs.repository.account.maininfo.model.CpSequence;
import cbs.repository.account.maininfo.model.CpSequenceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CpSequenceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CP_SEQUENCE
     *
     * @mbggenerated Mon Nov 29 09:48:09 CST 2010
     */
    int countByExample(CpSequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CP_SEQUENCE
     *
     * @mbggenerated Mon Nov 29 09:48:09 CST 2010
     */
    int deleteByExample(CpSequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CP_SEQUENCE
     *
     * @mbggenerated Mon Nov 29 09:48:09 CST 2010
     */
    int insert(CpSequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CP_SEQUENCE
     *
     * @mbggenerated Mon Nov 29 09:48:09 CST 2010
     */
    int insertSelective(CpSequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CP_SEQUENCE
     *
     * @mbggenerated Mon Nov 29 09:48:09 CST 2010
     */
    List<CpSequence> selectByExample(CpSequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CP_SEQUENCE
     *
     * @mbggenerated Mon Nov 29 09:48:09 CST 2010
     */
    int updateByExampleSelective(@Param("record") CpSequence record, @Param("example") CpSequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CP_SEQUENCE
     *
     * @mbggenerated Mon Nov 29 09:48:09 CST 2010
     */
    int updateByExample(@Param("record") CpSequence record, @Param("example") CpSequenceExample example);

    /*
    *更新当前最大值+1 */
    void updateCurvaluePlus1();

    /*锁读*/
    List<CpSequence> selectByExampleForupdate(CpSequenceExample example);
}