package cbs.repository.account.billinfo.model;

public class ActlgcKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTLGC.APCODE
     *
     * @mbggenerated Wed Mar 02 09:29:45 CST 2011
     */
    private String apcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTLGC.CURCDE
     *
     * @mbggenerated Wed Mar 02 09:29:45 CST 2011
     */
    private String curcde;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTLGC.CUSIDT
     *
     * @mbggenerated Wed Mar 02 09:29:45 CST 2011
     */
    private String cusidt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTLGC.LEGPNY
     *
     * @mbggenerated Wed Mar 02 09:29:45 CST 2011
     */
    private Short legpny;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTLGC.NLEGPG
     *
     * @mbggenerated Wed Mar 02 09:29:45 CST 2011
     */
    private Integer nlegpg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTLGC.ORGIDT
     *
     * @mbggenerated Wed Mar 02 09:29:45 CST 2011
     */
    private String orgidt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTLGC.PAGLIN
     *
     * @mbggenerated Wed Mar 02 09:29:45 CST 2011
     */
    private Short paglin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTLGC.SYSIDT
     *
     * @mbggenerated Wed Mar 02 09:29:45 CST 2011
     */
    private String sysidt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTLGC.APCODE
     *
     * @return the value of ACTLGC.APCODE
     *
     * @mbggenerated Wed Mar 02 09:29:45 CST 2011
     */
    public String getApcode() {
        return apcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTLGC.APCODE
     *
     * @param apcode the value for ACTLGC.APCODE
     *
     * @mbggenerated Wed Mar 02 09:29:45 CST 2011
     */
    public void setApcode(String apcode) {
        this.apcode = apcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTLGC.CURCDE
     *
     * @return the value of ACTLGC.CURCDE
     *
     * @mbggenerated Wed Mar 02 09:29:45 CST 2011
     */
    public String getCurcde() {
        return curcde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTLGC.CURCDE
     *
     * @param curcde the value for ACTLGC.CURCDE
     *
     * @mbggenerated Wed Mar 02 09:29:45 CST 2011
     */
    public void setCurcde(String curcde) {
        this.curcde = curcde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTLGC.CUSIDT
     *
     * @return the value of ACTLGC.CUSIDT
     *
     * @mbggenerated Wed Mar 02 09:29:45 CST 2011
     */
    public String getCusidt() {
        return cusidt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTLGC.CUSIDT
     *
     * @param cusidt the value for ACTLGC.CUSIDT
     *
     * @mbggenerated Wed Mar 02 09:29:45 CST 2011
     */
    public void setCusidt(String cusidt) {
        this.cusidt = cusidt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTLGC.LEGPNY
     *
     * @return the value of ACTLGC.LEGPNY
     *
     * @mbggenerated Wed Mar 02 09:29:45 CST 2011
     */
    public Short getLegpny() {
        return legpny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTLGC.LEGPNY
     *
     * @param legpny the value for ACTLGC.LEGPNY
     *
     * @mbggenerated Wed Mar 02 09:29:45 CST 2011
     */
    public void setLegpny(Short legpny) {
        this.legpny = legpny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTLGC.NLEGPG
     *
     * @return the value of ACTLGC.NLEGPG
     *
     * @mbggenerated Wed Mar 02 09:29:45 CST 2011
     */
    public Integer getNlegpg() {
        return nlegpg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTLGC.NLEGPG
     *
     * @param nlegpg the value for ACTLGC.NLEGPG
     *
     * @mbggenerated Wed Mar 02 09:29:45 CST 2011
     */
    public void setNlegpg(Integer nlegpg) {
        this.nlegpg = nlegpg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTLGC.ORGIDT
     *
     * @return the value of ACTLGC.ORGIDT
     *
     * @mbggenerated Wed Mar 02 09:29:45 CST 2011
     */
    public String getOrgidt() {
        return orgidt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTLGC.ORGIDT
     *
     * @param orgidt the value for ACTLGC.ORGIDT
     *
     * @mbggenerated Wed Mar 02 09:29:45 CST 2011
     */
    public void setOrgidt(String orgidt) {
        this.orgidt = orgidt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTLGC.PAGLIN
     *
     * @return the value of ACTLGC.PAGLIN
     *
     * @mbggenerated Wed Mar 02 09:29:45 CST 2011
     */
    public Short getPaglin() {
        return paglin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTLGC.PAGLIN
     *
     * @param paglin the value for ACTLGC.PAGLIN
     *
     * @mbggenerated Wed Mar 02 09:29:45 CST 2011
     */
    public void setPaglin(Short paglin) {
        this.paglin = paglin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTLGC.SYSIDT
     *
     * @return the value of ACTLGC.SYSIDT
     *
     * @mbggenerated Wed Mar 02 09:29:45 CST 2011
     */
    public String getSysidt() {
        return sysidt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTLGC.SYSIDT
     *
     * @param sysidt the value for ACTLGC.SYSIDT
     *
     * @mbggenerated Wed Mar 02 09:29:45 CST 2011
     */
    public void setSysidt(String sysidt) {
        this.sysidt = sysidt;
    }
}