package cbs.repository.code.model;

import cbs.common.IbatisFactory;
import cbs.common.enums.ACEnum;
import cbs.repository.code.dao.ActapcMapper;
import org.apache.ibatis.session.SqlSession;
import org.apache.ibatis.session.SqlSessionFactory;

import javax.faces.model.SelectItem;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class Actapc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTAPC.APCODE
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String apcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTAPC.APCNAM
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String apcnam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTAPC.APCTYP
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String apctyp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTAPC.GLCODE
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String glcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTAPC.PLCODE
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String plcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTAPC.INTEXP
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String intexp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTAPC.INTINC
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String intinc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTAPC.OPSAPC
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String opsapc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTAPC.APCDCR
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String apcdcr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTAPC.INTDAC
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String intdac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTAPC.INTCAC
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String intcac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTAPC.NDRINT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String ndrint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTAPC.NCRINT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String ncrint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTAPC.APCKID
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String apckid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTAPC.AMDTLR
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String amdtlr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTAPC.UPDDAT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private Date upddat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTAPC.RECSTS
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String recsts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTAPC.APCODE
     *
     * @return the value of ACTAPC.APCODE
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getApcode() {
        return apcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTAPC.APCODE
     *
     * @param apcode the value for ACTAPC.APCODE
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setApcode(String apcode) {
        this.apcode = apcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTAPC.APCNAM
     *
     * @return the value of ACTAPC.APCNAM
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getApcnam() {
        return apcnam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTAPC.APCNAM
     *
     * @param apcnam the value for ACTAPC.APCNAM
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setApcnam(String apcnam) {
        this.apcnam = apcnam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTAPC.APCTYP
     *
     * @return the value of ACTAPC.APCTYP
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getApctyp() {
        return apctyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTAPC.APCTYP
     *
     * @param apctyp the value for ACTAPC.APCTYP
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setApctyp(String apctyp) {
        this.apctyp = apctyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTAPC.GLCODE
     *
     * @return the value of ACTAPC.GLCODE
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getGlcode() {
        return glcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTAPC.GLCODE
     *
     * @param glcode the value for ACTAPC.GLCODE
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setGlcode(String glcode) {
        this.glcode = glcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTAPC.PLCODE
     *
     * @return the value of ACTAPC.PLCODE
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getPlcode() {
        return plcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTAPC.PLCODE
     *
     * @param plcode the value for ACTAPC.PLCODE
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setPlcode(String plcode) {
        this.plcode = plcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTAPC.INTEXP
     *
     * @return the value of ACTAPC.INTEXP
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getIntexp() {
        return intexp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTAPC.INTEXP
     *
     * @param intexp the value for ACTAPC.INTEXP
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setIntexp(String intexp) {
        this.intexp = intexp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTAPC.INTINC
     *
     * @return the value of ACTAPC.INTINC
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getIntinc() {
        return intinc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTAPC.INTINC
     *
     * @param intinc the value for ACTAPC.INTINC
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setIntinc(String intinc) {
        this.intinc = intinc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTAPC.OPSAPC
     *
     * @return the value of ACTAPC.OPSAPC
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getOpsapc() {
        return opsapc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTAPC.OPSAPC
     *
     * @param opsapc the value for ACTAPC.OPSAPC
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setOpsapc(String opsapc) {
        this.opsapc = opsapc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTAPC.APCDCR
     *
     * @return the value of ACTAPC.APCDCR
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getApcdcr() {
        return apcdcr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTAPC.APCDCR
     *
     * @param apcdcr the value for ACTAPC.APCDCR
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setApcdcr(String apcdcr) {
        this.apcdcr = apcdcr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTAPC.INTDAC
     *
     * @return the value of ACTAPC.INTDAC
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getIntdac() {
        return intdac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTAPC.INTDAC
     *
     * @param intdac the value for ACTAPC.INTDAC
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setIntdac(String intdac) {
        this.intdac = intdac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTAPC.INTCAC
     *
     * @return the value of ACTAPC.INTCAC
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getIntcac() {
        return intcac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTAPC.INTCAC
     *
     * @param intcac the value for ACTAPC.INTCAC
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setIntcac(String intcac) {
        this.intcac = intcac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTAPC.NDRINT
     *
     * @return the value of ACTAPC.NDRINT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getNdrint() {
        return ndrint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTAPC.NDRINT
     *
     * @param ndrint the value for ACTAPC.NDRINT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setNdrint(String ndrint) {
        this.ndrint = ndrint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTAPC.NCRINT
     *
     * @return the value of ACTAPC.NCRINT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getNcrint() {
        return ncrint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTAPC.NCRINT
     *
     * @param ncrint the value for ACTAPC.NCRINT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setNcrint(String ncrint) {
        this.ncrint = ncrint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTAPC.APCKID
     *
     * @return the value of ACTAPC.APCKID
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getApckid() {
        return apckid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTAPC.APCKID
     *
     * @param apckid the value for ACTAPC.APCKID
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setApckid(String apckid) {
        this.apckid = apckid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTAPC.AMDTLR
     *
     * @return the value of ACTAPC.AMDTLR
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getAmdtlr() {
        return amdtlr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTAPC.AMDTLR
     *
     * @param amdtlr the value for ACTAPC.AMDTLR
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setAmdtlr(String amdtlr) {
        this.amdtlr = amdtlr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTAPC.UPDDAT
     *
     * @return the value of ACTAPC.UPDDAT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public Date getUpddat() {
        return upddat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTAPC.UPDDAT
     *
     * @param upddat the value for ACTAPC.UPDDAT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setUpddat(Date upddat) {
        this.upddat = upddat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTAPC.RECSTS
     *
     * @return the value of ACTAPC.RECSTS
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getRecsts() {
        return recsts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTAPC.RECSTS
     *
     * @param recsts the value for ACTAPC.RECSTS
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setRecsts(String recsts) {
        this.recsts = recsts;
    }
    /*
    * 按核算码查询获得总账码*/
    public String getGLCODE(String apcode) {
        SqlSessionFactory sessionFactory;
        sessionFactory = IbatisFactory.ORACLE.getInstance();
        SqlSession session = sessionFactory.openSession();
        ActapcMapper apcmap = session.getMapper(ActapcMapper.class);
        ActapcExample apcexam = new ActapcExample();
        apcexam.createCriteria().andApcodeEqualTo(apcode);
        List<Actapc> apcLst = apcmap.selectByExample(apcexam);
        Iterator it = apcLst.iterator();
        String glcode = "";
        while (it.hasNext()) {
            Actapc apc = (Actapc)it.next();
            glcode = apc.getGlcode();
        }
        return glcode;
    }
    /*
    * 取得表的所有数据*/
    public ArrayList<SelectItem> getAllData() {
        ActapcExample ae = new ActapcExample();
        ae.createCriteria().andRecstsEqualTo(ACEnum.RECSTS_VALID.getStatus());
        ae.setOrderByClause("apcode");
        ArrayList aList=new ArrayList();
        SelectItem siSpace = new SelectItem("","");
        aList.add(siSpace);
        SqlSessionFactory sessionFactory;
        sessionFactory = IbatisFactory.ORACLE.getInstance();
        SqlSession session = sessionFactory.openSession();
        try {
            ActapcMapper mapper = session.getMapper(ActapcMapper.class);
            List<Actapc> ls = mapper.selectByExample(ae);
            Iterator it = ls.iterator();
            while (it.hasNext()) {
                Actapc m = (Actapc)it.next();
                int i=0;
                String val = "";
                String lbl = "";
                val = m.getApcode();
                lbl = val + " " + m.getApcnam();
                SelectItem si = new SelectItem(val,lbl);
                aList.add(si);
            }
        } finally {
            session.close();
        }
        return aList;
    }

    /**
     * 根据actglc.glccat的条件取得数据*/
    public ArrayList<SelectItem> getData(String glccat) throws Exception {
        ArrayList aList=new ArrayList();
        SelectItem siSpace = new SelectItem("","");
        aList.add(siSpace);
        SqlSessionFactory sessionFactory;
        sessionFactory = IbatisFactory.ORACLE.getInstance();
        SqlSession session = sessionFactory.openSession();
        try {
            ActapcMapper mapper = session.getMapper(ActapcMapper.class);
            List<Actapc> ls = mapper.selectApcByGlccat(glccat);
            Iterator it = ls.iterator();
            while (it.hasNext()) {
                Actapc m = (Actapc)it.next();
                int i=0;
                String val = "";
                String lbl = "";
                val = m.getApcode();
                lbl = val + " " + m.getApcnam();
                SelectItem si = new SelectItem(val,lbl);
                aList.add(si);
            }
        } catch (Exception ex) {
            throw ex;
        }
        finally {
            session.close();
        }
        return aList;
    }

}