package cbs.repository.code.model;

import cbs.common.IbatisFactory;
import cbs.common.enums.ACEnum;
import cbs.repository.code.dao.ActccyMapper;
import org.apache.ibatis.session.SqlSession;
import org.apache.ibatis.session.SqlSessionFactory;

import javax.faces.model.SelectItem;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class Actccy {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTCCY.CURCDE
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String curcde;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTCCY.CURNMC
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String curnmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTCCY.CURNME
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String curnme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTCCY.DOMCDE
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String domcde;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTCCY.INTCUR
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String intcur;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTCCY.CURUNT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private Integer curunt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTCCY.DECPOS
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private Short decpos;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTCCY.EXCFLG
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String excflg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTCCY.EXCUNT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private BigDecimal excunt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTCCY.MINUNT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private BigDecimal minunt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTCCY.CUTFLG
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String cutflg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTCCY.WEIGHT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTCCY.INTDAY
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String intday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTCCY.SPEFLG
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String speflg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTCCY.HOLFLG
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String holflg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTCCY.CLRFLG
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String clrflg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTCCY.EFFDAT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private Date effdat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTCCY.EXPDAT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private Date expdat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTCCY.AMDTLR
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String amdtlr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTCCY.UPDDAT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private Date upddat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTCCY.RECSTS
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String recsts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTCCY.CURCDE
     *
     * @return the value of ACTCCY.CURCDE
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getCurcde() {
        return curcde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTCCY.CURCDE
     *
     * @param curcde the value for ACTCCY.CURCDE
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setCurcde(String curcde) {
        this.curcde = curcde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTCCY.CURNMC
     *
     * @return the value of ACTCCY.CURNMC
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getCurnmc() {
        return curnmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTCCY.CURNMC
     *
     * @param curnmc the value for ACTCCY.CURNMC
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setCurnmc(String curnmc) {
        this.curnmc = curnmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTCCY.CURNME
     *
     * @return the value of ACTCCY.CURNME
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getCurnme() {
        return curnme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTCCY.CURNME
     *
     * @param curnme the value for ACTCCY.CURNME
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setCurnme(String curnme) {
        this.curnme = curnme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTCCY.DOMCDE
     *
     * @return the value of ACTCCY.DOMCDE
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getDomcde() {
        return domcde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTCCY.DOMCDE
     *
     * @param domcde the value for ACTCCY.DOMCDE
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setDomcde(String domcde) {
        this.domcde = domcde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTCCY.INTCUR
     *
     * @return the value of ACTCCY.INTCUR
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getIntcur() {
        return intcur;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTCCY.INTCUR
     *
     * @param intcur the value for ACTCCY.INTCUR
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setIntcur(String intcur) {
        this.intcur = intcur;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTCCY.CURUNT
     *
     * @return the value of ACTCCY.CURUNT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public Integer getCurunt() {
        return curunt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTCCY.CURUNT
     *
     * @param curunt the value for ACTCCY.CURUNT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setCurunt(Integer curunt) {
        this.curunt = curunt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTCCY.DECPOS
     *
     * @return the value of ACTCCY.DECPOS
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public Short getDecpos() {
        return decpos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTCCY.DECPOS
     *
     * @param decpos the value for ACTCCY.DECPOS
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setDecpos(Short decpos) {
        this.decpos = decpos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTCCY.EXCFLG
     *
     * @return the value of ACTCCY.EXCFLG
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getExcflg() {
        return excflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTCCY.EXCFLG
     *
     * @param excflg the value for ACTCCY.EXCFLG
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setExcflg(String excflg) {
        this.excflg = excflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTCCY.EXCUNT
     *
     * @return the value of ACTCCY.EXCUNT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public BigDecimal getExcunt() {
        return excunt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTCCY.EXCUNT
     *
     * @param excunt the value for ACTCCY.EXCUNT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setExcunt(BigDecimal excunt) {
        this.excunt = excunt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTCCY.MINUNT
     *
     * @return the value of ACTCCY.MINUNT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public BigDecimal getMinunt() {
        return minunt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTCCY.MINUNT
     *
     * @param minunt the value for ACTCCY.MINUNT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setMinunt(BigDecimal minunt) {
        this.minunt = minunt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTCCY.CUTFLG
     *
     * @return the value of ACTCCY.CUTFLG
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getCutflg() {
        return cutflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTCCY.CUTFLG
     *
     * @param cutflg the value for ACTCCY.CUTFLG
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setCutflg(String cutflg) {
        this.cutflg = cutflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTCCY.WEIGHT
     *
     * @return the value of ACTCCY.WEIGHT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTCCY.WEIGHT
     *
     * @param weight the value for ACTCCY.WEIGHT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setWeight(String weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTCCY.INTDAY
     *
     * @return the value of ACTCCY.INTDAY
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getIntday() {
        return intday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTCCY.INTDAY
     *
     * @param intday the value for ACTCCY.INTDAY
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setIntday(String intday) {
        this.intday = intday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTCCY.SPEFLG
     *
     * @return the value of ACTCCY.SPEFLG
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getSpeflg() {
        return speflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTCCY.SPEFLG
     *
     * @param speflg the value for ACTCCY.SPEFLG
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setSpeflg(String speflg) {
        this.speflg = speflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTCCY.HOLFLG
     *
     * @return the value of ACTCCY.HOLFLG
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getHolflg() {
        return holflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTCCY.HOLFLG
     *
     * @param holflg the value for ACTCCY.HOLFLG
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setHolflg(String holflg) {
        this.holflg = holflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTCCY.CLRFLG
     *
     * @return the value of ACTCCY.CLRFLG
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getClrflg() {
        return clrflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTCCY.CLRFLG
     *
     * @param clrflg the value for ACTCCY.CLRFLG
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setClrflg(String clrflg) {
        this.clrflg = clrflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTCCY.EFFDAT
     *
     * @return the value of ACTCCY.EFFDAT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public Date getEffdat() {
        return effdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTCCY.EFFDAT
     *
     * @param effdat the value for ACTCCY.EFFDAT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setEffdat(Date effdat) {
        this.effdat = effdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTCCY.EXPDAT
     *
     * @return the value of ACTCCY.EXPDAT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public Date getExpdat() {
        return expdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTCCY.EXPDAT
     *
     * @param expdat the value for ACTCCY.EXPDAT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setExpdat(Date expdat) {
        this.expdat = expdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTCCY.AMDTLR
     *
     * @return the value of ACTCCY.AMDTLR
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getAmdtlr() {
        return amdtlr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTCCY.AMDTLR
     *
     * @param amdtlr the value for ACTCCY.AMDTLR
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setAmdtlr(String amdtlr) {
        this.amdtlr = amdtlr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTCCY.UPDDAT
     *
     * @return the value of ACTCCY.UPDDAT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public Date getUpddat() {
        return upddat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTCCY.UPDDAT
     *
     * @param upddat the value for ACTCCY.UPDDAT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setUpddat(Date upddat) {
        this.upddat = upddat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTCCY.RECSTS
     *
     * @return the value of ACTCCY.RECSTS
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getRecsts() {
        return recsts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTCCY.RECSTS
     *
     * @param recsts the value for ACTCCY.RECSTS
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setRecsts(String recsts) {
        this.recsts = recsts;
    }

    public ArrayList<SelectItem> getAllData() {
        ActccyExample ae = new ActccyExample();
        ae.createCriteria().andRecstsEqualTo(ACEnum.RECSTS_VALID.getStatus());
        ae.setOrderByClause("curcde");
        ArrayList aList=new ArrayList();
        SqlSessionFactory sessionFactory;
        sessionFactory = IbatisFactory.ORACLE.getInstance();
        SqlSession session = sessionFactory.openSession();
        try {
            ActccyMapper mapper = session.getMapper(ActccyMapper.class);
            List<Actccy> ls = mapper.selectByExample(ae);
            Iterator it = ls.iterator();
            while (it.hasNext()) {
                Actccy m = (Actccy)it.next();
                int i=0;
                String val = "";
                String lbl = "";
                val = m.getCurcde();
                lbl = val + " " + m.getCurnmc();
                SelectItem si = new SelectItem(val,lbl);
                aList.add(si);
            }
        } finally {
            session.close();
        }
        return aList;
    }
}