package cbs.repository.code.model;

import java.util.Date;

public class Actery {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTERY.PRDCDE
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String prdcde;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTERY.EVTCDE
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String evtcde;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTERY.CTPCDE
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String ctpcde;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTERY.CATCDE
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String catcde;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTERY.ERYSEQ
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private Short eryseq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTERY.ORGIDT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String orgidt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTERY.CUSIDT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String cusidt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTERY.APCODE
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String apcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTERY.CURCDE
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String curcde;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTERY.ERYAMT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String eryamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTERY.CDRFLG
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private Short cdrflg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTERY.VCHPAR
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String vchpar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTERY.TOTNUM
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private Short totnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTERY.CORCUR
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String corcur;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTERY.CORAPC
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String corapc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTERY.ERYREM
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String eryrem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTERY.AMDTLR
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String amdtlr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTERY.UPDDAT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private Date upddat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTERY.RECSTS
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String recsts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTERY.PRDCDE
     *
     * @return the value of ACTERY.PRDCDE
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getPrdcde() {
        return prdcde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTERY.PRDCDE
     *
     * @param prdcde the value for ACTERY.PRDCDE
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setPrdcde(String prdcde) {
        this.prdcde = prdcde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTERY.EVTCDE
     *
     * @return the value of ACTERY.EVTCDE
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getEvtcde() {
        return evtcde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTERY.EVTCDE
     *
     * @param evtcde the value for ACTERY.EVTCDE
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setEvtcde(String evtcde) {
        this.evtcde = evtcde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTERY.CTPCDE
     *
     * @return the value of ACTERY.CTPCDE
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getCtpcde() {
        return ctpcde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTERY.CTPCDE
     *
     * @param ctpcde the value for ACTERY.CTPCDE
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setCtpcde(String ctpcde) {
        this.ctpcde = ctpcde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTERY.CATCDE
     *
     * @return the value of ACTERY.CATCDE
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getCatcde() {
        return catcde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTERY.CATCDE
     *
     * @param catcde the value for ACTERY.CATCDE
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setCatcde(String catcde) {
        this.catcde = catcde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTERY.ERYSEQ
     *
     * @return the value of ACTERY.ERYSEQ
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public Short getEryseq() {
        return eryseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTERY.ERYSEQ
     *
     * @param eryseq the value for ACTERY.ERYSEQ
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setEryseq(Short eryseq) {
        this.eryseq = eryseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTERY.ORGIDT
     *
     * @return the value of ACTERY.ORGIDT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getOrgidt() {
        return orgidt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTERY.ORGIDT
     *
     * @param orgidt the value for ACTERY.ORGIDT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setOrgidt(String orgidt) {
        this.orgidt = orgidt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTERY.CUSIDT
     *
     * @return the value of ACTERY.CUSIDT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getCusidt() {
        return cusidt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTERY.CUSIDT
     *
     * @param cusidt the value for ACTERY.CUSIDT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setCusidt(String cusidt) {
        this.cusidt = cusidt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTERY.APCODE
     *
     * @return the value of ACTERY.APCODE
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getApcode() {
        return apcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTERY.APCODE
     *
     * @param apcode the value for ACTERY.APCODE
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setApcode(String apcode) {
        this.apcode = apcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTERY.CURCDE
     *
     * @return the value of ACTERY.CURCDE
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getCurcde() {
        return curcde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTERY.CURCDE
     *
     * @param curcde the value for ACTERY.CURCDE
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setCurcde(String curcde) {
        this.curcde = curcde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTERY.ERYAMT
     *
     * @return the value of ACTERY.ERYAMT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getEryamt() {
        return eryamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTERY.ERYAMT
     *
     * @param eryamt the value for ACTERY.ERYAMT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setEryamt(String eryamt) {
        this.eryamt = eryamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTERY.CDRFLG
     *
     * @return the value of ACTERY.CDRFLG
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public Short getCdrflg() {
        return cdrflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTERY.CDRFLG
     *
     * @param cdrflg the value for ACTERY.CDRFLG
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setCdrflg(Short cdrflg) {
        this.cdrflg = cdrflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTERY.VCHPAR
     *
     * @return the value of ACTERY.VCHPAR
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getVchpar() {
        return vchpar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTERY.VCHPAR
     *
     * @param vchpar the value for ACTERY.VCHPAR
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setVchpar(String vchpar) {
        this.vchpar = vchpar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTERY.TOTNUM
     *
     * @return the value of ACTERY.TOTNUM
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public Short getTotnum() {
        return totnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTERY.TOTNUM
     *
     * @param totnum the value for ACTERY.TOTNUM
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setTotnum(Short totnum) {
        this.totnum = totnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTERY.CORCUR
     *
     * @return the value of ACTERY.CORCUR
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getCorcur() {
        return corcur;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTERY.CORCUR
     *
     * @param corcur the value for ACTERY.CORCUR
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setCorcur(String corcur) {
        this.corcur = corcur;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTERY.CORAPC
     *
     * @return the value of ACTERY.CORAPC
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getCorapc() {
        return corapc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTERY.CORAPC
     *
     * @param corapc the value for ACTERY.CORAPC
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setCorapc(String corapc) {
        this.corapc = corapc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTERY.ERYREM
     *
     * @return the value of ACTERY.ERYREM
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getEryrem() {
        return eryrem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTERY.ERYREM
     *
     * @param eryrem the value for ACTERY.ERYREM
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setEryrem(String eryrem) {
        this.eryrem = eryrem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTERY.AMDTLR
     *
     * @return the value of ACTERY.AMDTLR
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getAmdtlr() {
        return amdtlr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTERY.AMDTLR
     *
     * @param amdtlr the value for ACTERY.AMDTLR
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setAmdtlr(String amdtlr) {
        this.amdtlr = amdtlr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTERY.UPDDAT
     *
     * @return the value of ACTERY.UPDDAT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public Date getUpddat() {
        return upddat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTERY.UPDDAT
     *
     * @param upddat the value for ACTERY.UPDDAT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setUpddat(Date upddat) {
        this.upddat = upddat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTERY.RECSTS
     *
     * @return the value of ACTERY.RECSTS
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getRecsts() {
        return recsts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTERY.RECSTS
     *
     * @param recsts the value for ACTERY.RECSTS
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setRecsts(String recsts) {
        this.recsts = recsts;
    }
}