package cbs.repository.code.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ActfrtExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ACTFRT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ACTFRT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ACTFRT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTFRT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public ActfrtExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTFRT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTFRT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTFRT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTFRT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTFRT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTFRT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTFRT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTFRT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTFRT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTFRT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ACTFRT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCurcdeIsNull() {
            addCriterion("CURCDE is null");
            return (Criteria) this;
        }

        public Criteria andCurcdeIsNotNull() {
            addCriterion("CURCDE is not null");
            return (Criteria) this;
        }

        public Criteria andCurcdeEqualTo(String value) {
            addCriterion("CURCDE =", value, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeNotEqualTo(String value) {
            addCriterion("CURCDE <>", value, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeGreaterThan(String value) {
            addCriterion("CURCDE >", value, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeGreaterThanOrEqualTo(String value) {
            addCriterion("CURCDE >=", value, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeLessThan(String value) {
            addCriterion("CURCDE <", value, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeLessThanOrEqualTo(String value) {
            addCriterion("CURCDE <=", value, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeLike(String value) {
            addCriterion("CURCDE like", value, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeNotLike(String value) {
            addCriterion("CURCDE not like", value, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeIn(List<String> values) {
            addCriterion("CURCDE in", values, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeNotIn(List<String> values) {
            addCriterion("CURCDE not in", values, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeBetween(String value1, String value2) {
            addCriterion("CURCDE between", value1, value2, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeNotBetween(String value1, String value2) {
            addCriterion("CURCDE not between", value1, value2, "curcde");
            return (Criteria) this;
        }

        public Criteria andEffdatIsNull() {
            addCriterion("EFFDAT is null");
            return (Criteria) this;
        }

        public Criteria andEffdatIsNotNull() {
            addCriterion("EFFDAT is not null");
            return (Criteria) this;
        }

        public Criteria andEffdatEqualTo(Date value) {
            addCriterion("EFFDAT =", value, "effdat");
            return (Criteria) this;
        }

        public Criteria andEffdatNotEqualTo(Date value) {
            addCriterion("EFFDAT <>", value, "effdat");
            return (Criteria) this;
        }

        public Criteria andEffdatGreaterThan(Date value) {
            addCriterion("EFFDAT >", value, "effdat");
            return (Criteria) this;
        }

        public Criteria andEffdatGreaterThanOrEqualTo(Date value) {
            addCriterion("EFFDAT >=", value, "effdat");
            return (Criteria) this;
        }

        public Criteria andEffdatLessThan(Date value) {
            addCriterion("EFFDAT <", value, "effdat");
            return (Criteria) this;
        }

        public Criteria andEffdatLessThanOrEqualTo(Date value) {
            addCriterion("EFFDAT <=", value, "effdat");
            return (Criteria) this;
        }

        public Criteria andEffdatIn(List<Date> values) {
            addCriterion("EFFDAT in", values, "effdat");
            return (Criteria) this;
        }

        public Criteria andEffdatNotIn(List<Date> values) {
            addCriterion("EFFDAT not in", values, "effdat");
            return (Criteria) this;
        }

        public Criteria andEffdatBetween(Date value1, Date value2) {
            addCriterion("EFFDAT between", value1, value2, "effdat");
            return (Criteria) this;
        }

        public Criteria andEffdatNotBetween(Date value1, Date value2) {
            addCriterion("EFFDAT not between", value1, value2, "effdat");
            return (Criteria) this;
        }

        public Criteria andFrtkd1IsNull() {
            addCriterion("FRTKD1 is null");
            return (Criteria) this;
        }

        public Criteria andFrtkd1IsNotNull() {
            addCriterion("FRTKD1 is not null");
            return (Criteria) this;
        }

        public Criteria andFrtkd1EqualTo(String value) {
            addCriterion("FRTKD1 =", value, "frtkd1");
            return (Criteria) this;
        }

        public Criteria andFrtkd1NotEqualTo(String value) {
            addCriterion("FRTKD1 <>", value, "frtkd1");
            return (Criteria) this;
        }

        public Criteria andFrtkd1GreaterThan(String value) {
            addCriterion("FRTKD1 >", value, "frtkd1");
            return (Criteria) this;
        }

        public Criteria andFrtkd1GreaterThanOrEqualTo(String value) {
            addCriterion("FRTKD1 >=", value, "frtkd1");
            return (Criteria) this;
        }

        public Criteria andFrtkd1LessThan(String value) {
            addCriterion("FRTKD1 <", value, "frtkd1");
            return (Criteria) this;
        }

        public Criteria andFrtkd1LessThanOrEqualTo(String value) {
            addCriterion("FRTKD1 <=", value, "frtkd1");
            return (Criteria) this;
        }

        public Criteria andFrtkd1Like(String value) {
            addCriterion("FRTKD1 like", value, "frtkd1");
            return (Criteria) this;
        }

        public Criteria andFrtkd1NotLike(String value) {
            addCriterion("FRTKD1 not like", value, "frtkd1");
            return (Criteria) this;
        }

        public Criteria andFrtkd1In(List<String> values) {
            addCriterion("FRTKD1 in", values, "frtkd1");
            return (Criteria) this;
        }

        public Criteria andFrtkd1NotIn(List<String> values) {
            addCriterion("FRTKD1 not in", values, "frtkd1");
            return (Criteria) this;
        }

        public Criteria andFrtkd1Between(String value1, String value2) {
            addCriterion("FRTKD1 between", value1, value2, "frtkd1");
            return (Criteria) this;
        }

        public Criteria andFrtkd1NotBetween(String value1, String value2) {
            addCriterion("FRTKD1 not between", value1, value2, "frtkd1");
            return (Criteria) this;
        }

        public Criteria andFrtkd2IsNull() {
            addCriterion("FRTKD2 is null");
            return (Criteria) this;
        }

        public Criteria andFrtkd2IsNotNull() {
            addCriterion("FRTKD2 is not null");
            return (Criteria) this;
        }

        public Criteria andFrtkd2EqualTo(String value) {
            addCriterion("FRTKD2 =", value, "frtkd2");
            return (Criteria) this;
        }

        public Criteria andFrtkd2NotEqualTo(String value) {
            addCriterion("FRTKD2 <>", value, "frtkd2");
            return (Criteria) this;
        }

        public Criteria andFrtkd2GreaterThan(String value) {
            addCriterion("FRTKD2 >", value, "frtkd2");
            return (Criteria) this;
        }

        public Criteria andFrtkd2GreaterThanOrEqualTo(String value) {
            addCriterion("FRTKD2 >=", value, "frtkd2");
            return (Criteria) this;
        }

        public Criteria andFrtkd2LessThan(String value) {
            addCriterion("FRTKD2 <", value, "frtkd2");
            return (Criteria) this;
        }

        public Criteria andFrtkd2LessThanOrEqualTo(String value) {
            addCriterion("FRTKD2 <=", value, "frtkd2");
            return (Criteria) this;
        }

        public Criteria andFrtkd2Like(String value) {
            addCriterion("FRTKD2 like", value, "frtkd2");
            return (Criteria) this;
        }

        public Criteria andFrtkd2NotLike(String value) {
            addCriterion("FRTKD2 not like", value, "frtkd2");
            return (Criteria) this;
        }

        public Criteria andFrtkd2In(List<String> values) {
            addCriterion("FRTKD2 in", values, "frtkd2");
            return (Criteria) this;
        }

        public Criteria andFrtkd2NotIn(List<String> values) {
            addCriterion("FRTKD2 not in", values, "frtkd2");
            return (Criteria) this;
        }

        public Criteria andFrtkd2Between(String value1, String value2) {
            addCriterion("FRTKD2 between", value1, value2, "frtkd2");
            return (Criteria) this;
        }

        public Criteria andFrtkd2NotBetween(String value1, String value2) {
            addCriterion("FRTKD2 not between", value1, value2, "frtkd2");
            return (Criteria) this;
        }

        public Criteria andFrtnamIsNull() {
            addCriterion("FRTNAM is null");
            return (Criteria) this;
        }

        public Criteria andFrtnamIsNotNull() {
            addCriterion("FRTNAM is not null");
            return (Criteria) this;
        }

        public Criteria andFrtnamEqualTo(String value) {
            addCriterion("FRTNAM =", value, "frtnam");
            return (Criteria) this;
        }

        public Criteria andFrtnamNotEqualTo(String value) {
            addCriterion("FRTNAM <>", value, "frtnam");
            return (Criteria) this;
        }

        public Criteria andFrtnamGreaterThan(String value) {
            addCriterion("FRTNAM >", value, "frtnam");
            return (Criteria) this;
        }

        public Criteria andFrtnamGreaterThanOrEqualTo(String value) {
            addCriterion("FRTNAM >=", value, "frtnam");
            return (Criteria) this;
        }

        public Criteria andFrtnamLessThan(String value) {
            addCriterion("FRTNAM <", value, "frtnam");
            return (Criteria) this;
        }

        public Criteria andFrtnamLessThanOrEqualTo(String value) {
            addCriterion("FRTNAM <=", value, "frtnam");
            return (Criteria) this;
        }

        public Criteria andFrtnamLike(String value) {
            addCriterion("FRTNAM like", value, "frtnam");
            return (Criteria) this;
        }

        public Criteria andFrtnamNotLike(String value) {
            addCriterion("FRTNAM not like", value, "frtnam");
            return (Criteria) this;
        }

        public Criteria andFrtnamIn(List<String> values) {
            addCriterion("FRTNAM in", values, "frtnam");
            return (Criteria) this;
        }

        public Criteria andFrtnamNotIn(List<String> values) {
            addCriterion("FRTNAM not in", values, "frtnam");
            return (Criteria) this;
        }

        public Criteria andFrtnamBetween(String value1, String value2) {
            addCriterion("FRTNAM between", value1, value2, "frtnam");
            return (Criteria) this;
        }

        public Criteria andFrtnamNotBetween(String value1, String value2) {
            addCriterion("FRTNAM not between", value1, value2, "frtnam");
            return (Criteria) this;
        }

        public Criteria andDoccdeIsNull() {
            addCriterion("DOCCDE is null");
            return (Criteria) this;
        }

        public Criteria andDoccdeIsNotNull() {
            addCriterion("DOCCDE is not null");
            return (Criteria) this;
        }

        public Criteria andDoccdeEqualTo(String value) {
            addCriterion("DOCCDE =", value, "doccde");
            return (Criteria) this;
        }

        public Criteria andDoccdeNotEqualTo(String value) {
            addCriterion("DOCCDE <>", value, "doccde");
            return (Criteria) this;
        }

        public Criteria andDoccdeGreaterThan(String value) {
            addCriterion("DOCCDE >", value, "doccde");
            return (Criteria) this;
        }

        public Criteria andDoccdeGreaterThanOrEqualTo(String value) {
            addCriterion("DOCCDE >=", value, "doccde");
            return (Criteria) this;
        }

        public Criteria andDoccdeLessThan(String value) {
            addCriterion("DOCCDE <", value, "doccde");
            return (Criteria) this;
        }

        public Criteria andDoccdeLessThanOrEqualTo(String value) {
            addCriterion("DOCCDE <=", value, "doccde");
            return (Criteria) this;
        }

        public Criteria andDoccdeLike(String value) {
            addCriterion("DOCCDE like", value, "doccde");
            return (Criteria) this;
        }

        public Criteria andDoccdeNotLike(String value) {
            addCriterion("DOCCDE not like", value, "doccde");
            return (Criteria) this;
        }

        public Criteria andDoccdeIn(List<String> values) {
            addCriterion("DOCCDE in", values, "doccde");
            return (Criteria) this;
        }

        public Criteria andDoccdeNotIn(List<String> values) {
            addCriterion("DOCCDE not in", values, "doccde");
            return (Criteria) this;
        }

        public Criteria andDoccdeBetween(String value1, String value2) {
            addCriterion("DOCCDE between", value1, value2, "doccde");
            return (Criteria) this;
        }

        public Criteria andDoccdeNotBetween(String value1, String value2) {
            addCriterion("DOCCDE not between", value1, value2, "doccde");
            return (Criteria) this;
        }

        public Criteria andDocnamIsNull() {
            addCriterion("DOCNAM is null");
            return (Criteria) this;
        }

        public Criteria andDocnamIsNotNull() {
            addCriterion("DOCNAM is not null");
            return (Criteria) this;
        }

        public Criteria andDocnamEqualTo(String value) {
            addCriterion("DOCNAM =", value, "docnam");
            return (Criteria) this;
        }

        public Criteria andDocnamNotEqualTo(String value) {
            addCriterion("DOCNAM <>", value, "docnam");
            return (Criteria) this;
        }

        public Criteria andDocnamGreaterThan(String value) {
            addCriterion("DOCNAM >", value, "docnam");
            return (Criteria) this;
        }

        public Criteria andDocnamGreaterThanOrEqualTo(String value) {
            addCriterion("DOCNAM >=", value, "docnam");
            return (Criteria) this;
        }

        public Criteria andDocnamLessThan(String value) {
            addCriterion("DOCNAM <", value, "docnam");
            return (Criteria) this;
        }

        public Criteria andDocnamLessThanOrEqualTo(String value) {
            addCriterion("DOCNAM <=", value, "docnam");
            return (Criteria) this;
        }

        public Criteria andDocnamLike(String value) {
            addCriterion("DOCNAM like", value, "docnam");
            return (Criteria) this;
        }

        public Criteria andDocnamNotLike(String value) {
            addCriterion("DOCNAM not like", value, "docnam");
            return (Criteria) this;
        }

        public Criteria andDocnamIn(List<String> values) {
            addCriterion("DOCNAM in", values, "docnam");
            return (Criteria) this;
        }

        public Criteria andDocnamNotIn(List<String> values) {
            addCriterion("DOCNAM not in", values, "docnam");
            return (Criteria) this;
        }

        public Criteria andDocnamBetween(String value1, String value2) {
            addCriterion("DOCNAM between", value1, value2, "docnam");
            return (Criteria) this;
        }

        public Criteria andDocnamNotBetween(String value1, String value2) {
            addCriterion("DOCNAM not between", value1, value2, "docnam");
            return (Criteria) this;
        }

        public Criteria andFrtsphIsNull() {
            addCriterion("FRTSPH is null");
            return (Criteria) this;
        }

        public Criteria andFrtsphIsNotNull() {
            addCriterion("FRTSPH is not null");
            return (Criteria) this;
        }

        public Criteria andFrtsphEqualTo(BigDecimal value) {
            addCriterion("FRTSPH =", value, "frtsph");
            return (Criteria) this;
        }

        public Criteria andFrtsphNotEqualTo(BigDecimal value) {
            addCriterion("FRTSPH <>", value, "frtsph");
            return (Criteria) this;
        }

        public Criteria andFrtsphGreaterThan(BigDecimal value) {
            addCriterion("FRTSPH >", value, "frtsph");
            return (Criteria) this;
        }

        public Criteria andFrtsphGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FRTSPH >=", value, "frtsph");
            return (Criteria) this;
        }

        public Criteria andFrtsphLessThan(BigDecimal value) {
            addCriterion("FRTSPH <", value, "frtsph");
            return (Criteria) this;
        }

        public Criteria andFrtsphLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FRTSPH <=", value, "frtsph");
            return (Criteria) this;
        }

        public Criteria andFrtsphIn(List<BigDecimal> values) {
            addCriterion("FRTSPH in", values, "frtsph");
            return (Criteria) this;
        }

        public Criteria andFrtsphNotIn(List<BigDecimal> values) {
            addCriterion("FRTSPH not in", values, "frtsph");
            return (Criteria) this;
        }

        public Criteria andFrtsphBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FRTSPH between", value1, value2, "frtsph");
            return (Criteria) this;
        }

        public Criteria andFrtsphNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FRTSPH not between", value1, value2, "frtsph");
            return (Criteria) this;
        }

        public Criteria andFrtsplIsNull() {
            addCriterion("FRTSPL is null");
            return (Criteria) this;
        }

        public Criteria andFrtsplIsNotNull() {
            addCriterion("FRTSPL is not null");
            return (Criteria) this;
        }

        public Criteria andFrtsplEqualTo(BigDecimal value) {
            addCriterion("FRTSPL =", value, "frtspl");
            return (Criteria) this;
        }

        public Criteria andFrtsplNotEqualTo(BigDecimal value) {
            addCriterion("FRTSPL <>", value, "frtspl");
            return (Criteria) this;
        }

        public Criteria andFrtsplGreaterThan(BigDecimal value) {
            addCriterion("FRTSPL >", value, "frtspl");
            return (Criteria) this;
        }

        public Criteria andFrtsplGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FRTSPL >=", value, "frtspl");
            return (Criteria) this;
        }

        public Criteria andFrtsplLessThan(BigDecimal value) {
            addCriterion("FRTSPL <", value, "frtspl");
            return (Criteria) this;
        }

        public Criteria andFrtsplLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FRTSPL <=", value, "frtspl");
            return (Criteria) this;
        }

        public Criteria andFrtsplIn(List<BigDecimal> values) {
            addCriterion("FRTSPL in", values, "frtspl");
            return (Criteria) this;
        }

        public Criteria andFrtsplNotIn(List<BigDecimal> values) {
            addCriterion("FRTSPL not in", values, "frtspl");
            return (Criteria) this;
        }

        public Criteria andFrtsplBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FRTSPL between", value1, value2, "frtspl");
            return (Criteria) this;
        }

        public Criteria andFrtsplNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FRTSPL not between", value1, value2, "frtspl");
            return (Criteria) this;
        }

        public Criteria andSprflgIsNull() {
            addCriterion("SPRFLG is null");
            return (Criteria) this;
        }

        public Criteria andSprflgIsNotNull() {
            addCriterion("SPRFLG is not null");
            return (Criteria) this;
        }

        public Criteria andSprflgEqualTo(String value) {
            addCriterion("SPRFLG =", value, "sprflg");
            return (Criteria) this;
        }

        public Criteria andSprflgNotEqualTo(String value) {
            addCriterion("SPRFLG <>", value, "sprflg");
            return (Criteria) this;
        }

        public Criteria andSprflgGreaterThan(String value) {
            addCriterion("SPRFLG >", value, "sprflg");
            return (Criteria) this;
        }

        public Criteria andSprflgGreaterThanOrEqualTo(String value) {
            addCriterion("SPRFLG >=", value, "sprflg");
            return (Criteria) this;
        }

        public Criteria andSprflgLessThan(String value) {
            addCriterion("SPRFLG <", value, "sprflg");
            return (Criteria) this;
        }

        public Criteria andSprflgLessThanOrEqualTo(String value) {
            addCriterion("SPRFLG <=", value, "sprflg");
            return (Criteria) this;
        }

        public Criteria andSprflgLike(String value) {
            addCriterion("SPRFLG like", value, "sprflg");
            return (Criteria) this;
        }

        public Criteria andSprflgNotLike(String value) {
            addCriterion("SPRFLG not like", value, "sprflg");
            return (Criteria) this;
        }

        public Criteria andSprflgIn(List<String> values) {
            addCriterion("SPRFLG in", values, "sprflg");
            return (Criteria) this;
        }

        public Criteria andSprflgNotIn(List<String> values) {
            addCriterion("SPRFLG not in", values, "sprflg");
            return (Criteria) this;
        }

        public Criteria andSprflgBetween(String value1, String value2) {
            addCriterion("SPRFLG between", value1, value2, "sprflg");
            return (Criteria) this;
        }

        public Criteria andSprflgNotBetween(String value1, String value2) {
            addCriterion("SPRFLG not between", value1, value2, "sprflg");
            return (Criteria) this;
        }

        public Criteria andMalfeeIsNull() {
            addCriterion("MALFEE is null");
            return (Criteria) this;
        }

        public Criteria andMalfeeIsNotNull() {
            addCriterion("MALFEE is not null");
            return (Criteria) this;
        }

        public Criteria andMalfeeEqualTo(BigDecimal value) {
            addCriterion("MALFEE =", value, "malfee");
            return (Criteria) this;
        }

        public Criteria andMalfeeNotEqualTo(BigDecimal value) {
            addCriterion("MALFEE <>", value, "malfee");
            return (Criteria) this;
        }

        public Criteria andMalfeeGreaterThan(BigDecimal value) {
            addCriterion("MALFEE >", value, "malfee");
            return (Criteria) this;
        }

        public Criteria andMalfeeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("MALFEE >=", value, "malfee");
            return (Criteria) this;
        }

        public Criteria andMalfeeLessThan(BigDecimal value) {
            addCriterion("MALFEE <", value, "malfee");
            return (Criteria) this;
        }

        public Criteria andMalfeeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("MALFEE <=", value, "malfee");
            return (Criteria) this;
        }

        public Criteria andMalfeeIn(List<BigDecimal> values) {
            addCriterion("MALFEE in", values, "malfee");
            return (Criteria) this;
        }

        public Criteria andMalfeeNotIn(List<BigDecimal> values) {
            addCriterion("MALFEE not in", values, "malfee");
            return (Criteria) this;
        }

        public Criteria andMalfeeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MALFEE between", value1, value2, "malfee");
            return (Criteria) this;
        }

        public Criteria andMalfeeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MALFEE not between", value1, value2, "malfee");
            return (Criteria) this;
        }

        public Criteria andComfeeIsNull() {
            addCriterion("COMFEE is null");
            return (Criteria) this;
        }

        public Criteria andComfeeIsNotNull() {
            addCriterion("COMFEE is not null");
            return (Criteria) this;
        }

        public Criteria andComfeeEqualTo(BigDecimal value) {
            addCriterion("COMFEE =", value, "comfee");
            return (Criteria) this;
        }

        public Criteria andComfeeNotEqualTo(BigDecimal value) {
            addCriterion("COMFEE <>", value, "comfee");
            return (Criteria) this;
        }

        public Criteria andComfeeGreaterThan(BigDecimal value) {
            addCriterion("COMFEE >", value, "comfee");
            return (Criteria) this;
        }

        public Criteria andComfeeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("COMFEE >=", value, "comfee");
            return (Criteria) this;
        }

        public Criteria andComfeeLessThan(BigDecimal value) {
            addCriterion("COMFEE <", value, "comfee");
            return (Criteria) this;
        }

        public Criteria andComfeeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("COMFEE <=", value, "comfee");
            return (Criteria) this;
        }

        public Criteria andComfeeIn(List<BigDecimal> values) {
            addCriterion("COMFEE in", values, "comfee");
            return (Criteria) this;
        }

        public Criteria andComfeeNotIn(List<BigDecimal> values) {
            addCriterion("COMFEE not in", values, "comfee");
            return (Criteria) this;
        }

        public Criteria andComfeeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("COMFEE between", value1, value2, "comfee");
            return (Criteria) this;
        }

        public Criteria andComfeeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("COMFEE not between", value1, value2, "comfee");
            return (Criteria) this;
        }

        public Criteria andFeeratIsNull() {
            addCriterion("FEERAT is null");
            return (Criteria) this;
        }

        public Criteria andFeeratIsNotNull() {
            addCriterion("FEERAT is not null");
            return (Criteria) this;
        }

        public Criteria andFeeratEqualTo(BigDecimal value) {
            addCriterion("FEERAT =", value, "feerat");
            return (Criteria) this;
        }

        public Criteria andFeeratNotEqualTo(BigDecimal value) {
            addCriterion("FEERAT <>", value, "feerat");
            return (Criteria) this;
        }

        public Criteria andFeeratGreaterThan(BigDecimal value) {
            addCriterion("FEERAT >", value, "feerat");
            return (Criteria) this;
        }

        public Criteria andFeeratGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FEERAT >=", value, "feerat");
            return (Criteria) this;
        }

        public Criteria andFeeratLessThan(BigDecimal value) {
            addCriterion("FEERAT <", value, "feerat");
            return (Criteria) this;
        }

        public Criteria andFeeratLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FEERAT <=", value, "feerat");
            return (Criteria) this;
        }

        public Criteria andFeeratIn(List<BigDecimal> values) {
            addCriterion("FEERAT in", values, "feerat");
            return (Criteria) this;
        }

        public Criteria andFeeratNotIn(List<BigDecimal> values) {
            addCriterion("FEERAT not in", values, "feerat");
            return (Criteria) this;
        }

        public Criteria andFeeratBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FEERAT between", value1, value2, "feerat");
            return (Criteria) this;
        }

        public Criteria andFeeratNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FEERAT not between", value1, value2, "feerat");
            return (Criteria) this;
        }

        public Criteria andHiglimIsNull() {
            addCriterion("HIGLIM is null");
            return (Criteria) this;
        }

        public Criteria andHiglimIsNotNull() {
            addCriterion("HIGLIM is not null");
            return (Criteria) this;
        }

        public Criteria andHiglimEqualTo(BigDecimal value) {
            addCriterion("HIGLIM =", value, "higlim");
            return (Criteria) this;
        }

        public Criteria andHiglimNotEqualTo(BigDecimal value) {
            addCriterion("HIGLIM <>", value, "higlim");
            return (Criteria) this;
        }

        public Criteria andHiglimGreaterThan(BigDecimal value) {
            addCriterion("HIGLIM >", value, "higlim");
            return (Criteria) this;
        }

        public Criteria andHiglimGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("HIGLIM >=", value, "higlim");
            return (Criteria) this;
        }

        public Criteria andHiglimLessThan(BigDecimal value) {
            addCriterion("HIGLIM <", value, "higlim");
            return (Criteria) this;
        }

        public Criteria andHiglimLessThanOrEqualTo(BigDecimal value) {
            addCriterion("HIGLIM <=", value, "higlim");
            return (Criteria) this;
        }

        public Criteria andHiglimIn(List<BigDecimal> values) {
            addCriterion("HIGLIM in", values, "higlim");
            return (Criteria) this;
        }

        public Criteria andHiglimNotIn(List<BigDecimal> values) {
            addCriterion("HIGLIM not in", values, "higlim");
            return (Criteria) this;
        }

        public Criteria andHiglimBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("HIGLIM between", value1, value2, "higlim");
            return (Criteria) this;
        }

        public Criteria andHiglimNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("HIGLIM not between", value1, value2, "higlim");
            return (Criteria) this;
        }

        public Criteria andLowlimIsNull() {
            addCriterion("LOWLIM is null");
            return (Criteria) this;
        }

        public Criteria andLowlimIsNotNull() {
            addCriterion("LOWLIM is not null");
            return (Criteria) this;
        }

        public Criteria andLowlimEqualTo(BigDecimal value) {
            addCriterion("LOWLIM =", value, "lowlim");
            return (Criteria) this;
        }

        public Criteria andLowlimNotEqualTo(BigDecimal value) {
            addCriterion("LOWLIM <>", value, "lowlim");
            return (Criteria) this;
        }

        public Criteria andLowlimGreaterThan(BigDecimal value) {
            addCriterion("LOWLIM >", value, "lowlim");
            return (Criteria) this;
        }

        public Criteria andLowlimGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("LOWLIM >=", value, "lowlim");
            return (Criteria) this;
        }

        public Criteria andLowlimLessThan(BigDecimal value) {
            addCriterion("LOWLIM <", value, "lowlim");
            return (Criteria) this;
        }

        public Criteria andLowlimLessThanOrEqualTo(BigDecimal value) {
            addCriterion("LOWLIM <=", value, "lowlim");
            return (Criteria) this;
        }

        public Criteria andLowlimIn(List<BigDecimal> values) {
            addCriterion("LOWLIM in", values, "lowlim");
            return (Criteria) this;
        }

        public Criteria andLowlimNotIn(List<BigDecimal> values) {
            addCriterion("LOWLIM not in", values, "lowlim");
            return (Criteria) this;
        }

        public Criteria andLowlimBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LOWLIM between", value1, value2, "lowlim");
            return (Criteria) this;
        }

        public Criteria andLowlimNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LOWLIM not between", value1, value2, "lowlim");
            return (Criteria) this;
        }

        public Criteria andFeecycIsNull() {
            addCriterion("FEECYC is null");
            return (Criteria) this;
        }

        public Criteria andFeecycIsNotNull() {
            addCriterion("FEECYC is not null");
            return (Criteria) this;
        }

        public Criteria andFeecycEqualTo(String value) {
            addCriterion("FEECYC =", value, "feecyc");
            return (Criteria) this;
        }

        public Criteria andFeecycNotEqualTo(String value) {
            addCriterion("FEECYC <>", value, "feecyc");
            return (Criteria) this;
        }

        public Criteria andFeecycGreaterThan(String value) {
            addCriterion("FEECYC >", value, "feecyc");
            return (Criteria) this;
        }

        public Criteria andFeecycGreaterThanOrEqualTo(String value) {
            addCriterion("FEECYC >=", value, "feecyc");
            return (Criteria) this;
        }

        public Criteria andFeecycLessThan(String value) {
            addCriterion("FEECYC <", value, "feecyc");
            return (Criteria) this;
        }

        public Criteria andFeecycLessThanOrEqualTo(String value) {
            addCriterion("FEECYC <=", value, "feecyc");
            return (Criteria) this;
        }

        public Criteria andFeecycLike(String value) {
            addCriterion("FEECYC like", value, "feecyc");
            return (Criteria) this;
        }

        public Criteria andFeecycNotLike(String value) {
            addCriterion("FEECYC not like", value, "feecyc");
            return (Criteria) this;
        }

        public Criteria andFeecycIn(List<String> values) {
            addCriterion("FEECYC in", values, "feecyc");
            return (Criteria) this;
        }

        public Criteria andFeecycNotIn(List<String> values) {
            addCriterion("FEECYC not in", values, "feecyc");
            return (Criteria) this;
        }

        public Criteria andFeecycBetween(String value1, String value2) {
            addCriterion("FEECYC between", value1, value2, "feecyc");
            return (Criteria) this;
        }

        public Criteria andFeecycNotBetween(String value1, String value2) {
            addCriterion("FEECYC not between", value1, value2, "feecyc");
            return (Criteria) this;
        }

        public Criteria andFeesdeIsNull() {
            addCriterion("FEESDE is null");
            return (Criteria) this;
        }

        public Criteria andFeesdeIsNotNull() {
            addCriterion("FEESDE is not null");
            return (Criteria) this;
        }

        public Criteria andFeesdeEqualTo(String value) {
            addCriterion("FEESDE =", value, "feesde");
            return (Criteria) this;
        }

        public Criteria andFeesdeNotEqualTo(String value) {
            addCriterion("FEESDE <>", value, "feesde");
            return (Criteria) this;
        }

        public Criteria andFeesdeGreaterThan(String value) {
            addCriterion("FEESDE >", value, "feesde");
            return (Criteria) this;
        }

        public Criteria andFeesdeGreaterThanOrEqualTo(String value) {
            addCriterion("FEESDE >=", value, "feesde");
            return (Criteria) this;
        }

        public Criteria andFeesdeLessThan(String value) {
            addCriterion("FEESDE <", value, "feesde");
            return (Criteria) this;
        }

        public Criteria andFeesdeLessThanOrEqualTo(String value) {
            addCriterion("FEESDE <=", value, "feesde");
            return (Criteria) this;
        }

        public Criteria andFeesdeLike(String value) {
            addCriterion("FEESDE like", value, "feesde");
            return (Criteria) this;
        }

        public Criteria andFeesdeNotLike(String value) {
            addCriterion("FEESDE not like", value, "feesde");
            return (Criteria) this;
        }

        public Criteria andFeesdeIn(List<String> values) {
            addCriterion("FEESDE in", values, "feesde");
            return (Criteria) this;
        }

        public Criteria andFeesdeNotIn(List<String> values) {
            addCriterion("FEESDE not in", values, "feesde");
            return (Criteria) this;
        }

        public Criteria andFeesdeBetween(String value1, String value2) {
            addCriterion("FEESDE between", value1, value2, "feesde");
            return (Criteria) this;
        }

        public Criteria andFeesdeNotBetween(String value1, String value2) {
            addCriterion("FEESDE not between", value1, value2, "feesde");
            return (Criteria) this;
        }

        public Criteria andFeeapcIsNull() {
            addCriterion("FEEAPC is null");
            return (Criteria) this;
        }

        public Criteria andFeeapcIsNotNull() {
            addCriterion("FEEAPC is not null");
            return (Criteria) this;
        }

        public Criteria andFeeapcEqualTo(String value) {
            addCriterion("FEEAPC =", value, "feeapc");
            return (Criteria) this;
        }

        public Criteria andFeeapcNotEqualTo(String value) {
            addCriterion("FEEAPC <>", value, "feeapc");
            return (Criteria) this;
        }

        public Criteria andFeeapcGreaterThan(String value) {
            addCriterion("FEEAPC >", value, "feeapc");
            return (Criteria) this;
        }

        public Criteria andFeeapcGreaterThanOrEqualTo(String value) {
            addCriterion("FEEAPC >=", value, "feeapc");
            return (Criteria) this;
        }

        public Criteria andFeeapcLessThan(String value) {
            addCriterion("FEEAPC <", value, "feeapc");
            return (Criteria) this;
        }

        public Criteria andFeeapcLessThanOrEqualTo(String value) {
            addCriterion("FEEAPC <=", value, "feeapc");
            return (Criteria) this;
        }

        public Criteria andFeeapcLike(String value) {
            addCriterion("FEEAPC like", value, "feeapc");
            return (Criteria) this;
        }

        public Criteria andFeeapcNotLike(String value) {
            addCriterion("FEEAPC not like", value, "feeapc");
            return (Criteria) this;
        }

        public Criteria andFeeapcIn(List<String> values) {
            addCriterion("FEEAPC in", values, "feeapc");
            return (Criteria) this;
        }

        public Criteria andFeeapcNotIn(List<String> values) {
            addCriterion("FEEAPC not in", values, "feeapc");
            return (Criteria) this;
        }

        public Criteria andFeeapcBetween(String value1, String value2) {
            addCriterion("FEEAPC between", value1, value2, "feeapc");
            return (Criteria) this;
        }

        public Criteria andFeeapcNotBetween(String value1, String value2) {
            addCriterion("FEEAPC not between", value1, value2, "feeapc");
            return (Criteria) this;
        }

        public Criteria andCretlrIsNull() {
            addCriterion("CRETLR is null");
            return (Criteria) this;
        }

        public Criteria andCretlrIsNotNull() {
            addCriterion("CRETLR is not null");
            return (Criteria) this;
        }

        public Criteria andCretlrEqualTo(String value) {
            addCriterion("CRETLR =", value, "cretlr");
            return (Criteria) this;
        }

        public Criteria andCretlrNotEqualTo(String value) {
            addCriterion("CRETLR <>", value, "cretlr");
            return (Criteria) this;
        }

        public Criteria andCretlrGreaterThan(String value) {
            addCriterion("CRETLR >", value, "cretlr");
            return (Criteria) this;
        }

        public Criteria andCretlrGreaterThanOrEqualTo(String value) {
            addCriterion("CRETLR >=", value, "cretlr");
            return (Criteria) this;
        }

        public Criteria andCretlrLessThan(String value) {
            addCriterion("CRETLR <", value, "cretlr");
            return (Criteria) this;
        }

        public Criteria andCretlrLessThanOrEqualTo(String value) {
            addCriterion("CRETLR <=", value, "cretlr");
            return (Criteria) this;
        }

        public Criteria andCretlrLike(String value) {
            addCriterion("CRETLR like", value, "cretlr");
            return (Criteria) this;
        }

        public Criteria andCretlrNotLike(String value) {
            addCriterion("CRETLR not like", value, "cretlr");
            return (Criteria) this;
        }

        public Criteria andCretlrIn(List<String> values) {
            addCriterion("CRETLR in", values, "cretlr");
            return (Criteria) this;
        }

        public Criteria andCretlrNotIn(List<String> values) {
            addCriterion("CRETLR not in", values, "cretlr");
            return (Criteria) this;
        }

        public Criteria andCretlrBetween(String value1, String value2) {
            addCriterion("CRETLR between", value1, value2, "cretlr");
            return (Criteria) this;
        }

        public Criteria andCretlrNotBetween(String value1, String value2) {
            addCriterion("CRETLR not between", value1, value2, "cretlr");
            return (Criteria) this;
        }

        public Criteria andCredatIsNull() {
            addCriterion("CREDAT is null");
            return (Criteria) this;
        }

        public Criteria andCredatIsNotNull() {
            addCriterion("CREDAT is not null");
            return (Criteria) this;
        }

        public Criteria andCredatEqualTo(Date value) {
            addCriterion("CREDAT =", value, "credat");
            return (Criteria) this;
        }

        public Criteria andCredatNotEqualTo(Date value) {
            addCriterion("CREDAT <>", value, "credat");
            return (Criteria) this;
        }

        public Criteria andCredatGreaterThan(Date value) {
            addCriterion("CREDAT >", value, "credat");
            return (Criteria) this;
        }

        public Criteria andCredatGreaterThanOrEqualTo(Date value) {
            addCriterion("CREDAT >=", value, "credat");
            return (Criteria) this;
        }

        public Criteria andCredatLessThan(Date value) {
            addCriterion("CREDAT <", value, "credat");
            return (Criteria) this;
        }

        public Criteria andCredatLessThanOrEqualTo(Date value) {
            addCriterion("CREDAT <=", value, "credat");
            return (Criteria) this;
        }

        public Criteria andCredatIn(List<Date> values) {
            addCriterion("CREDAT in", values, "credat");
            return (Criteria) this;
        }

        public Criteria andCredatNotIn(List<Date> values) {
            addCriterion("CREDAT not in", values, "credat");
            return (Criteria) this;
        }

        public Criteria andCredatBetween(Date value1, Date value2) {
            addCriterion("CREDAT between", value1, value2, "credat");
            return (Criteria) this;
        }

        public Criteria andCredatNotBetween(Date value1, Date value2) {
            addCriterion("CREDAT not between", value1, value2, "credat");
            return (Criteria) this;
        }

        public Criteria andRecstsIsNull() {
            addCriterion("RECSTS is null");
            return (Criteria) this;
        }

        public Criteria andRecstsIsNotNull() {
            addCriterion("RECSTS is not null");
            return (Criteria) this;
        }

        public Criteria andRecstsEqualTo(String value) {
            addCriterion("RECSTS =", value, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsNotEqualTo(String value) {
            addCriterion("RECSTS <>", value, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsGreaterThan(String value) {
            addCriterion("RECSTS >", value, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsGreaterThanOrEqualTo(String value) {
            addCriterion("RECSTS >=", value, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsLessThan(String value) {
            addCriterion("RECSTS <", value, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsLessThanOrEqualTo(String value) {
            addCriterion("RECSTS <=", value, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsLike(String value) {
            addCriterion("RECSTS like", value, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsNotLike(String value) {
            addCriterion("RECSTS not like", value, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsIn(List<String> values) {
            addCriterion("RECSTS in", values, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsNotIn(List<String> values) {
            addCriterion("RECSTS not in", values, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsBetween(String value1, String value2) {
            addCriterion("RECSTS between", value1, value2, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsNotBetween(String value1, String value2) {
            addCriterion("RECSTS not between", value1, value2, "recsts");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ACTFRT
     *
     * @mbggenerated do_not_delete_during_merge Sun Nov 21 21:36:06 CST 2010
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ACTFRT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}