package cbs.repository.code.model;

import java.util.Date;

public class Acthol {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTHOL.CURCDE
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String curcde;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTHOL.HOLDAT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String holdat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTHOL.PREDAT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private Date predat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTHOL.NXTDAT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private Date nxtdat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTHOL.PREDDS
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private Short predds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTHOL.NXTDDS
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private Short nxtdds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTHOL.AMDTLR
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String amdtlr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTHOL.UPDDAT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private Date upddat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTHOL.RECSTS
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String recsts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTHOL.CURCDE
     *
     * @return the value of ACTHOL.CURCDE
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getCurcde() {
        return curcde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTHOL.CURCDE
     *
     * @param curcde the value for ACTHOL.CURCDE
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setCurcde(String curcde) {
        this.curcde = curcde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTHOL.HOLDAT
     *
     * @return the value of ACTHOL.HOLDAT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getHoldat() {
        return holdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTHOL.HOLDAT
     *
     * @param holdat the value for ACTHOL.HOLDAT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setHoldat(String holdat) {
        this.holdat = holdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTHOL.PREDAT
     *
     * @return the value of ACTHOL.PREDAT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public Date getPredat() {
        return predat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTHOL.PREDAT
     *
     * @param predat the value for ACTHOL.PREDAT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setPredat(Date predat) {
        this.predat = predat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTHOL.NXTDAT
     *
     * @return the value of ACTHOL.NXTDAT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public Date getNxtdat() {
        return nxtdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTHOL.NXTDAT
     *
     * @param nxtdat the value for ACTHOL.NXTDAT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setNxtdat(Date nxtdat) {
        this.nxtdat = nxtdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTHOL.PREDDS
     *
     * @return the value of ACTHOL.PREDDS
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public Short getPredds() {
        return predds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTHOL.PREDDS
     *
     * @param predds the value for ACTHOL.PREDDS
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setPredds(Short predds) {
        this.predds = predds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTHOL.NXTDDS
     *
     * @return the value of ACTHOL.NXTDDS
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public Short getNxtdds() {
        return nxtdds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTHOL.NXTDDS
     *
     * @param nxtdds the value for ACTHOL.NXTDDS
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setNxtdds(Short nxtdds) {
        this.nxtdds = nxtdds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTHOL.AMDTLR
     *
     * @return the value of ACTHOL.AMDTLR
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getAmdtlr() {
        return amdtlr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTHOL.AMDTLR
     *
     * @param amdtlr the value for ACTHOL.AMDTLR
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setAmdtlr(String amdtlr) {
        this.amdtlr = amdtlr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTHOL.UPDDAT
     *
     * @return the value of ACTHOL.UPDDAT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public Date getUpddat() {
        return upddat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTHOL.UPDDAT
     *
     * @param upddat the value for ACTHOL.UPDDAT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setUpddat(Date upddat) {
        this.upddat = upddat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTHOL.RECSTS
     *
     * @return the value of ACTHOL.RECSTS
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getRecsts() {
        return recsts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTHOL.RECSTS
     *
     * @param recsts the value for ACTHOL.RECSTS
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setRecsts(String recsts) {
        this.recsts = recsts;
    }
}