package cbs.repository.code.model;

import cbs.common.IbatisFactory;
import cbs.repository.code.dao.ActirtMapper;
import org.apache.ibatis.session.SqlSession;
import org.apache.ibatis.session.SqlSessionFactory;

import javax.faces.model.SelectItem;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class Actirt {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTIRT.CURCDE
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String curcde;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTIRT.IRTKD1
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String irtkd1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTIRT.IRTKD2
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String irtkd2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTIRT.EFFDAT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private Date effdat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTIRT.IRTNAM
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String irtnam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTIRT.CURFLG
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String curflg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTIRT.MODFLG
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String modflg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTIRT.IRTVAL
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private BigDecimal irtval;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTIRT.IRTSPH
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private BigDecimal irtsph;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTIRT.IRTSPL
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private BigDecimal irtspl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTIRT.SPRFLG
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String sprflg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTIRT.CDFLAG
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String cdflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTIRT.IRTTRM
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private Short irttrm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTIRT.TRMUNT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String trmunt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTIRT.CRETLR
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String cretlr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTIRT.CREDAT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private Date credat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTIRT.RECSTS
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String recsts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTIRT.CURCDE
     *
     * @return the value of ACTIRT.CURCDE
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getCurcde() {
        return curcde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTIRT.CURCDE
     *
     * @param curcde the value for ACTIRT.CURCDE
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setCurcde(String curcde) {
        this.curcde = curcde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTIRT.IRTKD1
     *
     * @return the value of ACTIRT.IRTKD1
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getIrtkd1() {
        return irtkd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTIRT.IRTKD1
     *
     * @param irtkd1 the value for ACTIRT.IRTKD1
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setIrtkd1(String irtkd1) {
        this.irtkd1 = irtkd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTIRT.IRTKD2
     *
     * @return the value of ACTIRT.IRTKD2
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getIrtkd2() {
        return irtkd2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTIRT.IRTKD2
     *
     * @param irtkd2 the value for ACTIRT.IRTKD2
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setIrtkd2(String irtkd2) {
        this.irtkd2 = irtkd2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTIRT.EFFDAT
     *
     * @return the value of ACTIRT.EFFDAT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public Date getEffdat() {
        return effdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTIRT.EFFDAT
     *
     * @param effdat the value for ACTIRT.EFFDAT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setEffdat(Date effdat) {
        this.effdat = effdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTIRT.IRTNAM
     *
     * @return the value of ACTIRT.IRTNAM
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getIrtnam() {
        return irtnam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTIRT.IRTNAM
     *
     * @param irtnam the value for ACTIRT.IRTNAM
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setIrtnam(String irtnam) {
        this.irtnam = irtnam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTIRT.CURFLG
     *
     * @return the value of ACTIRT.CURFLG
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getCurflg() {
        return curflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTIRT.CURFLG
     *
     * @param curflg the value for ACTIRT.CURFLG
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setCurflg(String curflg) {
        this.curflg = curflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTIRT.MODFLG
     *
     * @return the value of ACTIRT.MODFLG
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getModflg() {
        return modflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTIRT.MODFLG
     *
     * @param modflg the value for ACTIRT.MODFLG
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setModflg(String modflg) {
        this.modflg = modflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTIRT.IRTVAL
     *
     * @return the value of ACTIRT.IRTVAL
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public BigDecimal getIrtval() {
        return irtval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTIRT.IRTVAL
     *
     * @param irtval the value for ACTIRT.IRTVAL
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setIrtval(BigDecimal irtval) {
        this.irtval = irtval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTIRT.IRTSPH
     *
     * @return the value of ACTIRT.IRTSPH
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public BigDecimal getIrtsph() {
        return irtsph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTIRT.IRTSPH
     *
     * @param irtsph the value for ACTIRT.IRTSPH
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setIrtsph(BigDecimal irtsph) {
        this.irtsph = irtsph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTIRT.IRTSPL
     *
     * @return the value of ACTIRT.IRTSPL
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public BigDecimal getIrtspl() {
        return irtspl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTIRT.IRTSPL
     *
     * @param irtspl the value for ACTIRT.IRTSPL
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setIrtspl(BigDecimal irtspl) {
        this.irtspl = irtspl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTIRT.SPRFLG
     *
     * @return the value of ACTIRT.SPRFLG
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getSprflg() {
        return sprflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTIRT.SPRFLG
     *
     * @param sprflg the value for ACTIRT.SPRFLG
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setSprflg(String sprflg) {
        this.sprflg = sprflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTIRT.CDFLAG
     *
     * @return the value of ACTIRT.CDFLAG
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getCdflag() {
        return cdflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTIRT.CDFLAG
     *
     * @param cdflag the value for ACTIRT.CDFLAG
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setCdflag(String cdflag) {
        this.cdflag = cdflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTIRT.IRTTRM
     *
     * @return the value of ACTIRT.IRTTRM
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public Short getIrttrm() {
        return irttrm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTIRT.IRTTRM
     *
     * @param irttrm the value for ACTIRT.IRTTRM
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setIrttrm(Short irttrm) {
        this.irttrm = irttrm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTIRT.TRMUNT
     *
     * @return the value of ACTIRT.TRMUNT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getTrmunt() {
        return trmunt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTIRT.TRMUNT
     *
     * @param trmunt the value for ACTIRT.TRMUNT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setTrmunt(String trmunt) {
        this.trmunt = trmunt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTIRT.CRETLR
     *
     * @return the value of ACTIRT.CRETLR
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getCretlr() {
        return cretlr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTIRT.CRETLR
     *
     * @param cretlr the value for ACTIRT.CRETLR
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setCretlr(String cretlr) {
        this.cretlr = cretlr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTIRT.CREDAT
     *
     * @return the value of ACTIRT.CREDAT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public Date getCredat() {
        return credat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTIRT.CREDAT
     *
     * @param credat the value for ACTIRT.CREDAT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setCredat(Date credat) {
        this.credat = credat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTIRT.RECSTS
     *
     * @return the value of ACTIRT.RECSTS
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getRecsts() {
        return recsts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTIRT.RECSTS
     *
     * @param recsts the value for ACTIRT.RECSTS
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setRecsts(String recsts) {
        this.recsts = recsts;
    }

    /**
     * reateBy: haiyuhuang
     * date:    2011-01-11
     * remark:  根据币别获取利率码list*/
    public ArrayList<SelectItem> getData(String curcde) throws Exception {
        ArrayList aList=new ArrayList();
        SelectItem siSpace = new SelectItem("","");
        aList.add(siSpace);
        SqlSessionFactory sessionFactory;
        sessionFactory = IbatisFactory.ORACLE.getInstance();
        SqlSession session = sessionFactory.openSession();
        try {
            ActirtMapper irtmap = session.getMapper(ActirtMapper.class);
            ActirtExample irtExam = new ActirtExample();
            irtExam.createCriteria().andCurcdeEqualTo(curcde).andCurflgEqualTo("1");
            List<Actirt> irtLst = irtmap.selectByExample(irtExam);
            Iterator it = irtLst.iterator();
            while (it.hasNext()) {
                Actirt irt = (Actirt)it.next();
                String val = "";
                String lbl = "";
                val = irt.getIrtkd1()+irt.getIrtkd2();
                lbl = val + " " + irt.getIrtnam();
                SelectItem si = new SelectItem(val,lbl);
                aList.add(si);
            }
        } catch (Exception ex) {
            throw ex;
        }
        finally {
            session.close();
        }
        return aList;
    }
}