package cbs.repository.code.model;

public class Actpdn {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTPDN.ORGIDT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String orgidt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTPDN.PRDCDE
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String prdcde;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTPDN.PDNSEQ
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private Integer pdnseq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTPDN.PDNYER
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String pdnyer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTPDN.RECSTS
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    private String recsts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTPDN.ORGIDT
     *
     * @return the value of ACTPDN.ORGIDT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getOrgidt() {
        return orgidt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTPDN.ORGIDT
     *
     * @param orgidt the value for ACTPDN.ORGIDT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setOrgidt(String orgidt) {
        this.orgidt = orgidt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTPDN.PRDCDE
     *
     * @return the value of ACTPDN.PRDCDE
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getPrdcde() {
        return prdcde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTPDN.PRDCDE
     *
     * @param prdcde the value for ACTPDN.PRDCDE
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setPrdcde(String prdcde) {
        this.prdcde = prdcde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTPDN.PDNSEQ
     *
     * @return the value of ACTPDN.PDNSEQ
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public Integer getPdnseq() {
        return pdnseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTPDN.PDNSEQ
     *
     * @param pdnseq the value for ACTPDN.PDNSEQ
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setPdnseq(Integer pdnseq) {
        this.pdnseq = pdnseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTPDN.PDNYER
     *
     * @return the value of ACTPDN.PDNYER
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getPdnyer() {
        return pdnyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTPDN.PDNYER
     *
     * @param pdnyer the value for ACTPDN.PDNYER
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setPdnyer(String pdnyer) {
        this.pdnyer = pdnyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTPDN.RECSTS
     *
     * @return the value of ACTPDN.RECSTS
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public String getRecsts() {
        return recsts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTPDN.RECSTS
     *
     * @param recsts the value for ACTPDN.RECSTS
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    public void setRecsts(String recsts) {
        this.recsts = recsts;
    }
}