package cbs.repository.customer.dao;

import cbs.repository.customer.model.Actcus;
import cbs.repository.customer.model.ActcusExample;
import cbs.repository.customer.model.ActcusKey;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ActcusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTCUS
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int countByExample(ActcusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTCUS
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int deleteByExample(ActcusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTCUS
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int deleteByPrimaryKey(ActcusKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTCUS
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int insert(Actcus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTCUS
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int insertSelective(Actcus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTCUS
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    List<Actcus> selectByExample(ActcusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTCUS
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    Actcus selectByPrimaryKey(ActcusKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTCUS
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int updateByExampleSelective(@Param("record") Actcus record, @Param("example") ActcusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTCUS
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int updateByExample(@Param("record") Actcus record, @Param("example") ActcusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTCUS
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int updateByPrimaryKeySelective(Actcus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTCUS
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int updateByPrimaryKey(Actcus record);

    @Select("select to_number(max(cusidt)) as maxCusidt from actcus where cusidt not like '9%'")
    int selectMaxCusidt();

    @Select("select to_number(min(cusidt)) as minCusidt from actcus")
    int selectMinCusidt();

    @Select("select count(cusidt) as idcnt from actcus where to_number(cusidt) = to_number(#{id})")
    int selectCusCountById(@Param("id")String id);

    @Update("update actcus set recsts = #{recsts} where cusidt =#{cusidt}")
    int deleteCusByCusidt(@Param("recsts")String recsts,@Param("cusidt")String cusidt);

    @Select("select CUSIDT, SYSIDT, CUSNAM, SHTNAM, ENGNAM, CUSIDX, RSDCTR, OPRCTR, CORADD, ZIPCDE, TELNUM, " +
            "    TELEXN, TSTRNK, PASTYP, PASSNO, CRDLIM, RSKGRP, RELCUS, OPNDAT, CUSPWD, CUSKID, ORGIDT," +
            "    DEPNUM, AMDTLR, UPDDAT, RECSTS From ACTCUS "+
            " where recsts = ' ' and CUSIDT = #{cusidt} order by cusidt")
    List<Actcus> selectCusByCusidt(@Param("cusidt")String cusidt);

    @Select("select CUSIDT, SYSIDT, CUSNAM, SHTNAM, ENGNAM, CUSIDX, RSDCTR, OPRCTR, CORADD, ZIPCDE, TELNUM, " +
            "    TELEXN, TSTRNK, PASTYP, PASSNO, CRDLIM, RSKGRP, RELCUS, OPNDAT, CUSPWD, CUSKID, ORGIDT," +
            "    DEPNUM, AMDTLR, UPDDAT, RECSTS From ACTCUS "+
            " where recsts = ' ' and  CUSNAM like '%'||#{cusnam}||'%' order by cusidt")
    List<Actcus> selectCusByCusnam(@Param("cusnam")String cusnam);

    @Select("select CUSIDT, SYSIDT, CUSNAM, SHTNAM, ENGNAM, CUSIDX, RSDCTR, OPRCTR, CORADD, ZIPCDE, TELNUM, " +
            "    TELEXN, TSTRNK, PASTYP, PASSNO, CRDLIM, RSKGRP, RELCUS, OPNDAT, CUSPWD, CUSKID, ORGIDT," +
            "    DEPNUM, AMDTLR, UPDDAT, RECSTS From ACTCUS "+
            " where recsts = ' ' and  CUSNAM like '%'||#{cusnam}||'%' and CUSIDT = #{cusidt} order by cusidt")
    List<Actcus> selectCusByIdNam(@Param("cusidt")String cusidt,@Param("cusnam")String cusnam);

     @Select("select CUSIDT, SYSIDT, CUSNAM, SHTNAM, ENGNAM, CUSIDX, RSDCTR, OPRCTR, CORADD, ZIPCDE, TELNUM, " +
            "    TELEXN, TSTRNK, PASTYP, PASSNO, CRDLIM, RSKGRP, RELCUS, OPNDAT, CUSPWD, CUSKID, ORGIDT," +
            "    DEPNUM, AMDTLR, UPDDAT, RECSTS From ACTCUS "+
            "  where recsts = ' ' order by cusidt")
    List<Actcus> selectCus();

}