package cbs.repository.customer.dao;

import cbs.repository.customer.model.Actper;
import cbs.repository.customer.model.ActperExample;
import cbs.repository.customer.model.ActperKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTPER
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int countByExample(ActperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTPER
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int deleteByExample(ActperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTPER
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int deleteByPrimaryKey(ActperKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTPER
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int insert(Actper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTPER
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int insertSelective(Actper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTPER
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    List<Actper> selectByExample(ActperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTPER
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    Actper selectByPrimaryKey(ActperKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTPER
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int updateByExampleSelective(@Param("record") Actper record, @Param("example") ActperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTPER
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int updateByExample(@Param("record") Actper record, @Param("example") ActperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTPER
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int updateByPrimaryKeySelective(Actper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTPER
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int updateByPrimaryKey(Actper record);
}