package cbs.repository.account.billinfo.dao;

import cbs.repository.account.billinfo.model.Actfgl;
import cbs.repository.account.billinfo.model.ActfglExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ActfglMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTFGL
     *
     * @mbggenerated Sun Mar 06 10:29:25 CST 2011
     */
    int countByExample(ActfglExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTFGL
     *
     * @mbggenerated Sun Mar 06 10:29:25 CST 2011
     */
    int deleteByExample(ActfglExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTFGL
     *
     * @mbggenerated Sun Mar 06 10:29:25 CST 2011
     */
    int insert(Actfgl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTFGL
     *
     * @mbggenerated Sun Mar 06 10:29:25 CST 2011
     */
    int insertSelective(Actfgl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTFGL
     *
     * @mbggenerated Sun Mar 06 10:29:25 CST 2011
     */
    List<Actfgl> selectByExample(ActfglExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTFGL
     *
     * @mbggenerated Sun Mar 06 10:29:25 CST 2011
     */
    int updateByExampleSelective(@Param("record") Actfgl record, @Param("example") ActfglExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTFGL
     *
     * @mbggenerated Sun Mar 06 10:29:25 CST 2011
     */
    int updateByExample(@Param("record") Actfgl record, @Param("example") ActfglExample example);
}