package cbs.repository.account.billinfo.dao;

import cbs.repository.account.billinfo.model.Actlsm;
import cbs.repository.account.billinfo.model.ActlsmExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ActlsmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTLSM
     *
     * @mbggenerated Wed Mar 02 17:20:04 CST 2011
     */
    int countByExample(ActlsmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTLSM
     *
     * @mbggenerated Wed Mar 02 17:20:04 CST 2011
     */
    int deleteByExample(ActlsmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTLSM
     *
     * @mbggenerated Wed Mar 02 17:20:04 CST 2011
     */
    int insert(Actlsm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTLSM
     *
     * @mbggenerated Wed Mar 02 17:20:04 CST 2011
     */
    int insertSelective(Actlsm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTLSM
     *
     * @mbggenerated Wed Mar 02 17:20:04 CST 2011
     */
    List<Actlsm> selectByExample(ActlsmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTLSM
     *
     * @mbggenerated Wed Mar 02 17:20:04 CST 2011
     */
    int updateByExampleSelective(@Param("record") Actlsm record, @Param("example") ActlsmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTLSM
     *
     * @mbggenerated Wed Mar 02 17:20:04 CST 2011
     */
    int updateByExample(@Param("record") Actlsm record, @Param("example") ActlsmExample example);
}