package cbs.repository.account.billinfo.dao;

import cbs.repository.account.billinfo.model.Actnsm;
import cbs.repository.account.billinfo.model.ActnsmExample;
import java.util.List;

import cbs.repository.account.maininfo.model.ActstmForActnum;
import cbs.repository.account.maininfo.model.ActstmForStmCotent;
import org.apache.ibatis.annotations.Param;

public interface ActnsmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTNSM
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int countByExample(ActnsmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTNSM
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int deleteByExample(ActnsmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTNSM
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int insert(Actnsm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTNSM
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int insertSelective(Actnsm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTNSM
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    List<Actnsm> selectByExample(ActnsmExample example);

    /**
     * createBy: haiyuhuang
     * date:     2011-03-24
     * 查询账号基本信息*/
    List<ActstmForActnum> selectForActnum(@Param("orgidt") String orgidt);

    /**
     * createBy: haiyuhuang
     * date:     2011-03-24
     * 按照账号查询账号传票信息*/
    List<ActstmForStmCotent> selectForStmContent(@Param("sysidt") String sysidt,@Param("orgidt") String orgidt
            ,@Param("cusidt") String cusidt,@Param("apcode") String apcode,@Param("curcde") String curcde);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTNSM
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int updateByExampleSelective(@Param("record") Actnsm record, @Param("example") ActnsmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTNSM
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int updateByExample(@Param("record") Actnsm record, @Param("example") ActnsmExample example);
}