package cbs.repository.platform.dao;

import cbs.repository.platform.model.Pterror;
import cbs.repository.platform.model.PterrorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PterrorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTERROR
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int countByExample(PterrorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTERROR
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int deleteByExample(PterrorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTERROR
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int insert(Pterror record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTERROR
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int insertSelective(Pterror record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTERROR
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    List<Pterror> selectByExample(PterrorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTERROR
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int updateByExampleSelective(@Param("record") Pterror record, @Param("example") PterrorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTERROR
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int updateByExample(@Param("record") Pterror record, @Param("example") PterrorExample example);
}