package cbs.repository.platform.dao;

import cbs.repository.platform.model.Scttlr;
import cbs.repository.platform.model.ScttlrExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import java.util.List;

public interface ScttlrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCTTLR
     *
     * @mbggenerated Mon Nov 22 22:47:20 CST 2010
     */
    int countByExample(ScttlrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCTTLR
     *
     * @mbggenerated Mon Nov 22 22:47:20 CST 2010
     */
    int deleteByExample(ScttlrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCTTLR
     *
     * @mbggenerated Mon Nov 22 22:47:20 CST 2010
     */
    int insert(Scttlr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCTTLR
     *
     * @mbggenerated Mon Nov 22 22:47:20 CST 2010
     */
    int insertSelective(Scttlr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCTTLR
     *
     * @mbggenerated Mon Nov 22 22:47:20 CST 2010
     */
    List<Scttlr> selectByExample(ScttlrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCTTLR
     *
     * @mbggenerated Mon Nov 22 22:47:20 CST 2010
     */
    int updateByExampleSelective(@Param("record") Scttlr record, @Param("example") ScttlrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCTTLR
     *
     * @mbggenerated Mon Nov 22 22:47:20 CST 2010
     */
    int updateByExample(@Param("record") Scttlr record, @Param("example") ScttlrExample example);

    //zhanrui
    @Select("select vchset from scttlr where tlrnum = #{tlrnum}")
    int selectVchsetByTlrnum(String tlrnum);

    @Update("update  scttlr  set vchset = vchset+1 where tlrnum = #{tlrnum}")
    int updateVchsetByTlrnum(String tlrnum);
}