package cbs.repository.platform.dao;

import cbs.repository.platform.model.SysSchedulerLog;
import cbs.repository.platform.model.SysSchedulerLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysSchedulerLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_SCHEDULER_LOG
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int countByExample(SysSchedulerLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_SCHEDULER_LOG
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int deleteByExample(SysSchedulerLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_SCHEDULER_LOG
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int insert(SysSchedulerLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_SCHEDULER_LOG
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int insertSelective(SysSchedulerLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_SCHEDULER_LOG
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    List<SysSchedulerLog> selectByExample(SysSchedulerLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_SCHEDULER_LOG
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int updateByExampleSelective(@Param("record") SysSchedulerLog record, @Param("example") SysSchedulerLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_SCHEDULER_LOG
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int updateByExample(@Param("record") SysSchedulerLog record, @Param("example") SysSchedulerLogExample example);
}