package cbs.repository.platform.dao;

import cbs.repository.platform.model.SysScheduler;
import cbs.repository.platform.model.SysSchedulerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysSchedulerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_SCHEDULER
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int countByExample(SysSchedulerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_SCHEDULER
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int deleteByExample(SysSchedulerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_SCHEDULER
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int insert(SysScheduler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_SCHEDULER
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int insertSelective(SysScheduler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_SCHEDULER
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    List<SysScheduler> selectByExample(SysSchedulerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_SCHEDULER
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int updateByExampleSelective(@Param("record") SysScheduler record, @Param("example") SysSchedulerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_SCHEDULER
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int updateByExample(@Param("record") SysScheduler record, @Param("example") SysSchedulerExample example);
}