package cbs.repository.code.dao;

import cbs.repository.code.model.Actani;
import cbs.repository.code.model.ActaniExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface ActaniMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTANI
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int countByExample(ActaniExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTANI
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int deleteByExample(ActaniExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTANI
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int insert(Actani record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTANI
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int insertSelective(Actani record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTANI
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    List<Actani> selectByExample(ActaniExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTANI
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int updateByExampleSelective(@Param("record") Actani record, @Param("example") ActaniExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTANI
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int updateByExample(@Param("record") Actani record, @Param("example") ActaniExample example);

    //zhanrui
    @Select("select count(*) from actani where trim(oldacn) = #{actno}")
    int countByOldacn(String actno);

    @Select("select * from actani where trim(oldacn) = #{actno} and orgidt = #{orgidt}")
    Actani selectByOldacn(@Param("actno")String actno, @Param("orgidt")String orgidt);

    @Select("select trim(oldacn) from actani where orgidt = #{orgidt} and cusidt = #{cusidt} and apcode = #{apcode} and curcde = #{curcde}")
    String selectByActnoCode(@Param("orgidt")String orgidt, @Param("cusidt")String cusidt, @Param("apcode")String apcode, @Param("curcde")String curcde);

}