package cbs.repository.code.dao;

import cbs.repository.code.model.Actapc;
import cbs.repository.code.model.ActapcExample;
import java.util.List;

import cbs.repository.code.model.Actirt;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface ActapcMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTAPC
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int countByExample(ActapcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTAPC
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int deleteByExample(ActapcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTAPC
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int insert(Actapc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTAPC
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int insertSelective(Actapc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTAPC
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    List<Actapc> selectByExample(ActapcExample example);

    /**
     * createBy: haiyuhuang
     * date:     2011-01-10
     * remark: 根据glccat选择核算码数据：
     *         公司客户：glccat = '2' 内不可： glccat = 其它*/
    List<Actapc> selectApcByGlccat(@Param("glccat") String glccat);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTAPC
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int updateByExampleSelective(@Param("record") Actapc record, @Param("example") ActapcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTAPC
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int updateByExample(@Param("record") Actapc record, @Param("example") ActapcExample example);

      List<Actapc> selectApcByCondition(@Param("glcode") String glcode,@Param("apctyp") String apctyp,
                                      @Param("apcode") String apcode, @Param("apcnam") String apcnam);
    
    @Select("select *  from actapc where apcode=#{param} and recsts=#{recsts}")
    Actapc selectApcByCode(@Param("param")String param,@Param("recsts")String recsts);
}