package cbs.repository.code.dao;

import cbs.repository.code.model.Actapc;
import cbs.repository.code.model.Actglc;
import cbs.repository.code.model.ActglcExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface ActglcMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTGLC
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int countByExample(ActglcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTGLC
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int deleteByExample(ActglcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTGLC
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int insert(Actglc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTGLC
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int insertSelective(Actglc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTGLC
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    List<Actglc> selectByExample(ActglcExample example);
    /**
     * createBy: haiyuhuang
     * date:     2011-01-10*/
    List<Actglc> selectByApcode(@Param("apcode") String apcode);
    /**
     * createBy: haiyuhuang
     * date:     2011-01-18*/
    List<Actglc> selectGrpActForPlc(@Param("curcde") String curcde,@Param("plctyp") String plctyp);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTGLC
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int updateByExampleSelective(@Param("record") Actglc record, @Param("example") ActglcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTGLC
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int updateByExample(@Param("record") Actglc record, @Param("example") ActglcExample example);

    String getGLCBALByApcode(@Param("apcode") String apcode);

    @Select("select *  from actglc where glcode=#{param} and recsts = #{recsts}")
    Actglc selectGlcByCode(@Param("param")String param,@Param("recsts")String recsts);
}