package cbs.repository.code.dao;

import cbs.repository.code.model.Actxrt;
import cbs.repository.code.model.ActxrtExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActxrtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTXRT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int countByExample(ActxrtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTXRT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int deleteByExample(ActxrtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTXRT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int insert(Actxrt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTXRT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int insertSelective(Actxrt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTXRT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    List<Actxrt> selectByExample(ActxrtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTXRT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int updateByExampleSelective(@Param("record") Actxrt record, @Param("example") ActxrtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTXRT
     *
     * @mbggenerated Sun Nov 21 21:36:06 CST 2010
     */
    int updateByExample(@Param("record") Actxrt record, @Param("example") ActxrtExample example);
}