package cbs.repository.account.maininfo.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ActbahExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ACTBAH
     *
     * @mbggenerated Thu Dec 23 14:10:12 CST 2010
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ACTBAH
     *
     * @mbggenerated Thu Dec 23 14:10:12 CST 2010
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ACTBAH
     *
     * @mbggenerated Thu Dec 23 14:10:12 CST 2010
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTBAH
     *
     * @mbggenerated Thu Dec 23 14:10:12 CST 2010
     */
    public ActbahExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTBAH
     *
     * @mbggenerated Thu Dec 23 14:10:12 CST 2010
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTBAH
     *
     * @mbggenerated Thu Dec 23 14:10:12 CST 2010
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTBAH
     *
     * @mbggenerated Thu Dec 23 14:10:12 CST 2010
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTBAH
     *
     * @mbggenerated Thu Dec 23 14:10:12 CST 2010
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTBAH
     *
     * @mbggenerated Thu Dec 23 14:10:12 CST 2010
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTBAH
     *
     * @mbggenerated Thu Dec 23 14:10:12 CST 2010
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTBAH
     *
     * @mbggenerated Thu Dec 23 14:10:12 CST 2010
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTBAH
     *
     * @mbggenerated Thu Dec 23 14:10:12 CST 2010
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTBAH
     *
     * @mbggenerated Thu Dec 23 14:10:12 CST 2010
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTBAH
     *
     * @mbggenerated Thu Dec 23 14:10:12 CST 2010
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ACTBAH
     *
     * @mbggenerated Thu Dec 23 14:10:12 CST 2010
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSysidtIsNull() {
            addCriterion("SYSIDT is null");
            return (Criteria) this;
        }

        public Criteria andSysidtIsNotNull() {
            addCriterion("SYSIDT is not null");
            return (Criteria) this;
        }

        public Criteria andSysidtEqualTo(String value) {
            addCriterion("SYSIDT =", value, "sysidt");
            return (Criteria) this;
        }

        public Criteria andSysidtNotEqualTo(String value) {
            addCriterion("SYSIDT <>", value, "sysidt");
            return (Criteria) this;
        }

        public Criteria andSysidtGreaterThan(String value) {
            addCriterion("SYSIDT >", value, "sysidt");
            return (Criteria) this;
        }

        public Criteria andSysidtGreaterThanOrEqualTo(String value) {
            addCriterion("SYSIDT >=", value, "sysidt");
            return (Criteria) this;
        }

        public Criteria andSysidtLessThan(String value) {
            addCriterion("SYSIDT <", value, "sysidt");
            return (Criteria) this;
        }

        public Criteria andSysidtLessThanOrEqualTo(String value) {
            addCriterion("SYSIDT <=", value, "sysidt");
            return (Criteria) this;
        }

        public Criteria andSysidtLike(String value) {
            addCriterion("SYSIDT like", value, "sysidt");
            return (Criteria) this;
        }

        public Criteria andSysidtNotLike(String value) {
            addCriterion("SYSIDT not like", value, "sysidt");
            return (Criteria) this;
        }

        public Criteria andSysidtIn(List<String> values) {
            addCriterion("SYSIDT in", values, "sysidt");
            return (Criteria) this;
        }

        public Criteria andSysidtNotIn(List<String> values) {
            addCriterion("SYSIDT not in", values, "sysidt");
            return (Criteria) this;
        }

        public Criteria andSysidtBetween(String value1, String value2) {
            addCriterion("SYSIDT between", value1, value2, "sysidt");
            return (Criteria) this;
        }

        public Criteria andSysidtNotBetween(String value1, String value2) {
            addCriterion("SYSIDT not between", value1, value2, "sysidt");
            return (Criteria) this;
        }

        public Criteria andOrgidtIsNull() {
            addCriterion("ORGIDT is null");
            return (Criteria) this;
        }

        public Criteria andOrgidtIsNotNull() {
            addCriterion("ORGIDT is not null");
            return (Criteria) this;
        }

        public Criteria andOrgidtEqualTo(String value) {
            addCriterion("ORGIDT =", value, "orgidt");
            return (Criteria) this;
        }

        public Criteria andOrgidtNotEqualTo(String value) {
            addCriterion("ORGIDT <>", value, "orgidt");
            return (Criteria) this;
        }

        public Criteria andOrgidtGreaterThan(String value) {
            addCriterion("ORGIDT >", value, "orgidt");
            return (Criteria) this;
        }

        public Criteria andOrgidtGreaterThanOrEqualTo(String value) {
            addCriterion("ORGIDT >=", value, "orgidt");
            return (Criteria) this;
        }

        public Criteria andOrgidtLessThan(String value) {
            addCriterion("ORGIDT <", value, "orgidt");
            return (Criteria) this;
        }

        public Criteria andOrgidtLessThanOrEqualTo(String value) {
            addCriterion("ORGIDT <=", value, "orgidt");
            return (Criteria) this;
        }

        public Criteria andOrgidtLike(String value) {
            addCriterion("ORGIDT like", value, "orgidt");
            return (Criteria) this;
        }

        public Criteria andOrgidtNotLike(String value) {
            addCriterion("ORGIDT not like", value, "orgidt");
            return (Criteria) this;
        }

        public Criteria andOrgidtIn(List<String> values) {
            addCriterion("ORGIDT in", values, "orgidt");
            return (Criteria) this;
        }

        public Criteria andOrgidtNotIn(List<String> values) {
            addCriterion("ORGIDT not in", values, "orgidt");
            return (Criteria) this;
        }

        public Criteria andOrgidtBetween(String value1, String value2) {
            addCriterion("ORGIDT between", value1, value2, "orgidt");
            return (Criteria) this;
        }

        public Criteria andOrgidtNotBetween(String value1, String value2) {
            addCriterion("ORGIDT not between", value1, value2, "orgidt");
            return (Criteria) this;
        }

        public Criteria andCusidtIsNull() {
            addCriterion("CUSIDT is null");
            return (Criteria) this;
        }

        public Criteria andCusidtIsNotNull() {
            addCriterion("CUSIDT is not null");
            return (Criteria) this;
        }

        public Criteria andCusidtEqualTo(String value) {
            addCriterion("CUSIDT =", value, "cusidt");
            return (Criteria) this;
        }

        public Criteria andCusidtNotEqualTo(String value) {
            addCriterion("CUSIDT <>", value, "cusidt");
            return (Criteria) this;
        }

        public Criteria andCusidtGreaterThan(String value) {
            addCriterion("CUSIDT >", value, "cusidt");
            return (Criteria) this;
        }

        public Criteria andCusidtGreaterThanOrEqualTo(String value) {
            addCriterion("CUSIDT >=", value, "cusidt");
            return (Criteria) this;
        }

        public Criteria andCusidtLessThan(String value) {
            addCriterion("CUSIDT <", value, "cusidt");
            return (Criteria) this;
        }

        public Criteria andCusidtLessThanOrEqualTo(String value) {
            addCriterion("CUSIDT <=", value, "cusidt");
            return (Criteria) this;
        }

        public Criteria andCusidtLike(String value) {
            addCriterion("CUSIDT like", value, "cusidt");
            return (Criteria) this;
        }

        public Criteria andCusidtNotLike(String value) {
            addCriterion("CUSIDT not like", value, "cusidt");
            return (Criteria) this;
        }

        public Criteria andCusidtIn(List<String> values) {
            addCriterion("CUSIDT in", values, "cusidt");
            return (Criteria) this;
        }

        public Criteria andCusidtNotIn(List<String> values) {
            addCriterion("CUSIDT not in", values, "cusidt");
            return (Criteria) this;
        }

        public Criteria andCusidtBetween(String value1, String value2) {
            addCriterion("CUSIDT between", value1, value2, "cusidt");
            return (Criteria) this;
        }

        public Criteria andCusidtNotBetween(String value1, String value2) {
            addCriterion("CUSIDT not between", value1, value2, "cusidt");
            return (Criteria) this;
        }

        public Criteria andApcodeIsNull() {
            addCriterion("APCODE is null");
            return (Criteria) this;
        }

        public Criteria andApcodeIsNotNull() {
            addCriterion("APCODE is not null");
            return (Criteria) this;
        }

        public Criteria andApcodeEqualTo(String value) {
            addCriterion("APCODE =", value, "apcode");
            return (Criteria) this;
        }

        public Criteria andApcodeNotEqualTo(String value) {
            addCriterion("APCODE <>", value, "apcode");
            return (Criteria) this;
        }

        public Criteria andApcodeGreaterThan(String value) {
            addCriterion("APCODE >", value, "apcode");
            return (Criteria) this;
        }

        public Criteria andApcodeGreaterThanOrEqualTo(String value) {
            addCriterion("APCODE >=", value, "apcode");
            return (Criteria) this;
        }

        public Criteria andApcodeLessThan(String value) {
            addCriterion("APCODE <", value, "apcode");
            return (Criteria) this;
        }

        public Criteria andApcodeLessThanOrEqualTo(String value) {
            addCriterion("APCODE <=", value, "apcode");
            return (Criteria) this;
        }

        public Criteria andApcodeLike(String value) {
            addCriterion("APCODE like", value, "apcode");
            return (Criteria) this;
        }

        public Criteria andApcodeNotLike(String value) {
            addCriterion("APCODE not like", value, "apcode");
            return (Criteria) this;
        }

        public Criteria andApcodeIn(List<String> values) {
            addCriterion("APCODE in", values, "apcode");
            return (Criteria) this;
        }

        public Criteria andApcodeNotIn(List<String> values) {
            addCriterion("APCODE not in", values, "apcode");
            return (Criteria) this;
        }

        public Criteria andApcodeBetween(String value1, String value2) {
            addCriterion("APCODE between", value1, value2, "apcode");
            return (Criteria) this;
        }

        public Criteria andApcodeNotBetween(String value1, String value2) {
            addCriterion("APCODE not between", value1, value2, "apcode");
            return (Criteria) this;
        }

        public Criteria andCurcdeIsNull() {
            addCriterion("CURCDE is null");
            return (Criteria) this;
        }

        public Criteria andCurcdeIsNotNull() {
            addCriterion("CURCDE is not null");
            return (Criteria) this;
        }

        public Criteria andCurcdeEqualTo(String value) {
            addCriterion("CURCDE =", value, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeNotEqualTo(String value) {
            addCriterion("CURCDE <>", value, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeGreaterThan(String value) {
            addCriterion("CURCDE >", value, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeGreaterThanOrEqualTo(String value) {
            addCriterion("CURCDE >=", value, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeLessThan(String value) {
            addCriterion("CURCDE <", value, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeLessThanOrEqualTo(String value) {
            addCriterion("CURCDE <=", value, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeLike(String value) {
            addCriterion("CURCDE like", value, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeNotLike(String value) {
            addCriterion("CURCDE not like", value, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeIn(List<String> values) {
            addCriterion("CURCDE in", values, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeNotIn(List<String> values) {
            addCriterion("CURCDE not in", values, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeBetween(String value1, String value2) {
            addCriterion("CURCDE between", value1, value2, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeNotBetween(String value1, String value2) {
            addCriterion("CURCDE not between", value1, value2, "curcde");
            return (Criteria) this;
        }

        public Criteria andBahdatIsNull() {
            addCriterion("BAHDAT is null");
            return (Criteria) this;
        }

        public Criteria andBahdatIsNotNull() {
            addCriterion("BAHDAT is not null");
            return (Criteria) this;
        }

        public Criteria andBahdatEqualTo(Date value) {
            addCriterion("BAHDAT =", value, "bahdat");
            return (Criteria) this;
        }

        public Criteria andBahdatNotEqualTo(Date value) {
            addCriterion("BAHDAT <>", value, "bahdat");
            return (Criteria) this;
        }

        public Criteria andBahdatGreaterThan(Date value) {
            addCriterion("BAHDAT >", value, "bahdat");
            return (Criteria) this;
        }

        public Criteria andBahdatGreaterThanOrEqualTo(Date value) {
            addCriterion("BAHDAT >=", value, "bahdat");
            return (Criteria) this;
        }

        public Criteria andBahdatLessThan(Date value) {
            addCriterion("BAHDAT <", value, "bahdat");
            return (Criteria) this;
        }

        public Criteria andBahdatLessThanOrEqualTo(Date value) {
            addCriterion("BAHDAT <=", value, "bahdat");
            return (Criteria) this;
        }

        public Criteria andBahdatIn(List<Date> values) {
            addCriterion("BAHDAT in", values, "bahdat");
            return (Criteria) this;
        }

        public Criteria andBahdatNotIn(List<Date> values) {
            addCriterion("BAHDAT not in", values, "bahdat");
            return (Criteria) this;
        }

        public Criteria andBahdatBetween(Date value1, Date value2) {
            addCriterion("BAHDAT between", value1, value2, "bahdat");
            return (Criteria) this;
        }

        public Criteria andBahdatNotBetween(Date value1, Date value2) {
            addCriterion("BAHDAT not between", value1, value2, "bahdat");
            return (Criteria) this;
        }

        public Criteria andBokbalIsNull() {
            addCriterion("BOKBAL is null");
            return (Criteria) this;
        }

        public Criteria andBokbalIsNotNull() {
            addCriterion("BOKBAL is not null");
            return (Criteria) this;
        }

        public Criteria andBokbalEqualTo(Long value) {
            addCriterion("BOKBAL =", value, "bokbal");
            return (Criteria) this;
        }

        public Criteria andBokbalNotEqualTo(Long value) {
            addCriterion("BOKBAL <>", value, "bokbal");
            return (Criteria) this;
        }

        public Criteria andBokbalGreaterThan(Long value) {
            addCriterion("BOKBAL >", value, "bokbal");
            return (Criteria) this;
        }

        public Criteria andBokbalGreaterThanOrEqualTo(Long value) {
            addCriterion("BOKBAL >=", value, "bokbal");
            return (Criteria) this;
        }

        public Criteria andBokbalLessThan(Long value) {
            addCriterion("BOKBAL <", value, "bokbal");
            return (Criteria) this;
        }

        public Criteria andBokbalLessThanOrEqualTo(Long value) {
            addCriterion("BOKBAL <=", value, "bokbal");
            return (Criteria) this;
        }

        public Criteria andBokbalIn(List<Long> values) {
            addCriterion("BOKBAL in", values, "bokbal");
            return (Criteria) this;
        }

        public Criteria andBokbalNotIn(List<Long> values) {
            addCriterion("BOKBAL not in", values, "bokbal");
            return (Criteria) this;
        }

        public Criteria andBokbalBetween(Long value1, Long value2) {
            addCriterion("BOKBAL between", value1, value2, "bokbal");
            return (Criteria) this;
        }

        public Criteria andBokbalNotBetween(Long value1, Long value2) {
            addCriterion("BOKBAL not between", value1, value2, "bokbal");
            return (Criteria) this;
        }

        public Criteria andDdrcntIsNull() {
            addCriterion("DDRCNT is null");
            return (Criteria) this;
        }

        public Criteria andDdrcntIsNotNull() {
            addCriterion("DDRCNT is not null");
            return (Criteria) this;
        }

        public Criteria andDdrcntEqualTo(Integer value) {
            addCriterion("DDRCNT =", value, "ddrcnt");
            return (Criteria) this;
        }

        public Criteria andDdrcntNotEqualTo(Integer value) {
            addCriterion("DDRCNT <>", value, "ddrcnt");
            return (Criteria) this;
        }

        public Criteria andDdrcntGreaterThan(Integer value) {
            addCriterion("DDRCNT >", value, "ddrcnt");
            return (Criteria) this;
        }

        public Criteria andDdrcntGreaterThanOrEqualTo(Integer value) {
            addCriterion("DDRCNT >=", value, "ddrcnt");
            return (Criteria) this;
        }

        public Criteria andDdrcntLessThan(Integer value) {
            addCriterion("DDRCNT <", value, "ddrcnt");
            return (Criteria) this;
        }

        public Criteria andDdrcntLessThanOrEqualTo(Integer value) {
            addCriterion("DDRCNT <=", value, "ddrcnt");
            return (Criteria) this;
        }

        public Criteria andDdrcntIn(List<Integer> values) {
            addCriterion("DDRCNT in", values, "ddrcnt");
            return (Criteria) this;
        }

        public Criteria andDdrcntNotIn(List<Integer> values) {
            addCriterion("DDRCNT not in", values, "ddrcnt");
            return (Criteria) this;
        }

        public Criteria andDdrcntBetween(Integer value1, Integer value2) {
            addCriterion("DDRCNT between", value1, value2, "ddrcnt");
            return (Criteria) this;
        }

        public Criteria andDdrcntNotBetween(Integer value1, Integer value2) {
            addCriterion("DDRCNT not between", value1, value2, "ddrcnt");
            return (Criteria) this;
        }

        public Criteria andDdramtIsNull() {
            addCriterion("DDRAMT is null");
            return (Criteria) this;
        }

        public Criteria andDdramtIsNotNull() {
            addCriterion("DDRAMT is not null");
            return (Criteria) this;
        }

        public Criteria andDdramtEqualTo(Long value) {
            addCriterion("DDRAMT =", value, "ddramt");
            return (Criteria) this;
        }

        public Criteria andDdramtNotEqualTo(Long value) {
            addCriterion("DDRAMT <>", value, "ddramt");
            return (Criteria) this;
        }

        public Criteria andDdramtGreaterThan(Long value) {
            addCriterion("DDRAMT >", value, "ddramt");
            return (Criteria) this;
        }

        public Criteria andDdramtGreaterThanOrEqualTo(Long value) {
            addCriterion("DDRAMT >=", value, "ddramt");
            return (Criteria) this;
        }

        public Criteria andDdramtLessThan(Long value) {
            addCriterion("DDRAMT <", value, "ddramt");
            return (Criteria) this;
        }

        public Criteria andDdramtLessThanOrEqualTo(Long value) {
            addCriterion("DDRAMT <=", value, "ddramt");
            return (Criteria) this;
        }

        public Criteria andDdramtIn(List<Long> values) {
            addCriterion("DDRAMT in", values, "ddramt");
            return (Criteria) this;
        }

        public Criteria andDdramtNotIn(List<Long> values) {
            addCriterion("DDRAMT not in", values, "ddramt");
            return (Criteria) this;
        }

        public Criteria andDdramtBetween(Long value1, Long value2) {
            addCriterion("DDRAMT between", value1, value2, "ddramt");
            return (Criteria) this;
        }

        public Criteria andDdramtNotBetween(Long value1, Long value2) {
            addCriterion("DDRAMT not between", value1, value2, "ddramt");
            return (Criteria) this;
        }

        public Criteria andDcrcntIsNull() {
            addCriterion("DCRCNT is null");
            return (Criteria) this;
        }

        public Criteria andDcrcntIsNotNull() {
            addCriterion("DCRCNT is not null");
            return (Criteria) this;
        }

        public Criteria andDcrcntEqualTo(Integer value) {
            addCriterion("DCRCNT =", value, "dcrcnt");
            return (Criteria) this;
        }

        public Criteria andDcrcntNotEqualTo(Integer value) {
            addCriterion("DCRCNT <>", value, "dcrcnt");
            return (Criteria) this;
        }

        public Criteria andDcrcntGreaterThan(Integer value) {
            addCriterion("DCRCNT >", value, "dcrcnt");
            return (Criteria) this;
        }

        public Criteria andDcrcntGreaterThanOrEqualTo(Integer value) {
            addCriterion("DCRCNT >=", value, "dcrcnt");
            return (Criteria) this;
        }

        public Criteria andDcrcntLessThan(Integer value) {
            addCriterion("DCRCNT <", value, "dcrcnt");
            return (Criteria) this;
        }

        public Criteria andDcrcntLessThanOrEqualTo(Integer value) {
            addCriterion("DCRCNT <=", value, "dcrcnt");
            return (Criteria) this;
        }

        public Criteria andDcrcntIn(List<Integer> values) {
            addCriterion("DCRCNT in", values, "dcrcnt");
            return (Criteria) this;
        }

        public Criteria andDcrcntNotIn(List<Integer> values) {
            addCriterion("DCRCNT not in", values, "dcrcnt");
            return (Criteria) this;
        }

        public Criteria andDcrcntBetween(Integer value1, Integer value2) {
            addCriterion("DCRCNT between", value1, value2, "dcrcnt");
            return (Criteria) this;
        }

        public Criteria andDcrcntNotBetween(Integer value1, Integer value2) {
            addCriterion("DCRCNT not between", value1, value2, "dcrcnt");
            return (Criteria) this;
        }

        public Criteria andDcramtIsNull() {
            addCriterion("DCRAMT is null");
            return (Criteria) this;
        }

        public Criteria andDcramtIsNotNull() {
            addCriterion("DCRAMT is not null");
            return (Criteria) this;
        }

        public Criteria andDcramtEqualTo(Long value) {
            addCriterion("DCRAMT =", value, "dcramt");
            return (Criteria) this;
        }

        public Criteria andDcramtNotEqualTo(Long value) {
            addCriterion("DCRAMT <>", value, "dcramt");
            return (Criteria) this;
        }

        public Criteria andDcramtGreaterThan(Long value) {
            addCriterion("DCRAMT >", value, "dcramt");
            return (Criteria) this;
        }

        public Criteria andDcramtGreaterThanOrEqualTo(Long value) {
            addCriterion("DCRAMT >=", value, "dcramt");
            return (Criteria) this;
        }

        public Criteria andDcramtLessThan(Long value) {
            addCriterion("DCRAMT <", value, "dcramt");
            return (Criteria) this;
        }

        public Criteria andDcramtLessThanOrEqualTo(Long value) {
            addCriterion("DCRAMT <=", value, "dcramt");
            return (Criteria) this;
        }

        public Criteria andDcramtIn(List<Long> values) {
            addCriterion("DCRAMT in", values, "dcramt");
            return (Criteria) this;
        }

        public Criteria andDcramtNotIn(List<Long> values) {
            addCriterion("DCRAMT not in", values, "dcramt");
            return (Criteria) this;
        }

        public Criteria andDcramtBetween(Long value1, Long value2) {
            addCriterion("DCRAMT between", value1, value2, "dcramt");
            return (Criteria) this;
        }

        public Criteria andDcramtNotBetween(Long value1, Long value2) {
            addCriterion("DCRAMT not between", value1, value2, "dcramt");
            return (Criteria) this;
        }

        public Criteria andDratsfIsNull() {
            addCriterion("DRATSF is null");
            return (Criteria) this;
        }

        public Criteria andDratsfIsNotNull() {
            addCriterion("DRATSF is not null");
            return (Criteria) this;
        }

        public Criteria andDratsfEqualTo(BigDecimal value) {
            addCriterion("DRATSF =", value, "dratsf");
            return (Criteria) this;
        }

        public Criteria andDratsfNotEqualTo(BigDecimal value) {
            addCriterion("DRATSF <>", value, "dratsf");
            return (Criteria) this;
        }

        public Criteria andDratsfGreaterThan(BigDecimal value) {
            addCriterion("DRATSF >", value, "dratsf");
            return (Criteria) this;
        }

        public Criteria andDratsfGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("DRATSF >=", value, "dratsf");
            return (Criteria) this;
        }

        public Criteria andDratsfLessThan(BigDecimal value) {
            addCriterion("DRATSF <", value, "dratsf");
            return (Criteria) this;
        }

        public Criteria andDratsfLessThanOrEqualTo(BigDecimal value) {
            addCriterion("DRATSF <=", value, "dratsf");
            return (Criteria) this;
        }

        public Criteria andDratsfIn(List<BigDecimal> values) {
            addCriterion("DRATSF in", values, "dratsf");
            return (Criteria) this;
        }

        public Criteria andDratsfNotIn(List<BigDecimal> values) {
            addCriterion("DRATSF not in", values, "dratsf");
            return (Criteria) this;
        }

        public Criteria andDratsfBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DRATSF between", value1, value2, "dratsf");
            return (Criteria) this;
        }

        public Criteria andDratsfNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DRATSF not between", value1, value2, "dratsf");
            return (Criteria) this;
        }

        public Criteria andCratsfIsNull() {
            addCriterion("CRATSF is null");
            return (Criteria) this;
        }

        public Criteria andCratsfIsNotNull() {
            addCriterion("CRATSF is not null");
            return (Criteria) this;
        }

        public Criteria andCratsfEqualTo(BigDecimal value) {
            addCriterion("CRATSF =", value, "cratsf");
            return (Criteria) this;
        }

        public Criteria andCratsfNotEqualTo(BigDecimal value) {
            addCriterion("CRATSF <>", value, "cratsf");
            return (Criteria) this;
        }

        public Criteria andCratsfGreaterThan(BigDecimal value) {
            addCriterion("CRATSF >", value, "cratsf");
            return (Criteria) this;
        }

        public Criteria andCratsfGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CRATSF >=", value, "cratsf");
            return (Criteria) this;
        }

        public Criteria andCratsfLessThan(BigDecimal value) {
            addCriterion("CRATSF <", value, "cratsf");
            return (Criteria) this;
        }

        public Criteria andCratsfLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CRATSF <=", value, "cratsf");
            return (Criteria) this;
        }

        public Criteria andCratsfIn(List<BigDecimal> values) {
            addCriterion("CRATSF in", values, "cratsf");
            return (Criteria) this;
        }

        public Criteria andCratsfNotIn(List<BigDecimal> values) {
            addCriterion("CRATSF not in", values, "cratsf");
            return (Criteria) this;
        }

        public Criteria andCratsfBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CRATSF between", value1, value2, "cratsf");
            return (Criteria) this;
        }

        public Criteria andCratsfNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CRATSF not between", value1, value2, "cratsf");
            return (Criteria) this;
        }

        public Criteria andIntstsIsNull() {
            addCriterion("INTSTS is null");
            return (Criteria) this;
        }

        public Criteria andIntstsIsNotNull() {
            addCriterion("INTSTS is not null");
            return (Criteria) this;
        }

        public Criteria andIntstsEqualTo(String value) {
            addCriterion("INTSTS =", value, "intsts");
            return (Criteria) this;
        }

        public Criteria andIntstsNotEqualTo(String value) {
            addCriterion("INTSTS <>", value, "intsts");
            return (Criteria) this;
        }

        public Criteria andIntstsGreaterThan(String value) {
            addCriterion("INTSTS >", value, "intsts");
            return (Criteria) this;
        }

        public Criteria andIntstsGreaterThanOrEqualTo(String value) {
            addCriterion("INTSTS >=", value, "intsts");
            return (Criteria) this;
        }

        public Criteria andIntstsLessThan(String value) {
            addCriterion("INTSTS <", value, "intsts");
            return (Criteria) this;
        }

        public Criteria andIntstsLessThanOrEqualTo(String value) {
            addCriterion("INTSTS <=", value, "intsts");
            return (Criteria) this;
        }

        public Criteria andIntstsLike(String value) {
            addCriterion("INTSTS like", value, "intsts");
            return (Criteria) this;
        }

        public Criteria andIntstsNotLike(String value) {
            addCriterion("INTSTS not like", value, "intsts");
            return (Criteria) this;
        }

        public Criteria andIntstsIn(List<String> values) {
            addCriterion("INTSTS in", values, "intsts");
            return (Criteria) this;
        }

        public Criteria andIntstsNotIn(List<String> values) {
            addCriterion("INTSTS not in", values, "intsts");
            return (Criteria) this;
        }

        public Criteria andIntstsBetween(String value1, String value2) {
            addCriterion("INTSTS between", value1, value2, "intsts");
            return (Criteria) this;
        }

        public Criteria andIntstsNotBetween(String value1, String value2) {
            addCriterion("INTSTS not between", value1, value2, "intsts");
            return (Criteria) this;
        }

        public Criteria andIntflgIsNull() {
            addCriterion("INTFLG is null");
            return (Criteria) this;
        }

        public Criteria andIntflgIsNotNull() {
            addCriterion("INTFLG is not null");
            return (Criteria) this;
        }

        public Criteria andIntflgEqualTo(String value) {
            addCriterion("INTFLG =", value, "intflg");
            return (Criteria) this;
        }

        public Criteria andIntflgNotEqualTo(String value) {
            addCriterion("INTFLG <>", value, "intflg");
            return (Criteria) this;
        }

        public Criteria andIntflgGreaterThan(String value) {
            addCriterion("INTFLG >", value, "intflg");
            return (Criteria) this;
        }

        public Criteria andIntflgGreaterThanOrEqualTo(String value) {
            addCriterion("INTFLG >=", value, "intflg");
            return (Criteria) this;
        }

        public Criteria andIntflgLessThan(String value) {
            addCriterion("INTFLG <", value, "intflg");
            return (Criteria) this;
        }

        public Criteria andIntflgLessThanOrEqualTo(String value) {
            addCriterion("INTFLG <=", value, "intflg");
            return (Criteria) this;
        }

        public Criteria andIntflgLike(String value) {
            addCriterion("INTFLG like", value, "intflg");
            return (Criteria) this;
        }

        public Criteria andIntflgNotLike(String value) {
            addCriterion("INTFLG not like", value, "intflg");
            return (Criteria) this;
        }

        public Criteria andIntflgIn(List<String> values) {
            addCriterion("INTFLG in", values, "intflg");
            return (Criteria) this;
        }

        public Criteria andIntflgNotIn(List<String> values) {
            addCriterion("INTFLG not in", values, "intflg");
            return (Criteria) this;
        }

        public Criteria andIntflgBetween(String value1, String value2) {
            addCriterion("INTFLG between", value1, value2, "intflg");
            return (Criteria) this;
        }

        public Criteria andIntflgNotBetween(String value1, String value2) {
            addCriterion("INTFLG not between", value1, value2, "intflg");
            return (Criteria) this;
        }

        public Criteria andDinratIsNull() {
            addCriterion("DINRAT is null");
            return (Criteria) this;
        }

        public Criteria andDinratIsNotNull() {
            addCriterion("DINRAT is not null");
            return (Criteria) this;
        }

        public Criteria andDinratEqualTo(String value) {
            addCriterion("DINRAT =", value, "dinrat");
            return (Criteria) this;
        }

        public Criteria andDinratNotEqualTo(String value) {
            addCriterion("DINRAT <>", value, "dinrat");
            return (Criteria) this;
        }

        public Criteria andDinratGreaterThan(String value) {
            addCriterion("DINRAT >", value, "dinrat");
            return (Criteria) this;
        }

        public Criteria andDinratGreaterThanOrEqualTo(String value) {
            addCriterion("DINRAT >=", value, "dinrat");
            return (Criteria) this;
        }

        public Criteria andDinratLessThan(String value) {
            addCriterion("DINRAT <", value, "dinrat");
            return (Criteria) this;
        }

        public Criteria andDinratLessThanOrEqualTo(String value) {
            addCriterion("DINRAT <=", value, "dinrat");
            return (Criteria) this;
        }

        public Criteria andDinratLike(String value) {
            addCriterion("DINRAT like", value, "dinrat");
            return (Criteria) this;
        }

        public Criteria andDinratNotLike(String value) {
            addCriterion("DINRAT not like", value, "dinrat");
            return (Criteria) this;
        }

        public Criteria andDinratIn(List<String> values) {
            addCriterion("DINRAT in", values, "dinrat");
            return (Criteria) this;
        }

        public Criteria andDinratNotIn(List<String> values) {
            addCriterion("DINRAT not in", values, "dinrat");
            return (Criteria) this;
        }

        public Criteria andDinratBetween(String value1, String value2) {
            addCriterion("DINRAT between", value1, value2, "dinrat");
            return (Criteria) this;
        }

        public Criteria andDinratNotBetween(String value1, String value2) {
            addCriterion("DINRAT not between", value1, value2, "dinrat");
            return (Criteria) this;
        }

        public Criteria andCinratIsNull() {
            addCriterion("CINRAT is null");
            return (Criteria) this;
        }

        public Criteria andCinratIsNotNull() {
            addCriterion("CINRAT is not null");
            return (Criteria) this;
        }

        public Criteria andCinratEqualTo(String value) {
            addCriterion("CINRAT =", value, "cinrat");
            return (Criteria) this;
        }

        public Criteria andCinratNotEqualTo(String value) {
            addCriterion("CINRAT <>", value, "cinrat");
            return (Criteria) this;
        }

        public Criteria andCinratGreaterThan(String value) {
            addCriterion("CINRAT >", value, "cinrat");
            return (Criteria) this;
        }

        public Criteria andCinratGreaterThanOrEqualTo(String value) {
            addCriterion("CINRAT >=", value, "cinrat");
            return (Criteria) this;
        }

        public Criteria andCinratLessThan(String value) {
            addCriterion("CINRAT <", value, "cinrat");
            return (Criteria) this;
        }

        public Criteria andCinratLessThanOrEqualTo(String value) {
            addCriterion("CINRAT <=", value, "cinrat");
            return (Criteria) this;
        }

        public Criteria andCinratLike(String value) {
            addCriterion("CINRAT like", value, "cinrat");
            return (Criteria) this;
        }

        public Criteria andCinratNotLike(String value) {
            addCriterion("CINRAT not like", value, "cinrat");
            return (Criteria) this;
        }

        public Criteria andCinratIn(List<String> values) {
            addCriterion("CINRAT in", values, "cinrat");
            return (Criteria) this;
        }

        public Criteria andCinratNotIn(List<String> values) {
            addCriterion("CINRAT not in", values, "cinrat");
            return (Criteria) this;
        }

        public Criteria andCinratBetween(String value1, String value2) {
            addCriterion("CINRAT between", value1, value2, "cinrat");
            return (Criteria) this;
        }

        public Criteria andCinratNotBetween(String value1, String value2) {
            addCriterion("CINRAT not between", value1, value2, "cinrat");
            return (Criteria) this;
        }

        public Criteria andRecstsIsNull() {
            addCriterion("RECSTS is null");
            return (Criteria) this;
        }

        public Criteria andRecstsIsNotNull() {
            addCriterion("RECSTS is not null");
            return (Criteria) this;
        }

        public Criteria andRecstsEqualTo(String value) {
            addCriterion("RECSTS =", value, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsNotEqualTo(String value) {
            addCriterion("RECSTS <>", value, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsGreaterThan(String value) {
            addCriterion("RECSTS >", value, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsGreaterThanOrEqualTo(String value) {
            addCriterion("RECSTS >=", value, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsLessThan(String value) {
            addCriterion("RECSTS <", value, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsLessThanOrEqualTo(String value) {
            addCriterion("RECSTS <=", value, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsLike(String value) {
            addCriterion("RECSTS like", value, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsNotLike(String value) {
            addCriterion("RECSTS not like", value, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsIn(List<String> values) {
            addCriterion("RECSTS in", values, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsNotIn(List<String> values) {
            addCriterion("RECSTS not in", values, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsBetween(String value1, String value2) {
            addCriterion("RECSTS between", value1, value2, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsNotBetween(String value1, String value2) {
            addCriterion("RECSTS not between", value1, value2, "recsts");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ACTBAH
     *
     * @mbggenerated do_not_delete_during_merge Thu Dec 23 14:10:12 CST 2010
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ACTBAH
     *
     * @mbggenerated Thu Dec 23 14:10:12 CST 2010
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}