package cbs.repository.account.maininfo.model;

import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
@Service
public class ActcmtExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ACTCMT
     *
     * @mbggenerated Tue Dec 28 17:17:15 CST 2010
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ACTCMT
     *
     * @mbggenerated Tue Dec 28 17:17:15 CST 2010
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ACTCMT
     *
     * @mbggenerated Tue Dec 28 17:17:15 CST 2010
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTCMT
     *
     * @mbggenerated Tue Dec 28 17:17:15 CST 2010
     */
    public ActcmtExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTCMT
     *
     * @mbggenerated Tue Dec 28 17:17:15 CST 2010
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTCMT
     *
     * @mbggenerated Tue Dec 28 17:17:15 CST 2010
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTCMT
     *
     * @mbggenerated Tue Dec 28 17:17:15 CST 2010
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTCMT
     *
     * @mbggenerated Tue Dec 28 17:17:15 CST 2010
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTCMT
     *
     * @mbggenerated Tue Dec 28 17:17:15 CST 2010
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTCMT
     *
     * @mbggenerated Tue Dec 28 17:17:15 CST 2010
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTCMT
     *
     * @mbggenerated Tue Dec 28 17:17:15 CST 2010
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTCMT
     *
     * @mbggenerated Tue Dec 28 17:17:15 CST 2010
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTCMT
     *
     * @mbggenerated Tue Dec 28 17:17:15 CST 2010
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTCMT
     *
     * @mbggenerated Tue Dec 28 17:17:15 CST 2010
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ACTCMT
     *
     * @mbggenerated Tue Dec 28 17:17:15 CST 2010
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCmtnumIsNull() {
            addCriterion("CMTNUM is null");
            return (Criteria) this;
        }

        public Criteria andCmtnumIsNotNull() {
            addCriterion("CMTNUM is not null");
            return (Criteria) this;
        }

        public Criteria andCmtnumEqualTo(String value) {
            addCriterion("CMTNUM =", value, "cmtnum");
            return (Criteria) this;
        }

        public Criteria andCmtnumNotEqualTo(String value) {
            addCriterion("CMTNUM <>", value, "cmtnum");
            return (Criteria) this;
        }

        public Criteria andCmtnumGreaterThan(String value) {
            addCriterion("CMTNUM >", value, "cmtnum");
            return (Criteria) this;
        }

        public Criteria andCmtnumGreaterThanOrEqualTo(String value) {
            addCriterion("CMTNUM >=", value, "cmtnum");
            return (Criteria) this;
        }

        public Criteria andCmtnumLessThan(String value) {
            addCriterion("CMTNUM <", value, "cmtnum");
            return (Criteria) this;
        }

        public Criteria andCmtnumLessThanOrEqualTo(String value) {
            addCriterion("CMTNUM <=", value, "cmtnum");
            return (Criteria) this;
        }

        public Criteria andCmtnumLike(String value) {
            addCriterion("CMTNUM like", value, "cmtnum");
            return (Criteria) this;
        }

        public Criteria andCmtnumNotLike(String value) {
            addCriterion("CMTNUM not like", value, "cmtnum");
            return (Criteria) this;
        }

        public Criteria andCmtnumIn(List<String> values) {
            addCriterion("CMTNUM in", values, "cmtnum");
            return (Criteria) this;
        }

        public Criteria andCmtnumNotIn(List<String> values) {
            addCriterion("CMTNUM not in", values, "cmtnum");
            return (Criteria) this;
        }

        public Criteria andCmtnumBetween(String value1, String value2) {
            addCriterion("CMTNUM between", value1, value2, "cmtnum");
            return (Criteria) this;
        }

        public Criteria andCmtnumNotBetween(String value1, String value2) {
            addCriterion("CMTNUM not between", value1, value2, "cmtnum");
            return (Criteria) this;
        }

        public Criteria andHqncusIsNull() {
            addCriterion("HQNCUS is null");
            return (Criteria) this;
        }

        public Criteria andHqncusIsNotNull() {
            addCriterion("HQNCUS is not null");
            return (Criteria) this;
        }

        public Criteria andHqncusEqualTo(String value) {
            addCriterion("HQNCUS =", value, "hqncus");
            return (Criteria) this;
        }

        public Criteria andHqncusNotEqualTo(String value) {
            addCriterion("HQNCUS <>", value, "hqncus");
            return (Criteria) this;
        }

        public Criteria andHqncusGreaterThan(String value) {
            addCriterion("HQNCUS >", value, "hqncus");
            return (Criteria) this;
        }

        public Criteria andHqncusGreaterThanOrEqualTo(String value) {
            addCriterion("HQNCUS >=", value, "hqncus");
            return (Criteria) this;
        }

        public Criteria andHqncusLessThan(String value) {
            addCriterion("HQNCUS <", value, "hqncus");
            return (Criteria) this;
        }

        public Criteria andHqncusLessThanOrEqualTo(String value) {
            addCriterion("HQNCUS <=", value, "hqncus");
            return (Criteria) this;
        }

        public Criteria andHqncusLike(String value) {
            addCriterion("HQNCUS like", value, "hqncus");
            return (Criteria) this;
        }

        public Criteria andHqncusNotLike(String value) {
            addCriterion("HQNCUS not like", value, "hqncus");
            return (Criteria) this;
        }

        public Criteria andHqncusIn(List<String> values) {
            addCriterion("HQNCUS in", values, "hqncus");
            return (Criteria) this;
        }

        public Criteria andHqncusNotIn(List<String> values) {
            addCriterion("HQNCUS not in", values, "hqncus");
            return (Criteria) this;
        }

        public Criteria andHqncusBetween(String value1, String value2) {
            addCriterion("HQNCUS between", value1, value2, "hqncus");
            return (Criteria) this;
        }

        public Criteria andHqncusNotBetween(String value1, String value2) {
            addCriterion("HQNCUS not between", value1, value2, "hqncus");
            return (Criteria) this;
        }

        public Criteria andHqlcurIsNull() {
            addCriterion("HQLCUR is null");
            return (Criteria) this;
        }

        public Criteria andHqlcurIsNotNull() {
            addCriterion("HQLCUR is not null");
            return (Criteria) this;
        }

        public Criteria andHqlcurEqualTo(String value) {
            addCriterion("HQLCUR =", value, "hqlcur");
            return (Criteria) this;
        }

        public Criteria andHqlcurNotEqualTo(String value) {
            addCriterion("HQLCUR <>", value, "hqlcur");
            return (Criteria) this;
        }

        public Criteria andHqlcurGreaterThan(String value) {
            addCriterion("HQLCUR >", value, "hqlcur");
            return (Criteria) this;
        }

        public Criteria andHqlcurGreaterThanOrEqualTo(String value) {
            addCriterion("HQLCUR >=", value, "hqlcur");
            return (Criteria) this;
        }

        public Criteria andHqlcurLessThan(String value) {
            addCriterion("HQLCUR <", value, "hqlcur");
            return (Criteria) this;
        }

        public Criteria andHqlcurLessThanOrEqualTo(String value) {
            addCriterion("HQLCUR <=", value, "hqlcur");
            return (Criteria) this;
        }

        public Criteria andHqlcurLike(String value) {
            addCriterion("HQLCUR like", value, "hqlcur");
            return (Criteria) this;
        }

        public Criteria andHqlcurNotLike(String value) {
            addCriterion("HQLCUR not like", value, "hqlcur");
            return (Criteria) this;
        }

        public Criteria andHqlcurIn(List<String> values) {
            addCriterion("HQLCUR in", values, "hqlcur");
            return (Criteria) this;
        }

        public Criteria andHqlcurNotIn(List<String> values) {
            addCriterion("HQLCUR not in", values, "hqlcur");
            return (Criteria) this;
        }

        public Criteria andHqlcurBetween(String value1, String value2) {
            addCriterion("HQLCUR between", value1, value2, "hqlcur");
            return (Criteria) this;
        }

        public Criteria andHqlcurNotBetween(String value1, String value2) {
            addCriterion("HQLCUR not between", value1, value2, "hqlcur");
            return (Criteria) this;
        }

        public Criteria andLoccusIsNull() {
            addCriterion("LOCCUS is null");
            return (Criteria) this;
        }

        public Criteria andLoccusIsNotNull() {
            addCriterion("LOCCUS is not null");
            return (Criteria) this;
        }

        public Criteria andLoccusEqualTo(String value) {
            addCriterion("LOCCUS =", value, "loccus");
            return (Criteria) this;
        }

        public Criteria andLoccusNotEqualTo(String value) {
            addCriterion("LOCCUS <>", value, "loccus");
            return (Criteria) this;
        }

        public Criteria andLoccusGreaterThan(String value) {
            addCriterion("LOCCUS >", value, "loccus");
            return (Criteria) this;
        }

        public Criteria andLoccusGreaterThanOrEqualTo(String value) {
            addCriterion("LOCCUS >=", value, "loccus");
            return (Criteria) this;
        }

        public Criteria andLoccusLessThan(String value) {
            addCriterion("LOCCUS <", value, "loccus");
            return (Criteria) this;
        }

        public Criteria andLoccusLessThanOrEqualTo(String value) {
            addCriterion("LOCCUS <=", value, "loccus");
            return (Criteria) this;
        }

        public Criteria andLoccusLike(String value) {
            addCriterion("LOCCUS like", value, "loccus");
            return (Criteria) this;
        }

        public Criteria andLoccusNotLike(String value) {
            addCriterion("LOCCUS not like", value, "loccus");
            return (Criteria) this;
        }

        public Criteria andLoccusIn(List<String> values) {
            addCriterion("LOCCUS in", values, "loccus");
            return (Criteria) this;
        }

        public Criteria andLoccusNotIn(List<String> values) {
            addCriterion("LOCCUS not in", values, "loccus");
            return (Criteria) this;
        }

        public Criteria andLoccusBetween(String value1, String value2) {
            addCriterion("LOCCUS between", value1, value2, "loccus");
            return (Criteria) this;
        }

        public Criteria andLoccusNotBetween(String value1, String value2) {
            addCriterion("LOCCUS not between", value1, value2, "loccus");
            return (Criteria) this;
        }

        public Criteria andLoccurIsNull() {
            addCriterion("LOCCUR is null");
            return (Criteria) this;
        }

        public Criteria andLoccurIsNotNull() {
            addCriterion("LOCCUR is not null");
            return (Criteria) this;
        }

        public Criteria andLoccurEqualTo(String value) {
            addCriterion("LOCCUR =", value, "loccur");
            return (Criteria) this;
        }

        public Criteria andLoccurNotEqualTo(String value) {
            addCriterion("LOCCUR <>", value, "loccur");
            return (Criteria) this;
        }

        public Criteria andLoccurGreaterThan(String value) {
            addCriterion("LOCCUR >", value, "loccur");
            return (Criteria) this;
        }

        public Criteria andLoccurGreaterThanOrEqualTo(String value) {
            addCriterion("LOCCUR >=", value, "loccur");
            return (Criteria) this;
        }

        public Criteria andLoccurLessThan(String value) {
            addCriterion("LOCCUR <", value, "loccur");
            return (Criteria) this;
        }

        public Criteria andLoccurLessThanOrEqualTo(String value) {
            addCriterion("LOCCUR <=", value, "loccur");
            return (Criteria) this;
        }

        public Criteria andLoccurLike(String value) {
            addCriterion("LOCCUR like", value, "loccur");
            return (Criteria) this;
        }

        public Criteria andLoccurNotLike(String value) {
            addCriterion("LOCCUR not like", value, "loccur");
            return (Criteria) this;
        }

        public Criteria andLoccurIn(List<String> values) {
            addCriterion("LOCCUR in", values, "loccur");
            return (Criteria) this;
        }

        public Criteria andLoccurNotIn(List<String> values) {
            addCriterion("LOCCUR not in", values, "loccur");
            return (Criteria) this;
        }

        public Criteria andLoccurBetween(String value1, String value2) {
            addCriterion("LOCCUR between", value1, value2, "loccur");
            return (Criteria) this;
        }

        public Criteria andLoccurNotBetween(String value1, String value2) {
            addCriterion("LOCCUR not between", value1, value2, "loccur");
            return (Criteria) this;
        }

        public Criteria andRptcurIsNull() {
            addCriterion("RPTCUR is null");
            return (Criteria) this;
        }

        public Criteria andRptcurIsNotNull() {
            addCriterion("RPTCUR is not null");
            return (Criteria) this;
        }

        public Criteria andRptcurEqualTo(String value) {
            addCriterion("RPTCUR =", value, "rptcur");
            return (Criteria) this;
        }

        public Criteria andRptcurNotEqualTo(String value) {
            addCriterion("RPTCUR <>", value, "rptcur");
            return (Criteria) this;
        }

        public Criteria andRptcurGreaterThan(String value) {
            addCriterion("RPTCUR >", value, "rptcur");
            return (Criteria) this;
        }

        public Criteria andRptcurGreaterThanOrEqualTo(String value) {
            addCriterion("RPTCUR >=", value, "rptcur");
            return (Criteria) this;
        }

        public Criteria andRptcurLessThan(String value) {
            addCriterion("RPTCUR <", value, "rptcur");
            return (Criteria) this;
        }

        public Criteria andRptcurLessThanOrEqualTo(String value) {
            addCriterion("RPTCUR <=", value, "rptcur");
            return (Criteria) this;
        }

        public Criteria andRptcurLike(String value) {
            addCriterion("RPTCUR like", value, "rptcur");
            return (Criteria) this;
        }

        public Criteria andRptcurNotLike(String value) {
            addCriterion("RPTCUR not like", value, "rptcur");
            return (Criteria) this;
        }

        public Criteria andRptcurIn(List<String> values) {
            addCriterion("RPTCUR in", values, "rptcur");
            return (Criteria) this;
        }

        public Criteria andRptcurNotIn(List<String> values) {
            addCriterion("RPTCUR not in", values, "rptcur");
            return (Criteria) this;
        }

        public Criteria andRptcurBetween(String value1, String value2) {
            addCriterion("RPTCUR between", value1, value2, "rptcur");
            return (Criteria) this;
        }

        public Criteria andRptcurNotBetween(String value1, String value2) {
            addCriterion("RPTCUR not between", value1, value2, "rptcur");
            return (Criteria) this;
        }

        public Criteria andSysverIsNull() {
            addCriterion("SYSVER is null");
            return (Criteria) this;
        }

        public Criteria andSysverIsNotNull() {
            addCriterion("SYSVER is not null");
            return (Criteria) this;
        }

        public Criteria andSysverEqualTo(String value) {
            addCriterion("SYSVER =", value, "sysver");
            return (Criteria) this;
        }

        public Criteria andSysverNotEqualTo(String value) {
            addCriterion("SYSVER <>", value, "sysver");
            return (Criteria) this;
        }

        public Criteria andSysverGreaterThan(String value) {
            addCriterion("SYSVER >", value, "sysver");
            return (Criteria) this;
        }

        public Criteria andSysverGreaterThanOrEqualTo(String value) {
            addCriterion("SYSVER >=", value, "sysver");
            return (Criteria) this;
        }

        public Criteria andSysverLessThan(String value) {
            addCriterion("SYSVER <", value, "sysver");
            return (Criteria) this;
        }

        public Criteria andSysverLessThanOrEqualTo(String value) {
            addCriterion("SYSVER <=", value, "sysver");
            return (Criteria) this;
        }

        public Criteria andSysverLike(String value) {
            addCriterion("SYSVER like", value, "sysver");
            return (Criteria) this;
        }

        public Criteria andSysverNotLike(String value) {
            addCriterion("SYSVER not like", value, "sysver");
            return (Criteria) this;
        }

        public Criteria andSysverIn(List<String> values) {
            addCriterion("SYSVER in", values, "sysver");
            return (Criteria) this;
        }

        public Criteria andSysverNotIn(List<String> values) {
            addCriterion("SYSVER not in", values, "sysver");
            return (Criteria) this;
        }

        public Criteria andSysverBetween(String value1, String value2) {
            addCriterion("SYSVER between", value1, value2, "sysver");
            return (Criteria) this;
        }

        public Criteria andSysverNotBetween(String value1, String value2) {
            addCriterion("SYSVER not between", value1, value2, "sysver");
            return (Criteria) this;
        }

        public Criteria andSysnamIsNull() {
            addCriterion("SYSNAM is null");
            return (Criteria) this;
        }

        public Criteria andSysnamIsNotNull() {
            addCriterion("SYSNAM is not null");
            return (Criteria) this;
        }

        public Criteria andSysnamEqualTo(String value) {
            addCriterion("SYSNAM =", value, "sysnam");
            return (Criteria) this;
        }

        public Criteria andSysnamNotEqualTo(String value) {
            addCriterion("SYSNAM <>", value, "sysnam");
            return (Criteria) this;
        }

        public Criteria andSysnamGreaterThan(String value) {
            addCriterion("SYSNAM >", value, "sysnam");
            return (Criteria) this;
        }

        public Criteria andSysnamGreaterThanOrEqualTo(String value) {
            addCriterion("SYSNAM >=", value, "sysnam");
            return (Criteria) this;
        }

        public Criteria andSysnamLessThan(String value) {
            addCriterion("SYSNAM <", value, "sysnam");
            return (Criteria) this;
        }

        public Criteria andSysnamLessThanOrEqualTo(String value) {
            addCriterion("SYSNAM <=", value, "sysnam");
            return (Criteria) this;
        }

        public Criteria andSysnamLike(String value) {
            addCriterion("SYSNAM like", value, "sysnam");
            return (Criteria) this;
        }

        public Criteria andSysnamNotLike(String value) {
            addCriterion("SYSNAM not like", value, "sysnam");
            return (Criteria) this;
        }

        public Criteria andSysnamIn(List<String> values) {
            addCriterion("SYSNAM in", values, "sysnam");
            return (Criteria) this;
        }

        public Criteria andSysnamNotIn(List<String> values) {
            addCriterion("SYSNAM not in", values, "sysnam");
            return (Criteria) this;
        }

        public Criteria andSysnamBetween(String value1, String value2) {
            addCriterion("SYSNAM between", value1, value2, "sysnam");
            return (Criteria) this;
        }

        public Criteria andSysnamNotBetween(String value1, String value2) {
            addCriterion("SYSNAM not between", value1, value2, "sysnam");
            return (Criteria) this;
        }

        public Criteria andPowtimIsNull() {
            addCriterion("POWTIM is null");
            return (Criteria) this;
        }

        public Criteria andPowtimIsNotNull() {
            addCriterion("POWTIM is not null");
            return (Criteria) this;
        }

        public Criteria andPowtimEqualTo(String value) {
            addCriterion("POWTIM =", value, "powtim");
            return (Criteria) this;
        }

        public Criteria andPowtimNotEqualTo(String value) {
            addCriterion("POWTIM <>", value, "powtim");
            return (Criteria) this;
        }

        public Criteria andPowtimGreaterThan(String value) {
            addCriterion("POWTIM >", value, "powtim");
            return (Criteria) this;
        }

        public Criteria andPowtimGreaterThanOrEqualTo(String value) {
            addCriterion("POWTIM >=", value, "powtim");
            return (Criteria) this;
        }

        public Criteria andPowtimLessThan(String value) {
            addCriterion("POWTIM <", value, "powtim");
            return (Criteria) this;
        }

        public Criteria andPowtimLessThanOrEqualTo(String value) {
            addCriterion("POWTIM <=", value, "powtim");
            return (Criteria) this;
        }

        public Criteria andPowtimLike(String value) {
            addCriterion("POWTIM like", value, "powtim");
            return (Criteria) this;
        }

        public Criteria andPowtimNotLike(String value) {
            addCriterion("POWTIM not like", value, "powtim");
            return (Criteria) this;
        }

        public Criteria andPowtimIn(List<String> values) {
            addCriterion("POWTIM in", values, "powtim");
            return (Criteria) this;
        }

        public Criteria andPowtimNotIn(List<String> values) {
            addCriterion("POWTIM not in", values, "powtim");
            return (Criteria) this;
        }

        public Criteria andPowtimBetween(String value1, String value2) {
            addCriterion("POWTIM between", value1, value2, "powtim");
            return (Criteria) this;
        }

        public Criteria andPowtimNotBetween(String value1, String value2) {
            addCriterion("POWTIM not between", value1, value2, "powtim");
            return (Criteria) this;
        }

        public Criteria andShttimIsNull() {
            addCriterion("SHTTIM is null");
            return (Criteria) this;
        }

        public Criteria andShttimIsNotNull() {
            addCriterion("SHTTIM is not null");
            return (Criteria) this;
        }

        public Criteria andShttimEqualTo(String value) {
            addCriterion("SHTTIM =", value, "shttim");
            return (Criteria) this;
        }

        public Criteria andShttimNotEqualTo(String value) {
            addCriterion("SHTTIM <>", value, "shttim");
            return (Criteria) this;
        }

        public Criteria andShttimGreaterThan(String value) {
            addCriterion("SHTTIM >", value, "shttim");
            return (Criteria) this;
        }

        public Criteria andShttimGreaterThanOrEqualTo(String value) {
            addCriterion("SHTTIM >=", value, "shttim");
            return (Criteria) this;
        }

        public Criteria andShttimLessThan(String value) {
            addCriterion("SHTTIM <", value, "shttim");
            return (Criteria) this;
        }

        public Criteria andShttimLessThanOrEqualTo(String value) {
            addCriterion("SHTTIM <=", value, "shttim");
            return (Criteria) this;
        }

        public Criteria andShttimLike(String value) {
            addCriterion("SHTTIM like", value, "shttim");
            return (Criteria) this;
        }

        public Criteria andShttimNotLike(String value) {
            addCriterion("SHTTIM not like", value, "shttim");
            return (Criteria) this;
        }

        public Criteria andShttimIn(List<String> values) {
            addCriterion("SHTTIM in", values, "shttim");
            return (Criteria) this;
        }

        public Criteria andShttimNotIn(List<String> values) {
            addCriterion("SHTTIM not in", values, "shttim");
            return (Criteria) this;
        }

        public Criteria andShttimBetween(String value1, String value2) {
            addCriterion("SHTTIM between", value1, value2, "shttim");
            return (Criteria) this;
        }

        public Criteria andShttimNotBetween(String value1, String value2) {
            addCriterion("SHTTIM not between", value1, value2, "shttim");
            return (Criteria) this;
        }

        public Criteria andBvamdsIsNull() {
            addCriterion("BVAMDS is null");
            return (Criteria) this;
        }

        public Criteria andBvamdsIsNotNull() {
            addCriterion("BVAMDS is not null");
            return (Criteria) this;
        }

        public Criteria andBvamdsEqualTo(Short value) {
            addCriterion("BVAMDS =", value, "bvamds");
            return (Criteria) this;
        }

        public Criteria andBvamdsNotEqualTo(Short value) {
            addCriterion("BVAMDS <>", value, "bvamds");
            return (Criteria) this;
        }

        public Criteria andBvamdsGreaterThan(Short value) {
            addCriterion("BVAMDS >", value, "bvamds");
            return (Criteria) this;
        }

        public Criteria andBvamdsGreaterThanOrEqualTo(Short value) {
            addCriterion("BVAMDS >=", value, "bvamds");
            return (Criteria) this;
        }

        public Criteria andBvamdsLessThan(Short value) {
            addCriterion("BVAMDS <", value, "bvamds");
            return (Criteria) this;
        }

        public Criteria andBvamdsLessThanOrEqualTo(Short value) {
            addCriterion("BVAMDS <=", value, "bvamds");
            return (Criteria) this;
        }

        public Criteria andBvamdsIn(List<Short> values) {
            addCriterion("BVAMDS in", values, "bvamds");
            return (Criteria) this;
        }

        public Criteria andBvamdsNotIn(List<Short> values) {
            addCriterion("BVAMDS not in", values, "bvamds");
            return (Criteria) this;
        }

        public Criteria andBvamdsBetween(Short value1, Short value2) {
            addCriterion("BVAMDS between", value1, value2, "bvamds");
            return (Criteria) this;
        }

        public Criteria andBvamdsNotBetween(Short value1, Short value2) {
            addCriterion("BVAMDS not between", value1, value2, "bvamds");
            return (Criteria) this;
        }

        public Criteria andBvaedtIsNull() {
            addCriterion("BVAEDT is null");
            return (Criteria) this;
        }

        public Criteria andBvaedtIsNotNull() {
            addCriterion("BVAEDT is not null");
            return (Criteria) this;
        }

        public Criteria andBvaedtEqualTo(Date value) {
            addCriterion("BVAEDT =", value, "bvaedt");
            return (Criteria) this;
        }

        public Criteria andBvaedtNotEqualTo(Date value) {
            addCriterion("BVAEDT <>", value, "bvaedt");
            return (Criteria) this;
        }

        public Criteria andBvaedtGreaterThan(Date value) {
            addCriterion("BVAEDT >", value, "bvaedt");
            return (Criteria) this;
        }

        public Criteria andBvaedtGreaterThanOrEqualTo(Date value) {
            addCriterion("BVAEDT >=", value, "bvaedt");
            return (Criteria) this;
        }

        public Criteria andBvaedtLessThan(Date value) {
            addCriterion("BVAEDT <", value, "bvaedt");
            return (Criteria) this;
        }

        public Criteria andBvaedtLessThanOrEqualTo(Date value) {
            addCriterion("BVAEDT <=", value, "bvaedt");
            return (Criteria) this;
        }

        public Criteria andBvaedtIn(List<Date> values) {
            addCriterion("BVAEDT in", values, "bvaedt");
            return (Criteria) this;
        }

        public Criteria andBvaedtNotIn(List<Date> values) {
            addCriterion("BVAEDT not in", values, "bvaedt");
            return (Criteria) this;
        }

        public Criteria andBvaedtBetween(Date value1, Date value2) {
            addCriterion("BVAEDT between", value1, value2, "bvaedt");
            return (Criteria) this;
        }

        public Criteria andBvaedtNotBetween(Date value1, Date value2) {
            addCriterion("BVAEDT not between", value1, value2, "bvaedt");
            return (Criteria) this;
        }

        public Criteria andIpydt1IsNull() {
            addCriterion("IPYDT1 is null");
            return (Criteria) this;
        }

        public Criteria andIpydt1IsNotNull() {
            addCriterion("IPYDT1 is not null");
            return (Criteria) this;
        }

        public Criteria andIpydt1EqualTo(String value) {
            addCriterion("IPYDT1 =", value, "ipydt1");
            return (Criteria) this;
        }

        public Criteria andIpydt1NotEqualTo(String value) {
            addCriterion("IPYDT1 <>", value, "ipydt1");
            return (Criteria) this;
        }

        public Criteria andIpydt1GreaterThan(String value) {
            addCriterion("IPYDT1 >", value, "ipydt1");
            return (Criteria) this;
        }

        public Criteria andIpydt1GreaterThanOrEqualTo(String value) {
            addCriterion("IPYDT1 >=", value, "ipydt1");
            return (Criteria) this;
        }

        public Criteria andIpydt1LessThan(String value) {
            addCriterion("IPYDT1 <", value, "ipydt1");
            return (Criteria) this;
        }

        public Criteria andIpydt1LessThanOrEqualTo(String value) {
            addCriterion("IPYDT1 <=", value, "ipydt1");
            return (Criteria) this;
        }

        public Criteria andIpydt1Like(String value) {
            addCriterion("IPYDT1 like", value, "ipydt1");
            return (Criteria) this;
        }

        public Criteria andIpydt1NotLike(String value) {
            addCriterion("IPYDT1 not like", value, "ipydt1");
            return (Criteria) this;
        }

        public Criteria andIpydt1In(List<String> values) {
            addCriterion("IPYDT1 in", values, "ipydt1");
            return (Criteria) this;
        }

        public Criteria andIpydt1NotIn(List<String> values) {
            addCriterion("IPYDT1 not in", values, "ipydt1");
            return (Criteria) this;
        }

        public Criteria andIpydt1Between(String value1, String value2) {
            addCriterion("IPYDT1 between", value1, value2, "ipydt1");
            return (Criteria) this;
        }

        public Criteria andIpydt1NotBetween(String value1, String value2) {
            addCriterion("IPYDT1 not between", value1, value2, "ipydt1");
            return (Criteria) this;
        }

        public Criteria andIpydt2IsNull() {
            addCriterion("IPYDT2 is null");
            return (Criteria) this;
        }

        public Criteria andIpydt2IsNotNull() {
            addCriterion("IPYDT2 is not null");
            return (Criteria) this;
        }

        public Criteria andIpydt2EqualTo(String value) {
            addCriterion("IPYDT2 =", value, "ipydt2");
            return (Criteria) this;
        }

        public Criteria andIpydt2NotEqualTo(String value) {
            addCriterion("IPYDT2 <>", value, "ipydt2");
            return (Criteria) this;
        }

        public Criteria andIpydt2GreaterThan(String value) {
            addCriterion("IPYDT2 >", value, "ipydt2");
            return (Criteria) this;
        }

        public Criteria andIpydt2GreaterThanOrEqualTo(String value) {
            addCriterion("IPYDT2 >=", value, "ipydt2");
            return (Criteria) this;
        }

        public Criteria andIpydt2LessThan(String value) {
            addCriterion("IPYDT2 <", value, "ipydt2");
            return (Criteria) this;
        }

        public Criteria andIpydt2LessThanOrEqualTo(String value) {
            addCriterion("IPYDT2 <=", value, "ipydt2");
            return (Criteria) this;
        }

        public Criteria andIpydt2Like(String value) {
            addCriterion("IPYDT2 like", value, "ipydt2");
            return (Criteria) this;
        }

        public Criteria andIpydt2NotLike(String value) {
            addCriterion("IPYDT2 not like", value, "ipydt2");
            return (Criteria) this;
        }

        public Criteria andIpydt2In(List<String> values) {
            addCriterion("IPYDT2 in", values, "ipydt2");
            return (Criteria) this;
        }

        public Criteria andIpydt2NotIn(List<String> values) {
            addCriterion("IPYDT2 not in", values, "ipydt2");
            return (Criteria) this;
        }

        public Criteria andIpydt2Between(String value1, String value2) {
            addCriterion("IPYDT2 between", value1, value2, "ipydt2");
            return (Criteria) this;
        }

        public Criteria andIpydt2NotBetween(String value1, String value2) {
            addCriterion("IPYDT2 not between", value1, value2, "ipydt2");
            return (Criteria) this;
        }

        public Criteria andIpydt3IsNull() {
            addCriterion("IPYDT3 is null");
            return (Criteria) this;
        }

        public Criteria andIpydt3IsNotNull() {
            addCriterion("IPYDT3 is not null");
            return (Criteria) this;
        }

        public Criteria andIpydt3EqualTo(String value) {
            addCriterion("IPYDT3 =", value, "ipydt3");
            return (Criteria) this;
        }

        public Criteria andIpydt3NotEqualTo(String value) {
            addCriterion("IPYDT3 <>", value, "ipydt3");
            return (Criteria) this;
        }

        public Criteria andIpydt3GreaterThan(String value) {
            addCriterion("IPYDT3 >", value, "ipydt3");
            return (Criteria) this;
        }

        public Criteria andIpydt3GreaterThanOrEqualTo(String value) {
            addCriterion("IPYDT3 >=", value, "ipydt3");
            return (Criteria) this;
        }

        public Criteria andIpydt3LessThan(String value) {
            addCriterion("IPYDT3 <", value, "ipydt3");
            return (Criteria) this;
        }

        public Criteria andIpydt3LessThanOrEqualTo(String value) {
            addCriterion("IPYDT3 <=", value, "ipydt3");
            return (Criteria) this;
        }

        public Criteria andIpydt3Like(String value) {
            addCriterion("IPYDT3 like", value, "ipydt3");
            return (Criteria) this;
        }

        public Criteria andIpydt3NotLike(String value) {
            addCriterion("IPYDT3 not like", value, "ipydt3");
            return (Criteria) this;
        }

        public Criteria andIpydt3In(List<String> values) {
            addCriterion("IPYDT3 in", values, "ipydt3");
            return (Criteria) this;
        }

        public Criteria andIpydt3NotIn(List<String> values) {
            addCriterion("IPYDT3 not in", values, "ipydt3");
            return (Criteria) this;
        }

        public Criteria andIpydt3Between(String value1, String value2) {
            addCriterion("IPYDT3 between", value1, value2, "ipydt3");
            return (Criteria) this;
        }

        public Criteria andIpydt3NotBetween(String value1, String value2) {
            addCriterion("IPYDT3 not between", value1, value2, "ipydt3");
            return (Criteria) this;
        }

        public Criteria andIpydt4IsNull() {
            addCriterion("IPYDT4 is null");
            return (Criteria) this;
        }

        public Criteria andIpydt4IsNotNull() {
            addCriterion("IPYDT4 is not null");
            return (Criteria) this;
        }

        public Criteria andIpydt4EqualTo(String value) {
            addCriterion("IPYDT4 =", value, "ipydt4");
            return (Criteria) this;
        }

        public Criteria andIpydt4NotEqualTo(String value) {
            addCriterion("IPYDT4 <>", value, "ipydt4");
            return (Criteria) this;
        }

        public Criteria andIpydt4GreaterThan(String value) {
            addCriterion("IPYDT4 >", value, "ipydt4");
            return (Criteria) this;
        }

        public Criteria andIpydt4GreaterThanOrEqualTo(String value) {
            addCriterion("IPYDT4 >=", value, "ipydt4");
            return (Criteria) this;
        }

        public Criteria andIpydt4LessThan(String value) {
            addCriterion("IPYDT4 <", value, "ipydt4");
            return (Criteria) this;
        }

        public Criteria andIpydt4LessThanOrEqualTo(String value) {
            addCriterion("IPYDT4 <=", value, "ipydt4");
            return (Criteria) this;
        }

        public Criteria andIpydt4Like(String value) {
            addCriterion("IPYDT4 like", value, "ipydt4");
            return (Criteria) this;
        }

        public Criteria andIpydt4NotLike(String value) {
            addCriterion("IPYDT4 not like", value, "ipydt4");
            return (Criteria) this;
        }

        public Criteria andIpydt4In(List<String> values) {
            addCriterion("IPYDT4 in", values, "ipydt4");
            return (Criteria) this;
        }

        public Criteria andIpydt4NotIn(List<String> values) {
            addCriterion("IPYDT4 not in", values, "ipydt4");
            return (Criteria) this;
        }

        public Criteria andIpydt4Between(String value1, String value2) {
            addCriterion("IPYDT4 between", value1, value2, "ipydt4");
            return (Criteria) this;
        }

        public Criteria andIpydt4NotBetween(String value1, String value2) {
            addCriterion("IPYDT4 not between", value1, value2, "ipydt4");
            return (Criteria) this;
        }

        public Criteria andFinedtIsNull() {
            addCriterion("FINEDT is null");
            return (Criteria) this;
        }

        public Criteria andFinedtIsNotNull() {
            addCriterion("FINEDT is not null");
            return (Criteria) this;
        }

        public Criteria andFinedtEqualTo(String value) {
            addCriterion("FINEDT =", value, "finedt");
            return (Criteria) this;
        }

        public Criteria andFinedtNotEqualTo(String value) {
            addCriterion("FINEDT <>", value, "finedt");
            return (Criteria) this;
        }

        public Criteria andFinedtGreaterThan(String value) {
            addCriterion("FINEDT >", value, "finedt");
            return (Criteria) this;
        }

        public Criteria andFinedtGreaterThanOrEqualTo(String value) {
            addCriterion("FINEDT >=", value, "finedt");
            return (Criteria) this;
        }

        public Criteria andFinedtLessThan(String value) {
            addCriterion("FINEDT <", value, "finedt");
            return (Criteria) this;
        }

        public Criteria andFinedtLessThanOrEqualTo(String value) {
            addCriterion("FINEDT <=", value, "finedt");
            return (Criteria) this;
        }

        public Criteria andFinedtLike(String value) {
            addCriterion("FINEDT like", value, "finedt");
            return (Criteria) this;
        }

        public Criteria andFinedtNotLike(String value) {
            addCriterion("FINEDT not like", value, "finedt");
            return (Criteria) this;
        }

        public Criteria andFinedtIn(List<String> values) {
            addCriterion("FINEDT in", values, "finedt");
            return (Criteria) this;
        }

        public Criteria andFinedtNotIn(List<String> values) {
            addCriterion("FINEDT not in", values, "finedt");
            return (Criteria) this;
        }

        public Criteria andFinedtBetween(String value1, String value2) {
            addCriterion("FINEDT between", value1, value2, "finedt");
            return (Criteria) this;
        }

        public Criteria andFinedtNotBetween(String value1, String value2) {
            addCriterion("FINEDT not between", value1, value2, "finedt");
            return (Criteria) this;
        }

        public Criteria andTaxedtIsNull() {
            addCriterion("TAXEDT is null");
            return (Criteria) this;
        }

        public Criteria andTaxedtIsNotNull() {
            addCriterion("TAXEDT is not null");
            return (Criteria) this;
        }

        public Criteria andTaxedtEqualTo(String value) {
            addCriterion("TAXEDT =", value, "taxedt");
            return (Criteria) this;
        }

        public Criteria andTaxedtNotEqualTo(String value) {
            addCriterion("TAXEDT <>", value, "taxedt");
            return (Criteria) this;
        }

        public Criteria andTaxedtGreaterThan(String value) {
            addCriterion("TAXEDT >", value, "taxedt");
            return (Criteria) this;
        }

        public Criteria andTaxedtGreaterThanOrEqualTo(String value) {
            addCriterion("TAXEDT >=", value, "taxedt");
            return (Criteria) this;
        }

        public Criteria andTaxedtLessThan(String value) {
            addCriterion("TAXEDT <", value, "taxedt");
            return (Criteria) this;
        }

        public Criteria andTaxedtLessThanOrEqualTo(String value) {
            addCriterion("TAXEDT <=", value, "taxedt");
            return (Criteria) this;
        }

        public Criteria andTaxedtLike(String value) {
            addCriterion("TAXEDT like", value, "taxedt");
            return (Criteria) this;
        }

        public Criteria andTaxedtNotLike(String value) {
            addCriterion("TAXEDT not like", value, "taxedt");
            return (Criteria) this;
        }

        public Criteria andTaxedtIn(List<String> values) {
            addCriterion("TAXEDT in", values, "taxedt");
            return (Criteria) this;
        }

        public Criteria andTaxedtNotIn(List<String> values) {
            addCriterion("TAXEDT not in", values, "taxedt");
            return (Criteria) this;
        }

        public Criteria andTaxedtBetween(String value1, String value2) {
            addCriterion("TAXEDT between", value1, value2, "taxedt");
            return (Criteria) this;
        }

        public Criteria andTaxedtNotBetween(String value1, String value2) {
            addCriterion("TAXEDT not between", value1, value2, "taxedt");
            return (Criteria) this;
        }

        public Criteria andPrestlIsNull() {
            addCriterion("PRESTL is null");
            return (Criteria) this;
        }

        public Criteria andPrestlIsNotNull() {
            addCriterion("PRESTL is not null");
            return (Criteria) this;
        }

        public Criteria andPrestlEqualTo(Date value) {
            addCriterion("PRESTL =", value, "prestl");
            return (Criteria) this;
        }

        public Criteria andPrestlNotEqualTo(Date value) {
            addCriterion("PRESTL <>", value, "prestl");
            return (Criteria) this;
        }

        public Criteria andPrestlGreaterThan(Date value) {
            addCriterion("PRESTL >", value, "prestl");
            return (Criteria) this;
        }

        public Criteria andPrestlGreaterThanOrEqualTo(Date value) {
            addCriterion("PRESTL >=", value, "prestl");
            return (Criteria) this;
        }

        public Criteria andPrestlLessThan(Date value) {
            addCriterion("PRESTL <", value, "prestl");
            return (Criteria) this;
        }

        public Criteria andPrestlLessThanOrEqualTo(Date value) {
            addCriterion("PRESTL <=", value, "prestl");
            return (Criteria) this;
        }

        public Criteria andPrestlIn(List<Date> values) {
            addCriterion("PRESTL in", values, "prestl");
            return (Criteria) this;
        }

        public Criteria andPrestlNotIn(List<Date> values) {
            addCriterion("PRESTL not in", values, "prestl");
            return (Criteria) this;
        }

        public Criteria andPrestlBetween(Date value1, Date value2) {
            addCriterion("PRESTL between", value1, value2, "prestl");
            return (Criteria) this;
        }

        public Criteria andPrestlNotBetween(Date value1, Date value2) {
            addCriterion("PRESTL not between", value1, value2, "prestl");
            return (Criteria) this;
        }

        public Criteria andCusinoIsNull() {
            addCriterion("CUSINO is null");
            return (Criteria) this;
        }

        public Criteria andCusinoIsNotNull() {
            addCriterion("CUSINO is not null");
            return (Criteria) this;
        }

        public Criteria andCusinoEqualTo(Integer value) {
            addCriterion("CUSINO =", value, "cusino");
            return (Criteria) this;
        }

        public Criteria andCusinoNotEqualTo(Integer value) {
            addCriterion("CUSINO <>", value, "cusino");
            return (Criteria) this;
        }

        public Criteria andCusinoGreaterThan(Integer value) {
            addCriterion("CUSINO >", value, "cusino");
            return (Criteria) this;
        }

        public Criteria andCusinoGreaterThanOrEqualTo(Integer value) {
            addCriterion("CUSINO >=", value, "cusino");
            return (Criteria) this;
        }

        public Criteria andCusinoLessThan(Integer value) {
            addCriterion("CUSINO <", value, "cusino");
            return (Criteria) this;
        }

        public Criteria andCusinoLessThanOrEqualTo(Integer value) {
            addCriterion("CUSINO <=", value, "cusino");
            return (Criteria) this;
        }

        public Criteria andCusinoIn(List<Integer> values) {
            addCriterion("CUSINO in", values, "cusino");
            return (Criteria) this;
        }

        public Criteria andCusinoNotIn(List<Integer> values) {
            addCriterion("CUSINO not in", values, "cusino");
            return (Criteria) this;
        }

        public Criteria andCusinoBetween(Integer value1, Integer value2) {
            addCriterion("CUSINO between", value1, value2, "cusino");
            return (Criteria) this;
        }

        public Criteria andCusinoNotBetween(Integer value1, Integer value2) {
            addCriterion("CUSINO not between", value1, value2, "cusino");
            return (Criteria) this;
        }

        public Criteria andJobnm1IsNull() {
            addCriterion("JOBNM1 is null");
            return (Criteria) this;
        }

        public Criteria andJobnm1IsNotNull() {
            addCriterion("JOBNM1 is not null");
            return (Criteria) this;
        }

        public Criteria andJobnm1EqualTo(String value) {
            addCriterion("JOBNM1 =", value, "jobnm1");
            return (Criteria) this;
        }

        public Criteria andJobnm1NotEqualTo(String value) {
            addCriterion("JOBNM1 <>", value, "jobnm1");
            return (Criteria) this;
        }

        public Criteria andJobnm1GreaterThan(String value) {
            addCriterion("JOBNM1 >", value, "jobnm1");
            return (Criteria) this;
        }

        public Criteria andJobnm1GreaterThanOrEqualTo(String value) {
            addCriterion("JOBNM1 >=", value, "jobnm1");
            return (Criteria) this;
        }

        public Criteria andJobnm1LessThan(String value) {
            addCriterion("JOBNM1 <", value, "jobnm1");
            return (Criteria) this;
        }

        public Criteria andJobnm1LessThanOrEqualTo(String value) {
            addCriterion("JOBNM1 <=", value, "jobnm1");
            return (Criteria) this;
        }

        public Criteria andJobnm1Like(String value) {
            addCriterion("JOBNM1 like", value, "jobnm1");
            return (Criteria) this;
        }

        public Criteria andJobnm1NotLike(String value) {
            addCriterion("JOBNM1 not like", value, "jobnm1");
            return (Criteria) this;
        }

        public Criteria andJobnm1In(List<String> values) {
            addCriterion("JOBNM1 in", values, "jobnm1");
            return (Criteria) this;
        }

        public Criteria andJobnm1NotIn(List<String> values) {
            addCriterion("JOBNM1 not in", values, "jobnm1");
            return (Criteria) this;
        }

        public Criteria andJobnm1Between(String value1, String value2) {
            addCriterion("JOBNM1 between", value1, value2, "jobnm1");
            return (Criteria) this;
        }

        public Criteria andJobnm1NotBetween(String value1, String value2) {
            addCriterion("JOBNM1 not between", value1, value2, "jobnm1");
            return (Criteria) this;
        }

        public Criteria andJobnm2IsNull() {
            addCriterion("JOBNM2 is null");
            return (Criteria) this;
        }

        public Criteria andJobnm2IsNotNull() {
            addCriterion("JOBNM2 is not null");
            return (Criteria) this;
        }

        public Criteria andJobnm2EqualTo(String value) {
            addCriterion("JOBNM2 =", value, "jobnm2");
            return (Criteria) this;
        }

        public Criteria andJobnm2NotEqualTo(String value) {
            addCriterion("JOBNM2 <>", value, "jobnm2");
            return (Criteria) this;
        }

        public Criteria andJobnm2GreaterThan(String value) {
            addCriterion("JOBNM2 >", value, "jobnm2");
            return (Criteria) this;
        }

        public Criteria andJobnm2GreaterThanOrEqualTo(String value) {
            addCriterion("JOBNM2 >=", value, "jobnm2");
            return (Criteria) this;
        }

        public Criteria andJobnm2LessThan(String value) {
            addCriterion("JOBNM2 <", value, "jobnm2");
            return (Criteria) this;
        }

        public Criteria andJobnm2LessThanOrEqualTo(String value) {
            addCriterion("JOBNM2 <=", value, "jobnm2");
            return (Criteria) this;
        }

        public Criteria andJobnm2Like(String value) {
            addCriterion("JOBNM2 like", value, "jobnm2");
            return (Criteria) this;
        }

        public Criteria andJobnm2NotLike(String value) {
            addCriterion("JOBNM2 not like", value, "jobnm2");
            return (Criteria) this;
        }

        public Criteria andJobnm2In(List<String> values) {
            addCriterion("JOBNM2 in", values, "jobnm2");
            return (Criteria) this;
        }

        public Criteria andJobnm2NotIn(List<String> values) {
            addCriterion("JOBNM2 not in", values, "jobnm2");
            return (Criteria) this;
        }

        public Criteria andJobnm2Between(String value1, String value2) {
            addCriterion("JOBNM2 between", value1, value2, "jobnm2");
            return (Criteria) this;
        }

        public Criteria andJobnm2NotBetween(String value1, String value2) {
            addCriterion("JOBNM2 not between", value1, value2, "jobnm2");
            return (Criteria) this;
        }

        public Criteria andAmdtlrIsNull() {
            addCriterion("AMDTLR is null");
            return (Criteria) this;
        }

        public Criteria andAmdtlrIsNotNull() {
            addCriterion("AMDTLR is not null");
            return (Criteria) this;
        }

        public Criteria andAmdtlrEqualTo(String value) {
            addCriterion("AMDTLR =", value, "amdtlr");
            return (Criteria) this;
        }

        public Criteria andAmdtlrNotEqualTo(String value) {
            addCriterion("AMDTLR <>", value, "amdtlr");
            return (Criteria) this;
        }

        public Criteria andAmdtlrGreaterThan(String value) {
            addCriterion("AMDTLR >", value, "amdtlr");
            return (Criteria) this;
        }

        public Criteria andAmdtlrGreaterThanOrEqualTo(String value) {
            addCriterion("AMDTLR >=", value, "amdtlr");
            return (Criteria) this;
        }

        public Criteria andAmdtlrLessThan(String value) {
            addCriterion("AMDTLR <", value, "amdtlr");
            return (Criteria) this;
        }

        public Criteria andAmdtlrLessThanOrEqualTo(String value) {
            addCriterion("AMDTLR <=", value, "amdtlr");
            return (Criteria) this;
        }

        public Criteria andAmdtlrLike(String value) {
            addCriterion("AMDTLR like", value, "amdtlr");
            return (Criteria) this;
        }

        public Criteria andAmdtlrNotLike(String value) {
            addCriterion("AMDTLR not like", value, "amdtlr");
            return (Criteria) this;
        }

        public Criteria andAmdtlrIn(List<String> values) {
            addCriterion("AMDTLR in", values, "amdtlr");
            return (Criteria) this;
        }

        public Criteria andAmdtlrNotIn(List<String> values) {
            addCriterion("AMDTLR not in", values, "amdtlr");
            return (Criteria) this;
        }

        public Criteria andAmdtlrBetween(String value1, String value2) {
            addCriterion("AMDTLR between", value1, value2, "amdtlr");
            return (Criteria) this;
        }

        public Criteria andAmdtlrNotBetween(String value1, String value2) {
            addCriterion("AMDTLR not between", value1, value2, "amdtlr");
            return (Criteria) this;
        }

        public Criteria andUpddatIsNull() {
            addCriterion("UPDDAT is null");
            return (Criteria) this;
        }

        public Criteria andUpddatIsNotNull() {
            addCriterion("UPDDAT is not null");
            return (Criteria) this;
        }

        public Criteria andUpddatEqualTo(Date value) {
            addCriterion("UPDDAT =", value, "upddat");
            return (Criteria) this;
        }

        public Criteria andUpddatNotEqualTo(Date value) {
            addCriterion("UPDDAT <>", value, "upddat");
            return (Criteria) this;
        }

        public Criteria andUpddatGreaterThan(Date value) {
            addCriterion("UPDDAT >", value, "upddat");
            return (Criteria) this;
        }

        public Criteria andUpddatGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDDAT >=", value, "upddat");
            return (Criteria) this;
        }

        public Criteria andUpddatLessThan(Date value) {
            addCriterion("UPDDAT <", value, "upddat");
            return (Criteria) this;
        }

        public Criteria andUpddatLessThanOrEqualTo(Date value) {
            addCriterion("UPDDAT <=", value, "upddat");
            return (Criteria) this;
        }

        public Criteria andUpddatIn(List<Date> values) {
            addCriterion("UPDDAT in", values, "upddat");
            return (Criteria) this;
        }

        public Criteria andUpddatNotIn(List<Date> values) {
            addCriterion("UPDDAT not in", values, "upddat");
            return (Criteria) this;
        }

        public Criteria andUpddatBetween(Date value1, Date value2) {
            addCriterion("UPDDAT between", value1, value2, "upddat");
            return (Criteria) this;
        }

        public Criteria andUpddatNotBetween(Date value1, Date value2) {
            addCriterion("UPDDAT not between", value1, value2, "upddat");
            return (Criteria) this;
        }

        public Criteria andRecstsIsNull() {
            addCriterion("RECSTS is null");
            return (Criteria) this;
        }

        public Criteria andRecstsIsNotNull() {
            addCriterion("RECSTS is not null");
            return (Criteria) this;
        }

        public Criteria andRecstsEqualTo(String value) {
            addCriterion("RECSTS =", value, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsNotEqualTo(String value) {
            addCriterion("RECSTS <>", value, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsGreaterThan(String value) {
            addCriterion("RECSTS >", value, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsGreaterThanOrEqualTo(String value) {
            addCriterion("RECSTS >=", value, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsLessThan(String value) {
            addCriterion("RECSTS <", value, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsLessThanOrEqualTo(String value) {
            addCriterion("RECSTS <=", value, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsLike(String value) {
            addCriterion("RECSTS like", value, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsNotLike(String value) {
            addCriterion("RECSTS not like", value, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsIn(List<String> values) {
            addCriterion("RECSTS in", values, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsNotIn(List<String> values) {
            addCriterion("RECSTS not in", values, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsBetween(String value1, String value2) {
            addCriterion("RECSTS between", value1, value2, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsNotBetween(String value1, String value2) {
            addCriterion("RECSTS not between", value1, value2, "recsts");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ACTCMT
     *
     * @mbggenerated do_not_delete_during_merge Tue Dec 28 17:17:15 CST 2010
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ACTCMT
     *
     * @mbggenerated Tue Dec 28 17:17:15 CST 2010
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}