package cbs.repository.account.maininfo.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ActoahExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ACTOAH
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ACTOAH
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ACTOAH
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTOAH
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public ActoahExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTOAH
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTOAH
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTOAH
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTOAH
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTOAH
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTOAH
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTOAH
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTOAH
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTOAH
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTOAH
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ACTOAH
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOrgidtIsNull() {
            addCriterion("ORGIDT is null");
            return (Criteria) this;
        }

        public Criteria andOrgidtIsNotNull() {
            addCriterion("ORGIDT is not null");
            return (Criteria) this;
        }

        public Criteria andOrgidtEqualTo(String value) {
            addCriterion("ORGIDT =", value, "orgidt");
            return (Criteria) this;
        }

        public Criteria andOrgidtNotEqualTo(String value) {
            addCriterion("ORGIDT <>", value, "orgidt");
            return (Criteria) this;
        }

        public Criteria andOrgidtGreaterThan(String value) {
            addCriterion("ORGIDT >", value, "orgidt");
            return (Criteria) this;
        }

        public Criteria andOrgidtGreaterThanOrEqualTo(String value) {
            addCriterion("ORGIDT >=", value, "orgidt");
            return (Criteria) this;
        }

        public Criteria andOrgidtLessThan(String value) {
            addCriterion("ORGIDT <", value, "orgidt");
            return (Criteria) this;
        }

        public Criteria andOrgidtLessThanOrEqualTo(String value) {
            addCriterion("ORGIDT <=", value, "orgidt");
            return (Criteria) this;
        }

        public Criteria andOrgidtLike(String value) {
            addCriterion("ORGIDT like", value, "orgidt");
            return (Criteria) this;
        }

        public Criteria andOrgidtNotLike(String value) {
            addCriterion("ORGIDT not like", value, "orgidt");
            return (Criteria) this;
        }

        public Criteria andOrgidtIn(List<String> values) {
            addCriterion("ORGIDT in", values, "orgidt");
            return (Criteria) this;
        }

        public Criteria andOrgidtNotIn(List<String> values) {
            addCriterion("ORGIDT not in", values, "orgidt");
            return (Criteria) this;
        }

        public Criteria andOrgidtBetween(String value1, String value2) {
            addCriterion("ORGIDT between", value1, value2, "orgidt");
            return (Criteria) this;
        }

        public Criteria andOrgidtNotBetween(String value1, String value2) {
            addCriterion("ORGIDT not between", value1, value2, "orgidt");
            return (Criteria) this;
        }

        public Criteria andCusidtIsNull() {
            addCriterion("CUSIDT is null");
            return (Criteria) this;
        }

        public Criteria andCusidtIsNotNull() {
            addCriterion("CUSIDT is not null");
            return (Criteria) this;
        }

        public Criteria andCusidtEqualTo(String value) {
            addCriterion("CUSIDT =", value, "cusidt");
            return (Criteria) this;
        }

        public Criteria andCusidtNotEqualTo(String value) {
            addCriterion("CUSIDT <>", value, "cusidt");
            return (Criteria) this;
        }

        public Criteria andCusidtGreaterThan(String value) {
            addCriterion("CUSIDT >", value, "cusidt");
            return (Criteria) this;
        }

        public Criteria andCusidtGreaterThanOrEqualTo(String value) {
            addCriterion("CUSIDT >=", value, "cusidt");
            return (Criteria) this;
        }

        public Criteria andCusidtLessThan(String value) {
            addCriterion("CUSIDT <", value, "cusidt");
            return (Criteria) this;
        }

        public Criteria andCusidtLessThanOrEqualTo(String value) {
            addCriterion("CUSIDT <=", value, "cusidt");
            return (Criteria) this;
        }

        public Criteria andCusidtLike(String value) {
            addCriterion("CUSIDT like", value, "cusidt");
            return (Criteria) this;
        }

        public Criteria andCusidtNotLike(String value) {
            addCriterion("CUSIDT not like", value, "cusidt");
            return (Criteria) this;
        }

        public Criteria andCusidtIn(List<String> values) {
            addCriterion("CUSIDT in", values, "cusidt");
            return (Criteria) this;
        }

        public Criteria andCusidtNotIn(List<String> values) {
            addCriterion("CUSIDT not in", values, "cusidt");
            return (Criteria) this;
        }

        public Criteria andCusidtBetween(String value1, String value2) {
            addCriterion("CUSIDT between", value1, value2, "cusidt");
            return (Criteria) this;
        }

        public Criteria andCusidtNotBetween(String value1, String value2) {
            addCriterion("CUSIDT not between", value1, value2, "cusidt");
            return (Criteria) this;
        }

        public Criteria andApcodeIsNull() {
            addCriterion("APCODE is null");
            return (Criteria) this;
        }

        public Criteria andApcodeIsNotNull() {
            addCriterion("APCODE is not null");
            return (Criteria) this;
        }

        public Criteria andApcodeEqualTo(String value) {
            addCriterion("APCODE =", value, "apcode");
            return (Criteria) this;
        }

        public Criteria andApcodeNotEqualTo(String value) {
            addCriterion("APCODE <>", value, "apcode");
            return (Criteria) this;
        }

        public Criteria andApcodeGreaterThan(String value) {
            addCriterion("APCODE >", value, "apcode");
            return (Criteria) this;
        }

        public Criteria andApcodeGreaterThanOrEqualTo(String value) {
            addCriterion("APCODE >=", value, "apcode");
            return (Criteria) this;
        }

        public Criteria andApcodeLessThan(String value) {
            addCriterion("APCODE <", value, "apcode");
            return (Criteria) this;
        }

        public Criteria andApcodeLessThanOrEqualTo(String value) {
            addCriterion("APCODE <=", value, "apcode");
            return (Criteria) this;
        }

        public Criteria andApcodeLike(String value) {
            addCriterion("APCODE like", value, "apcode");
            return (Criteria) this;
        }

        public Criteria andApcodeNotLike(String value) {
            addCriterion("APCODE not like", value, "apcode");
            return (Criteria) this;
        }

        public Criteria andApcodeIn(List<String> values) {
            addCriterion("APCODE in", values, "apcode");
            return (Criteria) this;
        }

        public Criteria andApcodeNotIn(List<String> values) {
            addCriterion("APCODE not in", values, "apcode");
            return (Criteria) this;
        }

        public Criteria andApcodeBetween(String value1, String value2) {
            addCriterion("APCODE between", value1, value2, "apcode");
            return (Criteria) this;
        }

        public Criteria andApcodeNotBetween(String value1, String value2) {
            addCriterion("APCODE not between", value1, value2, "apcode");
            return (Criteria) this;
        }

        public Criteria andCurcdeIsNull() {
            addCriterion("CURCDE is null");
            return (Criteria) this;
        }

        public Criteria andCurcdeIsNotNull() {
            addCriterion("CURCDE is not null");
            return (Criteria) this;
        }

        public Criteria andCurcdeEqualTo(String value) {
            addCriterion("CURCDE =", value, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeNotEqualTo(String value) {
            addCriterion("CURCDE <>", value, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeGreaterThan(String value) {
            addCriterion("CURCDE >", value, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeGreaterThanOrEqualTo(String value) {
            addCriterion("CURCDE >=", value, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeLessThan(String value) {
            addCriterion("CURCDE <", value, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeLessThanOrEqualTo(String value) {
            addCriterion("CURCDE <=", value, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeLike(String value) {
            addCriterion("CURCDE like", value, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeNotLike(String value) {
            addCriterion("CURCDE not like", value, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeIn(List<String> values) {
            addCriterion("CURCDE in", values, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeNotIn(List<String> values) {
            addCriterion("CURCDE not in", values, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeBetween(String value1, String value2) {
            addCriterion("CURCDE between", value1, value2, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeNotBetween(String value1, String value2) {
            addCriterion("CURCDE not between", value1, value2, "curcde");
            return (Criteria) this;
        }

        public Criteria andCredatIsNull() {
            addCriterion("CREDAT is null");
            return (Criteria) this;
        }

        public Criteria andCredatIsNotNull() {
            addCriterion("CREDAT is not null");
            return (Criteria) this;
        }

        public Criteria andCredatEqualTo(Date value) {
            addCriterion("CREDAT =", value, "credat");
            return (Criteria) this;
        }

        public Criteria andCredatNotEqualTo(Date value) {
            addCriterion("CREDAT <>", value, "credat");
            return (Criteria) this;
        }

        public Criteria andCredatGreaterThan(Date value) {
            addCriterion("CREDAT >", value, "credat");
            return (Criteria) this;
        }

        public Criteria andCredatGreaterThanOrEqualTo(Date value) {
            addCriterion("CREDAT >=", value, "credat");
            return (Criteria) this;
        }

        public Criteria andCredatLessThan(Date value) {
            addCriterion("CREDAT <", value, "credat");
            return (Criteria) this;
        }

        public Criteria andCredatLessThanOrEqualTo(Date value) {
            addCriterion("CREDAT <=", value, "credat");
            return (Criteria) this;
        }

        public Criteria andCredatIn(List<Date> values) {
            addCriterion("CREDAT in", values, "credat");
            return (Criteria) this;
        }

        public Criteria andCredatNotIn(List<Date> values) {
            addCriterion("CREDAT not in", values, "credat");
            return (Criteria) this;
        }

        public Criteria andCredatBetween(Date value1, Date value2) {
            addCriterion("CREDAT between", value1, value2, "credat");
            return (Criteria) this;
        }

        public Criteria andCredatNotBetween(Date value1, Date value2) {
            addCriterion("CREDAT not between", value1, value2, "credat");
            return (Criteria) this;
        }

        public Criteria andCretimIsNull() {
            addCriterion("CRETIM is null");
            return (Criteria) this;
        }

        public Criteria andCretimIsNotNull() {
            addCriterion("CRETIM is not null");
            return (Criteria) this;
        }

        public Criteria andCretimEqualTo(String value) {
            addCriterion("CRETIM =", value, "cretim");
            return (Criteria) this;
        }

        public Criteria andCretimNotEqualTo(String value) {
            addCriterion("CRETIM <>", value, "cretim");
            return (Criteria) this;
        }

        public Criteria andCretimGreaterThan(String value) {
            addCriterion("CRETIM >", value, "cretim");
            return (Criteria) this;
        }

        public Criteria andCretimGreaterThanOrEqualTo(String value) {
            addCriterion("CRETIM >=", value, "cretim");
            return (Criteria) this;
        }

        public Criteria andCretimLessThan(String value) {
            addCriterion("CRETIM <", value, "cretim");
            return (Criteria) this;
        }

        public Criteria andCretimLessThanOrEqualTo(String value) {
            addCriterion("CRETIM <=", value, "cretim");
            return (Criteria) this;
        }

        public Criteria andCretimLike(String value) {
            addCriterion("CRETIM like", value, "cretim");
            return (Criteria) this;
        }

        public Criteria andCretimNotLike(String value) {
            addCriterion("CRETIM not like", value, "cretim");
            return (Criteria) this;
        }

        public Criteria andCretimIn(List<String> values) {
            addCriterion("CRETIM in", values, "cretim");
            return (Criteria) this;
        }

        public Criteria andCretimNotIn(List<String> values) {
            addCriterion("CRETIM not in", values, "cretim");
            return (Criteria) this;
        }

        public Criteria andCretimBetween(String value1, String value2) {
            addCriterion("CRETIM between", value1, value2, "cretim");
            return (Criteria) this;
        }

        public Criteria andCretimNotBetween(String value1, String value2) {
            addCriterion("CRETIM not between", value1, value2, "cretim");
            return (Criteria) this;
        }

        public Criteria andOacflgIsNull() {
            addCriterion("OACFLG is null");
            return (Criteria) this;
        }

        public Criteria andOacflgIsNotNull() {
            addCriterion("OACFLG is not null");
            return (Criteria) this;
        }

        public Criteria andOacflgEqualTo(String value) {
            addCriterion("OACFLG =", value, "oacflg");
            return (Criteria) this;
        }

        public Criteria andOacflgNotEqualTo(String value) {
            addCriterion("OACFLG <>", value, "oacflg");
            return (Criteria) this;
        }

        public Criteria andOacflgGreaterThan(String value) {
            addCriterion("OACFLG >", value, "oacflg");
            return (Criteria) this;
        }

        public Criteria andOacflgGreaterThanOrEqualTo(String value) {
            addCriterion("OACFLG >=", value, "oacflg");
            return (Criteria) this;
        }

        public Criteria andOacflgLessThan(String value) {
            addCriterion("OACFLG <", value, "oacflg");
            return (Criteria) this;
        }

        public Criteria andOacflgLessThanOrEqualTo(String value) {
            addCriterion("OACFLG <=", value, "oacflg");
            return (Criteria) this;
        }

        public Criteria andOacflgLike(String value) {
            addCriterion("OACFLG like", value, "oacflg");
            return (Criteria) this;
        }

        public Criteria andOacflgNotLike(String value) {
            addCriterion("OACFLG not like", value, "oacflg");
            return (Criteria) this;
        }

        public Criteria andOacflgIn(List<String> values) {
            addCriterion("OACFLG in", values, "oacflg");
            return (Criteria) this;
        }

        public Criteria andOacflgNotIn(List<String> values) {
            addCriterion("OACFLG not in", values, "oacflg");
            return (Criteria) this;
        }

        public Criteria andOacflgBetween(String value1, String value2) {
            addCriterion("OACFLG between", value1, value2, "oacflg");
            return (Criteria) this;
        }

        public Criteria andOacflgNotBetween(String value1, String value2) {
            addCriterion("OACFLG not between", value1, value2, "oacflg");
            return (Criteria) this;
        }

        public Criteria andActnamIsNull() {
            addCriterion("ACTNAM is null");
            return (Criteria) this;
        }

        public Criteria andActnamIsNotNull() {
            addCriterion("ACTNAM is not null");
            return (Criteria) this;
        }

        public Criteria andActnamEqualTo(String value) {
            addCriterion("ACTNAM =", value, "actnam");
            return (Criteria) this;
        }

        public Criteria andActnamNotEqualTo(String value) {
            addCriterion("ACTNAM <>", value, "actnam");
            return (Criteria) this;
        }

        public Criteria andActnamGreaterThan(String value) {
            addCriterion("ACTNAM >", value, "actnam");
            return (Criteria) this;
        }

        public Criteria andActnamGreaterThanOrEqualTo(String value) {
            addCriterion("ACTNAM >=", value, "actnam");
            return (Criteria) this;
        }

        public Criteria andActnamLessThan(String value) {
            addCriterion("ACTNAM <", value, "actnam");
            return (Criteria) this;
        }

        public Criteria andActnamLessThanOrEqualTo(String value) {
            addCriterion("ACTNAM <=", value, "actnam");
            return (Criteria) this;
        }

        public Criteria andActnamLike(String value) {
            addCriterion("ACTNAM like", value, "actnam");
            return (Criteria) this;
        }

        public Criteria andActnamNotLike(String value) {
            addCriterion("ACTNAM not like", value, "actnam");
            return (Criteria) this;
        }

        public Criteria andActnamIn(List<String> values) {
            addCriterion("ACTNAM in", values, "actnam");
            return (Criteria) this;
        }

        public Criteria andActnamNotIn(List<String> values) {
            addCriterion("ACTNAM not in", values, "actnam");
            return (Criteria) this;
        }

        public Criteria andActnamBetween(String value1, String value2) {
            addCriterion("ACTNAM between", value1, value2, "actnam");
            return (Criteria) this;
        }

        public Criteria andActnamNotBetween(String value1, String value2) {
            addCriterion("ACTNAM not between", value1, value2, "actnam");
            return (Criteria) this;
        }

        public Criteria andDinratIsNull() {
            addCriterion("DINRAT is null");
            return (Criteria) this;
        }

        public Criteria andDinratIsNotNull() {
            addCriterion("DINRAT is not null");
            return (Criteria) this;
        }

        public Criteria andDinratEqualTo(String value) {
            addCriterion("DINRAT =", value, "dinrat");
            return (Criteria) this;
        }

        public Criteria andDinratNotEqualTo(String value) {
            addCriterion("DINRAT <>", value, "dinrat");
            return (Criteria) this;
        }

        public Criteria andDinratGreaterThan(String value) {
            addCriterion("DINRAT >", value, "dinrat");
            return (Criteria) this;
        }

        public Criteria andDinratGreaterThanOrEqualTo(String value) {
            addCriterion("DINRAT >=", value, "dinrat");
            return (Criteria) this;
        }

        public Criteria andDinratLessThan(String value) {
            addCriterion("DINRAT <", value, "dinrat");
            return (Criteria) this;
        }

        public Criteria andDinratLessThanOrEqualTo(String value) {
            addCriterion("DINRAT <=", value, "dinrat");
            return (Criteria) this;
        }

        public Criteria andDinratLike(String value) {
            addCriterion("DINRAT like", value, "dinrat");
            return (Criteria) this;
        }

        public Criteria andDinratNotLike(String value) {
            addCriterion("DINRAT not like", value, "dinrat");
            return (Criteria) this;
        }

        public Criteria andDinratIn(List<String> values) {
            addCriterion("DINRAT in", values, "dinrat");
            return (Criteria) this;
        }

        public Criteria andDinratNotIn(List<String> values) {
            addCriterion("DINRAT not in", values, "dinrat");
            return (Criteria) this;
        }

        public Criteria andDinratBetween(String value1, String value2) {
            addCriterion("DINRAT between", value1, value2, "dinrat");
            return (Criteria) this;
        }

        public Criteria andDinratNotBetween(String value1, String value2) {
            addCriterion("DINRAT not between", value1, value2, "dinrat");
            return (Criteria) this;
        }

        public Criteria andCinratIsNull() {
            addCriterion("CINRAT is null");
            return (Criteria) this;
        }

        public Criteria andCinratIsNotNull() {
            addCriterion("CINRAT is not null");
            return (Criteria) this;
        }

        public Criteria andCinratEqualTo(String value) {
            addCriterion("CINRAT =", value, "cinrat");
            return (Criteria) this;
        }

        public Criteria andCinratNotEqualTo(String value) {
            addCriterion("CINRAT <>", value, "cinrat");
            return (Criteria) this;
        }

        public Criteria andCinratGreaterThan(String value) {
            addCriterion("CINRAT >", value, "cinrat");
            return (Criteria) this;
        }

        public Criteria andCinratGreaterThanOrEqualTo(String value) {
            addCriterion("CINRAT >=", value, "cinrat");
            return (Criteria) this;
        }

        public Criteria andCinratLessThan(String value) {
            addCriterion("CINRAT <", value, "cinrat");
            return (Criteria) this;
        }

        public Criteria andCinratLessThanOrEqualTo(String value) {
            addCriterion("CINRAT <=", value, "cinrat");
            return (Criteria) this;
        }

        public Criteria andCinratLike(String value) {
            addCriterion("CINRAT like", value, "cinrat");
            return (Criteria) this;
        }

        public Criteria andCinratNotLike(String value) {
            addCriterion("CINRAT not like", value, "cinrat");
            return (Criteria) this;
        }

        public Criteria andCinratIn(List<String> values) {
            addCriterion("CINRAT in", values, "cinrat");
            return (Criteria) this;
        }

        public Criteria andCinratNotIn(List<String> values) {
            addCriterion("CINRAT not in", values, "cinrat");
            return (Criteria) this;
        }

        public Criteria andCinratBetween(String value1, String value2) {
            addCriterion("CINRAT between", value1, value2, "cinrat");
            return (Criteria) this;
        }

        public Criteria andCinratNotBetween(String value1, String value2) {
            addCriterion("CINRAT not between", value1, value2, "cinrat");
            return (Criteria) this;
        }

        public Criteria andDratsfIsNull() {
            addCriterion("DRATSF is null");
            return (Criteria) this;
        }

        public Criteria andDratsfIsNotNull() {
            addCriterion("DRATSF is not null");
            return (Criteria) this;
        }

        public Criteria andDratsfEqualTo(BigDecimal value) {
            addCriterion("DRATSF =", value, "dratsf");
            return (Criteria) this;
        }

        public Criteria andDratsfNotEqualTo(BigDecimal value) {
            addCriterion("DRATSF <>", value, "dratsf");
            return (Criteria) this;
        }

        public Criteria andDratsfGreaterThan(BigDecimal value) {
            addCriterion("DRATSF >", value, "dratsf");
            return (Criteria) this;
        }

        public Criteria andDratsfGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("DRATSF >=", value, "dratsf");
            return (Criteria) this;
        }

        public Criteria andDratsfLessThan(BigDecimal value) {
            addCriterion("DRATSF <", value, "dratsf");
            return (Criteria) this;
        }

        public Criteria andDratsfLessThanOrEqualTo(BigDecimal value) {
            addCriterion("DRATSF <=", value, "dratsf");
            return (Criteria) this;
        }

        public Criteria andDratsfIn(List<BigDecimal> values) {
            addCriterion("DRATSF in", values, "dratsf");
            return (Criteria) this;
        }

        public Criteria andDratsfNotIn(List<BigDecimal> values) {
            addCriterion("DRATSF not in", values, "dratsf");
            return (Criteria) this;
        }

        public Criteria andDratsfBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DRATSF between", value1, value2, "dratsf");
            return (Criteria) this;
        }

        public Criteria andDratsfNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DRATSF not between", value1, value2, "dratsf");
            return (Criteria) this;
        }

        public Criteria andCratsfIsNull() {
            addCriterion("CRATSF is null");
            return (Criteria) this;
        }

        public Criteria andCratsfIsNotNull() {
            addCriterion("CRATSF is not null");
            return (Criteria) this;
        }

        public Criteria andCratsfEqualTo(BigDecimal value) {
            addCriterion("CRATSF =", value, "cratsf");
            return (Criteria) this;
        }

        public Criteria andCratsfNotEqualTo(BigDecimal value) {
            addCriterion("CRATSF <>", value, "cratsf");
            return (Criteria) this;
        }

        public Criteria andCratsfGreaterThan(BigDecimal value) {
            addCriterion("CRATSF >", value, "cratsf");
            return (Criteria) this;
        }

        public Criteria andCratsfGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CRATSF >=", value, "cratsf");
            return (Criteria) this;
        }

        public Criteria andCratsfLessThan(BigDecimal value) {
            addCriterion("CRATSF <", value, "cratsf");
            return (Criteria) this;
        }

        public Criteria andCratsfLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CRATSF <=", value, "cratsf");
            return (Criteria) this;
        }

        public Criteria andCratsfIn(List<BigDecimal> values) {
            addCriterion("CRATSF in", values, "cratsf");
            return (Criteria) this;
        }

        public Criteria andCratsfNotIn(List<BigDecimal> values) {
            addCriterion("CRATSF not in", values, "cratsf");
            return (Criteria) this;
        }

        public Criteria andCratsfBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CRATSF between", value1, value2, "cratsf");
            return (Criteria) this;
        }

        public Criteria andCratsfNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CRATSF not between", value1, value2, "cratsf");
            return (Criteria) this;
        }

        public Criteria andIntflgIsNull() {
            addCriterion("INTFLG is null");
            return (Criteria) this;
        }

        public Criteria andIntflgIsNotNull() {
            addCriterion("INTFLG is not null");
            return (Criteria) this;
        }

        public Criteria andIntflgEqualTo(String value) {
            addCriterion("INTFLG =", value, "intflg");
            return (Criteria) this;
        }

        public Criteria andIntflgNotEqualTo(String value) {
            addCriterion("INTFLG <>", value, "intflg");
            return (Criteria) this;
        }

        public Criteria andIntflgGreaterThan(String value) {
            addCriterion("INTFLG >", value, "intflg");
            return (Criteria) this;
        }

        public Criteria andIntflgGreaterThanOrEqualTo(String value) {
            addCriterion("INTFLG >=", value, "intflg");
            return (Criteria) this;
        }

        public Criteria andIntflgLessThan(String value) {
            addCriterion("INTFLG <", value, "intflg");
            return (Criteria) this;
        }

        public Criteria andIntflgLessThanOrEqualTo(String value) {
            addCriterion("INTFLG <=", value, "intflg");
            return (Criteria) this;
        }

        public Criteria andIntflgLike(String value) {
            addCriterion("INTFLG like", value, "intflg");
            return (Criteria) this;
        }

        public Criteria andIntflgNotLike(String value) {
            addCriterion("INTFLG not like", value, "intflg");
            return (Criteria) this;
        }

        public Criteria andIntflgIn(List<String> values) {
            addCriterion("INTFLG in", values, "intflg");
            return (Criteria) this;
        }

        public Criteria andIntflgNotIn(List<String> values) {
            addCriterion("INTFLG not in", values, "intflg");
            return (Criteria) this;
        }

        public Criteria andIntflgBetween(String value1, String value2) {
            addCriterion("INTFLG between", value1, value2, "intflg");
            return (Criteria) this;
        }

        public Criteria andIntflgNotBetween(String value1, String value2) {
            addCriterion("INTFLG not between", value1, value2, "intflg");
            return (Criteria) this;
        }

        public Criteria andIntcycIsNull() {
            addCriterion("INTCYC is null");
            return (Criteria) this;
        }

        public Criteria andIntcycIsNotNull() {
            addCriterion("INTCYC is not null");
            return (Criteria) this;
        }

        public Criteria andIntcycEqualTo(String value) {
            addCriterion("INTCYC =", value, "intcyc");
            return (Criteria) this;
        }

        public Criteria andIntcycNotEqualTo(String value) {
            addCriterion("INTCYC <>", value, "intcyc");
            return (Criteria) this;
        }

        public Criteria andIntcycGreaterThan(String value) {
            addCriterion("INTCYC >", value, "intcyc");
            return (Criteria) this;
        }

        public Criteria andIntcycGreaterThanOrEqualTo(String value) {
            addCriterion("INTCYC >=", value, "intcyc");
            return (Criteria) this;
        }

        public Criteria andIntcycLessThan(String value) {
            addCriterion("INTCYC <", value, "intcyc");
            return (Criteria) this;
        }

        public Criteria andIntcycLessThanOrEqualTo(String value) {
            addCriterion("INTCYC <=", value, "intcyc");
            return (Criteria) this;
        }

        public Criteria andIntcycLike(String value) {
            addCriterion("INTCYC like", value, "intcyc");
            return (Criteria) this;
        }

        public Criteria andIntcycNotLike(String value) {
            addCriterion("INTCYC not like", value, "intcyc");
            return (Criteria) this;
        }

        public Criteria andIntcycIn(List<String> values) {
            addCriterion("INTCYC in", values, "intcyc");
            return (Criteria) this;
        }

        public Criteria andIntcycNotIn(List<String> values) {
            addCriterion("INTCYC not in", values, "intcyc");
            return (Criteria) this;
        }

        public Criteria andIntcycBetween(String value1, String value2) {
            addCriterion("INTCYC between", value1, value2, "intcyc");
            return (Criteria) this;
        }

        public Criteria andIntcycNotBetween(String value1, String value2) {
            addCriterion("INTCYC not between", value1, value2, "intcyc");
            return (Criteria) this;
        }

        public Criteria andInttraIsNull() {
            addCriterion("INTTRA is null");
            return (Criteria) this;
        }

        public Criteria andInttraIsNotNull() {
            addCriterion("INTTRA is not null");
            return (Criteria) this;
        }

        public Criteria andInttraEqualTo(String value) {
            addCriterion("INTTRA =", value, "inttra");
            return (Criteria) this;
        }

        public Criteria andInttraNotEqualTo(String value) {
            addCriterion("INTTRA <>", value, "inttra");
            return (Criteria) this;
        }

        public Criteria andInttraGreaterThan(String value) {
            addCriterion("INTTRA >", value, "inttra");
            return (Criteria) this;
        }

        public Criteria andInttraGreaterThanOrEqualTo(String value) {
            addCriterion("INTTRA >=", value, "inttra");
            return (Criteria) this;
        }

        public Criteria andInttraLessThan(String value) {
            addCriterion("INTTRA <", value, "inttra");
            return (Criteria) this;
        }

        public Criteria andInttraLessThanOrEqualTo(String value) {
            addCriterion("INTTRA <=", value, "inttra");
            return (Criteria) this;
        }

        public Criteria andInttraLike(String value) {
            addCriterion("INTTRA like", value, "inttra");
            return (Criteria) this;
        }

        public Criteria andInttraNotLike(String value) {
            addCriterion("INTTRA not like", value, "inttra");
            return (Criteria) this;
        }

        public Criteria andInttraIn(List<String> values) {
            addCriterion("INTTRA in", values, "inttra");
            return (Criteria) this;
        }

        public Criteria andInttraNotIn(List<String> values) {
            addCriterion("INTTRA not in", values, "inttra");
            return (Criteria) this;
        }

        public Criteria andInttraBetween(String value1, String value2) {
            addCriterion("INTTRA between", value1, value2, "inttra");
            return (Criteria) this;
        }

        public Criteria andInttraNotBetween(String value1, String value2) {
            addCriterion("INTTRA not between", value1, value2, "inttra");
            return (Criteria) this;
        }

        public Criteria andStmcycIsNull() {
            addCriterion("STMCYC is null");
            return (Criteria) this;
        }

        public Criteria andStmcycIsNotNull() {
            addCriterion("STMCYC is not null");
            return (Criteria) this;
        }

        public Criteria andStmcycEqualTo(String value) {
            addCriterion("STMCYC =", value, "stmcyc");
            return (Criteria) this;
        }

        public Criteria andStmcycNotEqualTo(String value) {
            addCriterion("STMCYC <>", value, "stmcyc");
            return (Criteria) this;
        }

        public Criteria andStmcycGreaterThan(String value) {
            addCriterion("STMCYC >", value, "stmcyc");
            return (Criteria) this;
        }

        public Criteria andStmcycGreaterThanOrEqualTo(String value) {
            addCriterion("STMCYC >=", value, "stmcyc");
            return (Criteria) this;
        }

        public Criteria andStmcycLessThan(String value) {
            addCriterion("STMCYC <", value, "stmcyc");
            return (Criteria) this;
        }

        public Criteria andStmcycLessThanOrEqualTo(String value) {
            addCriterion("STMCYC <=", value, "stmcyc");
            return (Criteria) this;
        }

        public Criteria andStmcycLike(String value) {
            addCriterion("STMCYC like", value, "stmcyc");
            return (Criteria) this;
        }

        public Criteria andStmcycNotLike(String value) {
            addCriterion("STMCYC not like", value, "stmcyc");
            return (Criteria) this;
        }

        public Criteria andStmcycIn(List<String> values) {
            addCriterion("STMCYC in", values, "stmcyc");
            return (Criteria) this;
        }

        public Criteria andStmcycNotIn(List<String> values) {
            addCriterion("STMCYC not in", values, "stmcyc");
            return (Criteria) this;
        }

        public Criteria andStmcycBetween(String value1, String value2) {
            addCriterion("STMCYC between", value1, value2, "stmcyc");
            return (Criteria) this;
        }

        public Criteria andStmcycNotBetween(String value1, String value2) {
            addCriterion("STMCYC not between", value1, value2, "stmcyc");
            return (Criteria) this;
        }

        public Criteria andStmcdtIsNull() {
            addCriterion("STMCDT is null");
            return (Criteria) this;
        }

        public Criteria andStmcdtIsNotNull() {
            addCriterion("STMCDT is not null");
            return (Criteria) this;
        }

        public Criteria andStmcdtEqualTo(String value) {
            addCriterion("STMCDT =", value, "stmcdt");
            return (Criteria) this;
        }

        public Criteria andStmcdtNotEqualTo(String value) {
            addCriterion("STMCDT <>", value, "stmcdt");
            return (Criteria) this;
        }

        public Criteria andStmcdtGreaterThan(String value) {
            addCriterion("STMCDT >", value, "stmcdt");
            return (Criteria) this;
        }

        public Criteria andStmcdtGreaterThanOrEqualTo(String value) {
            addCriterion("STMCDT >=", value, "stmcdt");
            return (Criteria) this;
        }

        public Criteria andStmcdtLessThan(String value) {
            addCriterion("STMCDT <", value, "stmcdt");
            return (Criteria) this;
        }

        public Criteria andStmcdtLessThanOrEqualTo(String value) {
            addCriterion("STMCDT <=", value, "stmcdt");
            return (Criteria) this;
        }

        public Criteria andStmcdtLike(String value) {
            addCriterion("STMCDT like", value, "stmcdt");
            return (Criteria) this;
        }

        public Criteria andStmcdtNotLike(String value) {
            addCriterion("STMCDT not like", value, "stmcdt");
            return (Criteria) this;
        }

        public Criteria andStmcdtIn(List<String> values) {
            addCriterion("STMCDT in", values, "stmcdt");
            return (Criteria) this;
        }

        public Criteria andStmcdtNotIn(List<String> values) {
            addCriterion("STMCDT not in", values, "stmcdt");
            return (Criteria) this;
        }

        public Criteria andStmcdtBetween(String value1, String value2) {
            addCriterion("STMCDT between", value1, value2, "stmcdt");
            return (Criteria) this;
        }

        public Criteria andStmcdtNotBetween(String value1, String value2) {
            addCriterion("STMCDT not between", value1, value2, "stmcdt");
            return (Criteria) this;
        }

        public Criteria andStmfmtIsNull() {
            addCriterion("STMFMT is null");
            return (Criteria) this;
        }

        public Criteria andStmfmtIsNotNull() {
            addCriterion("STMFMT is not null");
            return (Criteria) this;
        }

        public Criteria andStmfmtEqualTo(String value) {
            addCriterion("STMFMT =", value, "stmfmt");
            return (Criteria) this;
        }

        public Criteria andStmfmtNotEqualTo(String value) {
            addCriterion("STMFMT <>", value, "stmfmt");
            return (Criteria) this;
        }

        public Criteria andStmfmtGreaterThan(String value) {
            addCriterion("STMFMT >", value, "stmfmt");
            return (Criteria) this;
        }

        public Criteria andStmfmtGreaterThanOrEqualTo(String value) {
            addCriterion("STMFMT >=", value, "stmfmt");
            return (Criteria) this;
        }

        public Criteria andStmfmtLessThan(String value) {
            addCriterion("STMFMT <", value, "stmfmt");
            return (Criteria) this;
        }

        public Criteria andStmfmtLessThanOrEqualTo(String value) {
            addCriterion("STMFMT <=", value, "stmfmt");
            return (Criteria) this;
        }

        public Criteria andStmfmtLike(String value) {
            addCriterion("STMFMT like", value, "stmfmt");
            return (Criteria) this;
        }

        public Criteria andStmfmtNotLike(String value) {
            addCriterion("STMFMT not like", value, "stmfmt");
            return (Criteria) this;
        }

        public Criteria andStmfmtIn(List<String> values) {
            addCriterion("STMFMT in", values, "stmfmt");
            return (Criteria) this;
        }

        public Criteria andStmfmtNotIn(List<String> values) {
            addCriterion("STMFMT not in", values, "stmfmt");
            return (Criteria) this;
        }

        public Criteria andStmfmtBetween(String value1, String value2) {
            addCriterion("STMFMT between", value1, value2, "stmfmt");
            return (Criteria) this;
        }

        public Criteria andStmfmtNotBetween(String value1, String value2) {
            addCriterion("STMFMT not between", value1, value2, "stmfmt");
            return (Criteria) this;
        }

        public Criteria andStmaddIsNull() {
            addCriterion("STMADD is null");
            return (Criteria) this;
        }

        public Criteria andStmaddIsNotNull() {
            addCriterion("STMADD is not null");
            return (Criteria) this;
        }

        public Criteria andStmaddEqualTo(String value) {
            addCriterion("STMADD =", value, "stmadd");
            return (Criteria) this;
        }

        public Criteria andStmaddNotEqualTo(String value) {
            addCriterion("STMADD <>", value, "stmadd");
            return (Criteria) this;
        }

        public Criteria andStmaddGreaterThan(String value) {
            addCriterion("STMADD >", value, "stmadd");
            return (Criteria) this;
        }

        public Criteria andStmaddGreaterThanOrEqualTo(String value) {
            addCriterion("STMADD >=", value, "stmadd");
            return (Criteria) this;
        }

        public Criteria andStmaddLessThan(String value) {
            addCriterion("STMADD <", value, "stmadd");
            return (Criteria) this;
        }

        public Criteria andStmaddLessThanOrEqualTo(String value) {
            addCriterion("STMADD <=", value, "stmadd");
            return (Criteria) this;
        }

        public Criteria andStmaddLike(String value) {
            addCriterion("STMADD like", value, "stmadd");
            return (Criteria) this;
        }

        public Criteria andStmaddNotLike(String value) {
            addCriterion("STMADD not like", value, "stmadd");
            return (Criteria) this;
        }

        public Criteria andStmaddIn(List<String> values) {
            addCriterion("STMADD in", values, "stmadd");
            return (Criteria) this;
        }

        public Criteria andStmaddNotIn(List<String> values) {
            addCriterion("STMADD not in", values, "stmadd");
            return (Criteria) this;
        }

        public Criteria andStmaddBetween(String value1, String value2) {
            addCriterion("STMADD between", value1, value2, "stmadd");
            return (Criteria) this;
        }

        public Criteria andStmaddNotBetween(String value1, String value2) {
            addCriterion("STMADD not between", value1, value2, "stmadd");
            return (Criteria) this;
        }

        public Criteria andStmzipIsNull() {
            addCriterion("STMZIP is null");
            return (Criteria) this;
        }

        public Criteria andStmzipIsNotNull() {
            addCriterion("STMZIP is not null");
            return (Criteria) this;
        }

        public Criteria andStmzipEqualTo(String value) {
            addCriterion("STMZIP =", value, "stmzip");
            return (Criteria) this;
        }

        public Criteria andStmzipNotEqualTo(String value) {
            addCriterion("STMZIP <>", value, "stmzip");
            return (Criteria) this;
        }

        public Criteria andStmzipGreaterThan(String value) {
            addCriterion("STMZIP >", value, "stmzip");
            return (Criteria) this;
        }

        public Criteria andStmzipGreaterThanOrEqualTo(String value) {
            addCriterion("STMZIP >=", value, "stmzip");
            return (Criteria) this;
        }

        public Criteria andStmzipLessThan(String value) {
            addCriterion("STMZIP <", value, "stmzip");
            return (Criteria) this;
        }

        public Criteria andStmzipLessThanOrEqualTo(String value) {
            addCriterion("STMZIP <=", value, "stmzip");
            return (Criteria) this;
        }

        public Criteria andStmzipLike(String value) {
            addCriterion("STMZIP like", value, "stmzip");
            return (Criteria) this;
        }

        public Criteria andStmzipNotLike(String value) {
            addCriterion("STMZIP not like", value, "stmzip");
            return (Criteria) this;
        }

        public Criteria andStmzipIn(List<String> values) {
            addCriterion("STMZIP in", values, "stmzip");
            return (Criteria) this;
        }

        public Criteria andStmzipNotIn(List<String> values) {
            addCriterion("STMZIP not in", values, "stmzip");
            return (Criteria) this;
        }

        public Criteria andStmzipBetween(String value1, String value2) {
            addCriterion("STMZIP between", value1, value2, "stmzip");
            return (Criteria) this;
        }

        public Criteria andStmzipNotBetween(String value1, String value2) {
            addCriterion("STMZIP not between", value1, value2, "stmzip");
            return (Criteria) this;
        }

        public Criteria andStmshtIsNull() {
            addCriterion("STMSHT is null");
            return (Criteria) this;
        }

        public Criteria andStmshtIsNotNull() {
            addCriterion("STMSHT is not null");
            return (Criteria) this;
        }

        public Criteria andStmshtEqualTo(Short value) {
            addCriterion("STMSHT =", value, "stmsht");
            return (Criteria) this;
        }

        public Criteria andStmshtNotEqualTo(Short value) {
            addCriterion("STMSHT <>", value, "stmsht");
            return (Criteria) this;
        }

        public Criteria andStmshtGreaterThan(Short value) {
            addCriterion("STMSHT >", value, "stmsht");
            return (Criteria) this;
        }

        public Criteria andStmshtGreaterThanOrEqualTo(Short value) {
            addCriterion("STMSHT >=", value, "stmsht");
            return (Criteria) this;
        }

        public Criteria andStmshtLessThan(Short value) {
            addCriterion("STMSHT <", value, "stmsht");
            return (Criteria) this;
        }

        public Criteria andStmshtLessThanOrEqualTo(Short value) {
            addCriterion("STMSHT <=", value, "stmsht");
            return (Criteria) this;
        }

        public Criteria andStmshtIn(List<Short> values) {
            addCriterion("STMSHT in", values, "stmsht");
            return (Criteria) this;
        }

        public Criteria andStmshtNotIn(List<Short> values) {
            addCriterion("STMSHT not in", values, "stmsht");
            return (Criteria) this;
        }

        public Criteria andStmshtBetween(Short value1, Short value2) {
            addCriterion("STMSHT between", value1, value2, "stmsht");
            return (Criteria) this;
        }

        public Criteria andStmshtNotBetween(Short value1, Short value2) {
            addCriterion("STMSHT not between", value1, value2, "stmsht");
            return (Criteria) this;
        }

        public Criteria andStmdepIsNull() {
            addCriterion("STMDEP is null");
            return (Criteria) this;
        }

        public Criteria andStmdepIsNotNull() {
            addCriterion("STMDEP is not null");
            return (Criteria) this;
        }

        public Criteria andStmdepEqualTo(String value) {
            addCriterion("STMDEP =", value, "stmdep");
            return (Criteria) this;
        }

        public Criteria andStmdepNotEqualTo(String value) {
            addCriterion("STMDEP <>", value, "stmdep");
            return (Criteria) this;
        }

        public Criteria andStmdepGreaterThan(String value) {
            addCriterion("STMDEP >", value, "stmdep");
            return (Criteria) this;
        }

        public Criteria andStmdepGreaterThanOrEqualTo(String value) {
            addCriterion("STMDEP >=", value, "stmdep");
            return (Criteria) this;
        }

        public Criteria andStmdepLessThan(String value) {
            addCriterion("STMDEP <", value, "stmdep");
            return (Criteria) this;
        }

        public Criteria andStmdepLessThanOrEqualTo(String value) {
            addCriterion("STMDEP <=", value, "stmdep");
            return (Criteria) this;
        }

        public Criteria andStmdepLike(String value) {
            addCriterion("STMDEP like", value, "stmdep");
            return (Criteria) this;
        }

        public Criteria andStmdepNotLike(String value) {
            addCriterion("STMDEP not like", value, "stmdep");
            return (Criteria) this;
        }

        public Criteria andStmdepIn(List<String> values) {
            addCriterion("STMDEP in", values, "stmdep");
            return (Criteria) this;
        }

        public Criteria andStmdepNotIn(List<String> values) {
            addCriterion("STMDEP not in", values, "stmdep");
            return (Criteria) this;
        }

        public Criteria andStmdepBetween(String value1, String value2) {
            addCriterion("STMDEP between", value1, value2, "stmdep");
            return (Criteria) this;
        }

        public Criteria andStmdepNotBetween(String value1, String value2) {
            addCriterion("STMDEP not between", value1, value2, "stmdep");
            return (Criteria) this;
        }

        public Criteria andLegcycIsNull() {
            addCriterion("LEGCYC is null");
            return (Criteria) this;
        }

        public Criteria andLegcycIsNotNull() {
            addCriterion("LEGCYC is not null");
            return (Criteria) this;
        }

        public Criteria andLegcycEqualTo(String value) {
            addCriterion("LEGCYC =", value, "legcyc");
            return (Criteria) this;
        }

        public Criteria andLegcycNotEqualTo(String value) {
            addCriterion("LEGCYC <>", value, "legcyc");
            return (Criteria) this;
        }

        public Criteria andLegcycGreaterThan(String value) {
            addCriterion("LEGCYC >", value, "legcyc");
            return (Criteria) this;
        }

        public Criteria andLegcycGreaterThanOrEqualTo(String value) {
            addCriterion("LEGCYC >=", value, "legcyc");
            return (Criteria) this;
        }

        public Criteria andLegcycLessThan(String value) {
            addCriterion("LEGCYC <", value, "legcyc");
            return (Criteria) this;
        }

        public Criteria andLegcycLessThanOrEqualTo(String value) {
            addCriterion("LEGCYC <=", value, "legcyc");
            return (Criteria) this;
        }

        public Criteria andLegcycLike(String value) {
            addCriterion("LEGCYC like", value, "legcyc");
            return (Criteria) this;
        }

        public Criteria andLegcycNotLike(String value) {
            addCriterion("LEGCYC not like", value, "legcyc");
            return (Criteria) this;
        }

        public Criteria andLegcycIn(List<String> values) {
            addCriterion("LEGCYC in", values, "legcyc");
            return (Criteria) this;
        }

        public Criteria andLegcycNotIn(List<String> values) {
            addCriterion("LEGCYC not in", values, "legcyc");
            return (Criteria) this;
        }

        public Criteria andLegcycBetween(String value1, String value2) {
            addCriterion("LEGCYC between", value1, value2, "legcyc");
            return (Criteria) this;
        }

        public Criteria andLegcycNotBetween(String value1, String value2) {
            addCriterion("LEGCYC not between", value1, value2, "legcyc");
            return (Criteria) this;
        }

        public Criteria andLegcdtIsNull() {
            addCriterion("LEGCDT is null");
            return (Criteria) this;
        }

        public Criteria andLegcdtIsNotNull() {
            addCriterion("LEGCDT is not null");
            return (Criteria) this;
        }

        public Criteria andLegcdtEqualTo(String value) {
            addCriterion("LEGCDT =", value, "legcdt");
            return (Criteria) this;
        }

        public Criteria andLegcdtNotEqualTo(String value) {
            addCriterion("LEGCDT <>", value, "legcdt");
            return (Criteria) this;
        }

        public Criteria andLegcdtGreaterThan(String value) {
            addCriterion("LEGCDT >", value, "legcdt");
            return (Criteria) this;
        }

        public Criteria andLegcdtGreaterThanOrEqualTo(String value) {
            addCriterion("LEGCDT >=", value, "legcdt");
            return (Criteria) this;
        }

        public Criteria andLegcdtLessThan(String value) {
            addCriterion("LEGCDT <", value, "legcdt");
            return (Criteria) this;
        }

        public Criteria andLegcdtLessThanOrEqualTo(String value) {
            addCriterion("LEGCDT <=", value, "legcdt");
            return (Criteria) this;
        }

        public Criteria andLegcdtLike(String value) {
            addCriterion("LEGCDT like", value, "legcdt");
            return (Criteria) this;
        }

        public Criteria andLegcdtNotLike(String value) {
            addCriterion("LEGCDT not like", value, "legcdt");
            return (Criteria) this;
        }

        public Criteria andLegcdtIn(List<String> values) {
            addCriterion("LEGCDT in", values, "legcdt");
            return (Criteria) this;
        }

        public Criteria andLegcdtNotIn(List<String> values) {
            addCriterion("LEGCDT not in", values, "legcdt");
            return (Criteria) this;
        }

        public Criteria andLegcdtBetween(String value1, String value2) {
            addCriterion("LEGCDT between", value1, value2, "legcdt");
            return (Criteria) this;
        }

        public Criteria andLegcdtNotBetween(String value1, String value2) {
            addCriterion("LEGCDT not between", value1, value2, "legcdt");
            return (Criteria) this;
        }

        public Criteria andLegfmtIsNull() {
            addCriterion("LEGFMT is null");
            return (Criteria) this;
        }

        public Criteria andLegfmtIsNotNull() {
            addCriterion("LEGFMT is not null");
            return (Criteria) this;
        }

        public Criteria andLegfmtEqualTo(String value) {
            addCriterion("LEGFMT =", value, "legfmt");
            return (Criteria) this;
        }

        public Criteria andLegfmtNotEqualTo(String value) {
            addCriterion("LEGFMT <>", value, "legfmt");
            return (Criteria) this;
        }

        public Criteria andLegfmtGreaterThan(String value) {
            addCriterion("LEGFMT >", value, "legfmt");
            return (Criteria) this;
        }

        public Criteria andLegfmtGreaterThanOrEqualTo(String value) {
            addCriterion("LEGFMT >=", value, "legfmt");
            return (Criteria) this;
        }

        public Criteria andLegfmtLessThan(String value) {
            addCriterion("LEGFMT <", value, "legfmt");
            return (Criteria) this;
        }

        public Criteria andLegfmtLessThanOrEqualTo(String value) {
            addCriterion("LEGFMT <=", value, "legfmt");
            return (Criteria) this;
        }

        public Criteria andLegfmtLike(String value) {
            addCriterion("LEGFMT like", value, "legfmt");
            return (Criteria) this;
        }

        public Criteria andLegfmtNotLike(String value) {
            addCriterion("LEGFMT not like", value, "legfmt");
            return (Criteria) this;
        }

        public Criteria andLegfmtIn(List<String> values) {
            addCriterion("LEGFMT in", values, "legfmt");
            return (Criteria) this;
        }

        public Criteria andLegfmtNotIn(List<String> values) {
            addCriterion("LEGFMT not in", values, "legfmt");
            return (Criteria) this;
        }

        public Criteria andLegfmtBetween(String value1, String value2) {
            addCriterion("LEGFMT between", value1, value2, "legfmt");
            return (Criteria) this;
        }

        public Criteria andLegfmtNotBetween(String value1, String value2) {
            addCriterion("LEGFMT not between", value1, value2, "legfmt");
            return (Criteria) this;
        }

        public Criteria andLegaddIsNull() {
            addCriterion("LEGADD is null");
            return (Criteria) this;
        }

        public Criteria andLegaddIsNotNull() {
            addCriterion("LEGADD is not null");
            return (Criteria) this;
        }

        public Criteria andLegaddEqualTo(String value) {
            addCriterion("LEGADD =", value, "legadd");
            return (Criteria) this;
        }

        public Criteria andLegaddNotEqualTo(String value) {
            addCriterion("LEGADD <>", value, "legadd");
            return (Criteria) this;
        }

        public Criteria andLegaddGreaterThan(String value) {
            addCriterion("LEGADD >", value, "legadd");
            return (Criteria) this;
        }

        public Criteria andLegaddGreaterThanOrEqualTo(String value) {
            addCriterion("LEGADD >=", value, "legadd");
            return (Criteria) this;
        }

        public Criteria andLegaddLessThan(String value) {
            addCriterion("LEGADD <", value, "legadd");
            return (Criteria) this;
        }

        public Criteria andLegaddLessThanOrEqualTo(String value) {
            addCriterion("LEGADD <=", value, "legadd");
            return (Criteria) this;
        }

        public Criteria andLegaddLike(String value) {
            addCriterion("LEGADD like", value, "legadd");
            return (Criteria) this;
        }

        public Criteria andLegaddNotLike(String value) {
            addCriterion("LEGADD not like", value, "legadd");
            return (Criteria) this;
        }

        public Criteria andLegaddIn(List<String> values) {
            addCriterion("LEGADD in", values, "legadd");
            return (Criteria) this;
        }

        public Criteria andLegaddNotIn(List<String> values) {
            addCriterion("LEGADD not in", values, "legadd");
            return (Criteria) this;
        }

        public Criteria andLegaddBetween(String value1, String value2) {
            addCriterion("LEGADD between", value1, value2, "legadd");
            return (Criteria) this;
        }

        public Criteria andLegaddNotBetween(String value1, String value2) {
            addCriterion("LEGADD not between", value1, value2, "legadd");
            return (Criteria) this;
        }

        public Criteria andLegzipIsNull() {
            addCriterion("LEGZIP is null");
            return (Criteria) this;
        }

        public Criteria andLegzipIsNotNull() {
            addCriterion("LEGZIP is not null");
            return (Criteria) this;
        }

        public Criteria andLegzipEqualTo(String value) {
            addCriterion("LEGZIP =", value, "legzip");
            return (Criteria) this;
        }

        public Criteria andLegzipNotEqualTo(String value) {
            addCriterion("LEGZIP <>", value, "legzip");
            return (Criteria) this;
        }

        public Criteria andLegzipGreaterThan(String value) {
            addCriterion("LEGZIP >", value, "legzip");
            return (Criteria) this;
        }

        public Criteria andLegzipGreaterThanOrEqualTo(String value) {
            addCriterion("LEGZIP >=", value, "legzip");
            return (Criteria) this;
        }

        public Criteria andLegzipLessThan(String value) {
            addCriterion("LEGZIP <", value, "legzip");
            return (Criteria) this;
        }

        public Criteria andLegzipLessThanOrEqualTo(String value) {
            addCriterion("LEGZIP <=", value, "legzip");
            return (Criteria) this;
        }

        public Criteria andLegzipLike(String value) {
            addCriterion("LEGZIP like", value, "legzip");
            return (Criteria) this;
        }

        public Criteria andLegzipNotLike(String value) {
            addCriterion("LEGZIP not like", value, "legzip");
            return (Criteria) this;
        }

        public Criteria andLegzipIn(List<String> values) {
            addCriterion("LEGZIP in", values, "legzip");
            return (Criteria) this;
        }

        public Criteria andLegzipNotIn(List<String> values) {
            addCriterion("LEGZIP not in", values, "legzip");
            return (Criteria) this;
        }

        public Criteria andLegzipBetween(String value1, String value2) {
            addCriterion("LEGZIP between", value1, value2, "legzip");
            return (Criteria) this;
        }

        public Criteria andLegzipNotBetween(String value1, String value2) {
            addCriterion("LEGZIP not between", value1, value2, "legzip");
            return (Criteria) this;
        }

        public Criteria andLegshtIsNull() {
            addCriterion("LEGSHT is null");
            return (Criteria) this;
        }

        public Criteria andLegshtIsNotNull() {
            addCriterion("LEGSHT is not null");
            return (Criteria) this;
        }

        public Criteria andLegshtEqualTo(Short value) {
            addCriterion("LEGSHT =", value, "legsht");
            return (Criteria) this;
        }

        public Criteria andLegshtNotEqualTo(Short value) {
            addCriterion("LEGSHT <>", value, "legsht");
            return (Criteria) this;
        }

        public Criteria andLegshtGreaterThan(Short value) {
            addCriterion("LEGSHT >", value, "legsht");
            return (Criteria) this;
        }

        public Criteria andLegshtGreaterThanOrEqualTo(Short value) {
            addCriterion("LEGSHT >=", value, "legsht");
            return (Criteria) this;
        }

        public Criteria andLegshtLessThan(Short value) {
            addCriterion("LEGSHT <", value, "legsht");
            return (Criteria) this;
        }

        public Criteria andLegshtLessThanOrEqualTo(Short value) {
            addCriterion("LEGSHT <=", value, "legsht");
            return (Criteria) this;
        }

        public Criteria andLegshtIn(List<Short> values) {
            addCriterion("LEGSHT in", values, "legsht");
            return (Criteria) this;
        }

        public Criteria andLegshtNotIn(List<Short> values) {
            addCriterion("LEGSHT not in", values, "legsht");
            return (Criteria) this;
        }

        public Criteria andLegshtBetween(Short value1, Short value2) {
            addCriterion("LEGSHT between", value1, value2, "legsht");
            return (Criteria) this;
        }

        public Criteria andLegshtNotBetween(Short value1, Short value2) {
            addCriterion("LEGSHT not between", value1, value2, "legsht");
            return (Criteria) this;
        }

        public Criteria andLegdepIsNull() {
            addCriterion("LEGDEP is null");
            return (Criteria) this;
        }

        public Criteria andLegdepIsNotNull() {
            addCriterion("LEGDEP is not null");
            return (Criteria) this;
        }

        public Criteria andLegdepEqualTo(String value) {
            addCriterion("LEGDEP =", value, "legdep");
            return (Criteria) this;
        }

        public Criteria andLegdepNotEqualTo(String value) {
            addCriterion("LEGDEP <>", value, "legdep");
            return (Criteria) this;
        }

        public Criteria andLegdepGreaterThan(String value) {
            addCriterion("LEGDEP >", value, "legdep");
            return (Criteria) this;
        }

        public Criteria andLegdepGreaterThanOrEqualTo(String value) {
            addCriterion("LEGDEP >=", value, "legdep");
            return (Criteria) this;
        }

        public Criteria andLegdepLessThan(String value) {
            addCriterion("LEGDEP <", value, "legdep");
            return (Criteria) this;
        }

        public Criteria andLegdepLessThanOrEqualTo(String value) {
            addCriterion("LEGDEP <=", value, "legdep");
            return (Criteria) this;
        }

        public Criteria andLegdepLike(String value) {
            addCriterion("LEGDEP like", value, "legdep");
            return (Criteria) this;
        }

        public Criteria andLegdepNotLike(String value) {
            addCriterion("LEGDEP not like", value, "legdep");
            return (Criteria) this;
        }

        public Criteria andLegdepIn(List<String> values) {
            addCriterion("LEGDEP in", values, "legdep");
            return (Criteria) this;
        }

        public Criteria andLegdepNotIn(List<String> values) {
            addCriterion("LEGDEP not in", values, "legdep");
            return (Criteria) this;
        }

        public Criteria andLegdepBetween(String value1, String value2) {
            addCriterion("LEGDEP between", value1, value2, "legdep");
            return (Criteria) this;
        }

        public Criteria andLegdepNotBetween(String value1, String value2) {
            addCriterion("LEGDEP not between", value1, value2, "legdep");
            return (Criteria) this;
        }

        public Criteria andActtypIsNull() {
            addCriterion("ACTTYP is null");
            return (Criteria) this;
        }

        public Criteria andActtypIsNotNull() {
            addCriterion("ACTTYP is not null");
            return (Criteria) this;
        }

        public Criteria andActtypEqualTo(String value) {
            addCriterion("ACTTYP =", value, "acttyp");
            return (Criteria) this;
        }

        public Criteria andActtypNotEqualTo(String value) {
            addCriterion("ACTTYP <>", value, "acttyp");
            return (Criteria) this;
        }

        public Criteria andActtypGreaterThan(String value) {
            addCriterion("ACTTYP >", value, "acttyp");
            return (Criteria) this;
        }

        public Criteria andActtypGreaterThanOrEqualTo(String value) {
            addCriterion("ACTTYP >=", value, "acttyp");
            return (Criteria) this;
        }

        public Criteria andActtypLessThan(String value) {
            addCriterion("ACTTYP <", value, "acttyp");
            return (Criteria) this;
        }

        public Criteria andActtypLessThanOrEqualTo(String value) {
            addCriterion("ACTTYP <=", value, "acttyp");
            return (Criteria) this;
        }

        public Criteria andActtypLike(String value) {
            addCriterion("ACTTYP like", value, "acttyp");
            return (Criteria) this;
        }

        public Criteria andActtypNotLike(String value) {
            addCriterion("ACTTYP not like", value, "acttyp");
            return (Criteria) this;
        }

        public Criteria andActtypIn(List<String> values) {
            addCriterion("ACTTYP in", values, "acttyp");
            return (Criteria) this;
        }

        public Criteria andActtypNotIn(List<String> values) {
            addCriterion("ACTTYP not in", values, "acttyp");
            return (Criteria) this;
        }

        public Criteria andActtypBetween(String value1, String value2) {
            addCriterion("ACTTYP between", value1, value2, "acttyp");
            return (Criteria) this;
        }

        public Criteria andActtypNotBetween(String value1, String value2) {
            addCriterion("ACTTYP not between", value1, value2, "acttyp");
            return (Criteria) this;
        }

        public Criteria andDepnumIsNull() {
            addCriterion("DEPNUM is null");
            return (Criteria) this;
        }

        public Criteria andDepnumIsNotNull() {
            addCriterion("DEPNUM is not null");
            return (Criteria) this;
        }

        public Criteria andDepnumEqualTo(String value) {
            addCriterion("DEPNUM =", value, "depnum");
            return (Criteria) this;
        }

        public Criteria andDepnumNotEqualTo(String value) {
            addCriterion("DEPNUM <>", value, "depnum");
            return (Criteria) this;
        }

        public Criteria andDepnumGreaterThan(String value) {
            addCriterion("DEPNUM >", value, "depnum");
            return (Criteria) this;
        }

        public Criteria andDepnumGreaterThanOrEqualTo(String value) {
            addCriterion("DEPNUM >=", value, "depnum");
            return (Criteria) this;
        }

        public Criteria andDepnumLessThan(String value) {
            addCriterion("DEPNUM <", value, "depnum");
            return (Criteria) this;
        }

        public Criteria andDepnumLessThanOrEqualTo(String value) {
            addCriterion("DEPNUM <=", value, "depnum");
            return (Criteria) this;
        }

        public Criteria andDepnumLike(String value) {
            addCriterion("DEPNUM like", value, "depnum");
            return (Criteria) this;
        }

        public Criteria andDepnumNotLike(String value) {
            addCriterion("DEPNUM not like", value, "depnum");
            return (Criteria) this;
        }

        public Criteria andDepnumIn(List<String> values) {
            addCriterion("DEPNUM in", values, "depnum");
            return (Criteria) this;
        }

        public Criteria andDepnumNotIn(List<String> values) {
            addCriterion("DEPNUM not in", values, "depnum");
            return (Criteria) this;
        }

        public Criteria andDepnumBetween(String value1, String value2) {
            addCriterion("DEPNUM between", value1, value2, "depnum");
            return (Criteria) this;
        }

        public Criteria andDepnumNotBetween(String value1, String value2) {
            addCriterion("DEPNUM not between", value1, value2, "depnum");
            return (Criteria) this;
        }

        public Criteria andOpndatIsNull() {
            addCriterion("OPNDAT is null");
            return (Criteria) this;
        }

        public Criteria andOpndatIsNotNull() {
            addCriterion("OPNDAT is not null");
            return (Criteria) this;
        }

        public Criteria andOpndatEqualTo(Date value) {
            addCriterion("OPNDAT =", value, "opndat");
            return (Criteria) this;
        }

        public Criteria andOpndatNotEqualTo(Date value) {
            addCriterion("OPNDAT <>", value, "opndat");
            return (Criteria) this;
        }

        public Criteria andOpndatGreaterThan(Date value) {
            addCriterion("OPNDAT >", value, "opndat");
            return (Criteria) this;
        }

        public Criteria andOpndatGreaterThanOrEqualTo(Date value) {
            addCriterion("OPNDAT >=", value, "opndat");
            return (Criteria) this;
        }

        public Criteria andOpndatLessThan(Date value) {
            addCriterion("OPNDAT <", value, "opndat");
            return (Criteria) this;
        }

        public Criteria andOpndatLessThanOrEqualTo(Date value) {
            addCriterion("OPNDAT <=", value, "opndat");
            return (Criteria) this;
        }

        public Criteria andOpndatIn(List<Date> values) {
            addCriterion("OPNDAT in", values, "opndat");
            return (Criteria) this;
        }

        public Criteria andOpndatNotIn(List<Date> values) {
            addCriterion("OPNDAT not in", values, "opndat");
            return (Criteria) this;
        }

        public Criteria andOpndatBetween(Date value1, Date value2) {
            addCriterion("OPNDAT between", value1, value2, "opndat");
            return (Criteria) this;
        }

        public Criteria andOpndatNotBetween(Date value1, Date value2) {
            addCriterion("OPNDAT not between", value1, value2, "opndat");
            return (Criteria) this;
        }

        public Criteria andClsdatIsNull() {
            addCriterion("CLSDAT is null");
            return (Criteria) this;
        }

        public Criteria andClsdatIsNotNull() {
            addCriterion("CLSDAT is not null");
            return (Criteria) this;
        }

        public Criteria andClsdatEqualTo(Date value) {
            addCriterion("CLSDAT =", value, "clsdat");
            return (Criteria) this;
        }

        public Criteria andClsdatNotEqualTo(Date value) {
            addCriterion("CLSDAT <>", value, "clsdat");
            return (Criteria) this;
        }

        public Criteria andClsdatGreaterThan(Date value) {
            addCriterion("CLSDAT >", value, "clsdat");
            return (Criteria) this;
        }

        public Criteria andClsdatGreaterThanOrEqualTo(Date value) {
            addCriterion("CLSDAT >=", value, "clsdat");
            return (Criteria) this;
        }

        public Criteria andClsdatLessThan(Date value) {
            addCriterion("CLSDAT <", value, "clsdat");
            return (Criteria) this;
        }

        public Criteria andClsdatLessThanOrEqualTo(Date value) {
            addCriterion("CLSDAT <=", value, "clsdat");
            return (Criteria) this;
        }

        public Criteria andClsdatIn(List<Date> values) {
            addCriterion("CLSDAT in", values, "clsdat");
            return (Criteria) this;
        }

        public Criteria andClsdatNotIn(List<Date> values) {
            addCriterion("CLSDAT not in", values, "clsdat");
            return (Criteria) this;
        }

        public Criteria andClsdatBetween(Date value1, Date value2) {
            addCriterion("CLSDAT between", value1, value2, "clsdat");
            return (Criteria) this;
        }

        public Criteria andClsdatNotBetween(Date value1, Date value2) {
            addCriterion("CLSDAT not between", value1, value2, "clsdat");
            return (Criteria) this;
        }

        public Criteria andCqeflgIsNull() {
            addCriterion("CQEFLG is null");
            return (Criteria) this;
        }

        public Criteria andCqeflgIsNotNull() {
            addCriterion("CQEFLG is not null");
            return (Criteria) this;
        }

        public Criteria andCqeflgEqualTo(String value) {
            addCriterion("CQEFLG =", value, "cqeflg");
            return (Criteria) this;
        }

        public Criteria andCqeflgNotEqualTo(String value) {
            addCriterion("CQEFLG <>", value, "cqeflg");
            return (Criteria) this;
        }

        public Criteria andCqeflgGreaterThan(String value) {
            addCriterion("CQEFLG >", value, "cqeflg");
            return (Criteria) this;
        }

        public Criteria andCqeflgGreaterThanOrEqualTo(String value) {
            addCriterion("CQEFLG >=", value, "cqeflg");
            return (Criteria) this;
        }

        public Criteria andCqeflgLessThan(String value) {
            addCriterion("CQEFLG <", value, "cqeflg");
            return (Criteria) this;
        }

        public Criteria andCqeflgLessThanOrEqualTo(String value) {
            addCriterion("CQEFLG <=", value, "cqeflg");
            return (Criteria) this;
        }

        public Criteria andCqeflgLike(String value) {
            addCriterion("CQEFLG like", value, "cqeflg");
            return (Criteria) this;
        }

        public Criteria andCqeflgNotLike(String value) {
            addCriterion("CQEFLG not like", value, "cqeflg");
            return (Criteria) this;
        }

        public Criteria andCqeflgIn(List<String> values) {
            addCriterion("CQEFLG in", values, "cqeflg");
            return (Criteria) this;
        }

        public Criteria andCqeflgNotIn(List<String> values) {
            addCriterion("CQEFLG not in", values, "cqeflg");
            return (Criteria) this;
        }

        public Criteria andCqeflgBetween(String value1, String value2) {
            addCriterion("CQEFLG between", value1, value2, "cqeflg");
            return (Criteria) this;
        }

        public Criteria andCqeflgNotBetween(String value1, String value2) {
            addCriterion("CQEFLG not between", value1, value2, "cqeflg");
            return (Criteria) this;
        }

        public Criteria andBallimIsNull() {
            addCriterion("BALLIM is null");
            return (Criteria) this;
        }

        public Criteria andBallimIsNotNull() {
            addCriterion("BALLIM is not null");
            return (Criteria) this;
        }

        public Criteria andBallimEqualTo(Long value) {
            addCriterion("BALLIM =", value, "ballim");
            return (Criteria) this;
        }

        public Criteria andBallimNotEqualTo(Long value) {
            addCriterion("BALLIM <>", value, "ballim");
            return (Criteria) this;
        }

        public Criteria andBallimGreaterThan(Long value) {
            addCriterion("BALLIM >", value, "ballim");
            return (Criteria) this;
        }

        public Criteria andBallimGreaterThanOrEqualTo(Long value) {
            addCriterion("BALLIM >=", value, "ballim");
            return (Criteria) this;
        }

        public Criteria andBallimLessThan(Long value) {
            addCriterion("BALLIM <", value, "ballim");
            return (Criteria) this;
        }

        public Criteria andBallimLessThanOrEqualTo(Long value) {
            addCriterion("BALLIM <=", value, "ballim");
            return (Criteria) this;
        }

        public Criteria andBallimIn(List<Long> values) {
            addCriterion("BALLIM in", values, "ballim");
            return (Criteria) this;
        }

        public Criteria andBallimNotIn(List<Long> values) {
            addCriterion("BALLIM not in", values, "ballim");
            return (Criteria) this;
        }

        public Criteria andBallimBetween(Long value1, Long value2) {
            addCriterion("BALLIM between", value1, value2, "ballim");
            return (Criteria) this;
        }

        public Criteria andBallimNotBetween(Long value1, Long value2) {
            addCriterion("BALLIM not between", value1, value2, "ballim");
            return (Criteria) this;
        }

        public Criteria andOvelimIsNull() {
            addCriterion("OVELIM is null");
            return (Criteria) this;
        }

        public Criteria andOvelimIsNotNull() {
            addCriterion("OVELIM is not null");
            return (Criteria) this;
        }

        public Criteria andOvelimEqualTo(Long value) {
            addCriterion("OVELIM =", value, "ovelim");
            return (Criteria) this;
        }

        public Criteria andOvelimNotEqualTo(Long value) {
            addCriterion("OVELIM <>", value, "ovelim");
            return (Criteria) this;
        }

        public Criteria andOvelimGreaterThan(Long value) {
            addCriterion("OVELIM >", value, "ovelim");
            return (Criteria) this;
        }

        public Criteria andOvelimGreaterThanOrEqualTo(Long value) {
            addCriterion("OVELIM >=", value, "ovelim");
            return (Criteria) this;
        }

        public Criteria andOvelimLessThan(Long value) {
            addCriterion("OVELIM <", value, "ovelim");
            return (Criteria) this;
        }

        public Criteria andOvelimLessThanOrEqualTo(Long value) {
            addCriterion("OVELIM <=", value, "ovelim");
            return (Criteria) this;
        }

        public Criteria andOvelimIn(List<Long> values) {
            addCriterion("OVELIM in", values, "ovelim");
            return (Criteria) this;
        }

        public Criteria andOvelimNotIn(List<Long> values) {
            addCriterion("OVELIM not in", values, "ovelim");
            return (Criteria) this;
        }

        public Criteria andOvelimBetween(Long value1, Long value2) {
            addCriterion("OVELIM between", value1, value2, "ovelim");
            return (Criteria) this;
        }

        public Criteria andOvelimNotBetween(Long value1, Long value2) {
            addCriterion("OVELIM not between", value1, value2, "ovelim");
            return (Criteria) this;
        }

        public Criteria andOveexpIsNull() {
            addCriterion("OVEEXP is null");
            return (Criteria) this;
        }

        public Criteria andOveexpIsNotNull() {
            addCriterion("OVEEXP is not null");
            return (Criteria) this;
        }

        public Criteria andOveexpEqualTo(Date value) {
            addCriterion("OVEEXP =", value, "oveexp");
            return (Criteria) this;
        }

        public Criteria andOveexpNotEqualTo(Date value) {
            addCriterion("OVEEXP <>", value, "oveexp");
            return (Criteria) this;
        }

        public Criteria andOveexpGreaterThan(Date value) {
            addCriterion("OVEEXP >", value, "oveexp");
            return (Criteria) this;
        }

        public Criteria andOveexpGreaterThanOrEqualTo(Date value) {
            addCriterion("OVEEXP >=", value, "oveexp");
            return (Criteria) this;
        }

        public Criteria andOveexpLessThan(Date value) {
            addCriterion("OVEEXP <", value, "oveexp");
            return (Criteria) this;
        }

        public Criteria andOveexpLessThanOrEqualTo(Date value) {
            addCriterion("OVEEXP <=", value, "oveexp");
            return (Criteria) this;
        }

        public Criteria andOveexpIn(List<Date> values) {
            addCriterion("OVEEXP in", values, "oveexp");
            return (Criteria) this;
        }

        public Criteria andOveexpNotIn(List<Date> values) {
            addCriterion("OVEEXP not in", values, "oveexp");
            return (Criteria) this;
        }

        public Criteria andOveexpBetween(Date value1, Date value2) {
            addCriterion("OVEEXP between", value1, value2, "oveexp");
            return (Criteria) this;
        }

        public Criteria andOveexpNotBetween(Date value1, Date value2) {
            addCriterion("OVEEXP not between", value1, value2, "oveexp");
            return (Criteria) this;
        }

        public Criteria andCretlrIsNull() {
            addCriterion("CRETLR is null");
            return (Criteria) this;
        }

        public Criteria andCretlrIsNotNull() {
            addCriterion("CRETLR is not null");
            return (Criteria) this;
        }

        public Criteria andCretlrEqualTo(String value) {
            addCriterion("CRETLR =", value, "cretlr");
            return (Criteria) this;
        }

        public Criteria andCretlrNotEqualTo(String value) {
            addCriterion("CRETLR <>", value, "cretlr");
            return (Criteria) this;
        }

        public Criteria andCretlrGreaterThan(String value) {
            addCriterion("CRETLR >", value, "cretlr");
            return (Criteria) this;
        }

        public Criteria andCretlrGreaterThanOrEqualTo(String value) {
            addCriterion("CRETLR >=", value, "cretlr");
            return (Criteria) this;
        }

        public Criteria andCretlrLessThan(String value) {
            addCriterion("CRETLR <", value, "cretlr");
            return (Criteria) this;
        }

        public Criteria andCretlrLessThanOrEqualTo(String value) {
            addCriterion("CRETLR <=", value, "cretlr");
            return (Criteria) this;
        }

        public Criteria andCretlrLike(String value) {
            addCriterion("CRETLR like", value, "cretlr");
            return (Criteria) this;
        }

        public Criteria andCretlrNotLike(String value) {
            addCriterion("CRETLR not like", value, "cretlr");
            return (Criteria) this;
        }

        public Criteria andCretlrIn(List<String> values) {
            addCriterion("CRETLR in", values, "cretlr");
            return (Criteria) this;
        }

        public Criteria andCretlrNotIn(List<String> values) {
            addCriterion("CRETLR not in", values, "cretlr");
            return (Criteria) this;
        }

        public Criteria andCretlrBetween(String value1, String value2) {
            addCriterion("CRETLR between", value1, value2, "cretlr");
            return (Criteria) this;
        }

        public Criteria andCretlrNotBetween(String value1, String value2) {
            addCriterion("CRETLR not between", value1, value2, "cretlr");
            return (Criteria) this;
        }

        public Criteria andRecstsIsNull() {
            addCriterion("RECSTS is null");
            return (Criteria) this;
        }

        public Criteria andRecstsIsNotNull() {
            addCriterion("RECSTS is not null");
            return (Criteria) this;
        }

        public Criteria andRecstsEqualTo(String value) {
            addCriterion("RECSTS =", value, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsNotEqualTo(String value) {
            addCriterion("RECSTS <>", value, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsGreaterThan(String value) {
            addCriterion("RECSTS >", value, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsGreaterThanOrEqualTo(String value) {
            addCriterion("RECSTS >=", value, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsLessThan(String value) {
            addCriterion("RECSTS <", value, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsLessThanOrEqualTo(String value) {
            addCriterion("RECSTS <=", value, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsLike(String value) {
            addCriterion("RECSTS like", value, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsNotLike(String value) {
            addCriterion("RECSTS not like", value, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsIn(List<String> values) {
            addCriterion("RECSTS in", values, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsNotIn(List<String> values) {
            addCriterion("RECSTS not in", values, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsBetween(String value1, String value2) {
            addCriterion("RECSTS between", value1, value2, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsNotBetween(String value1, String value2) {
            addCriterion("RECSTS not between", value1, value2, "recsts");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ACTOAH
     *
     * @mbggenerated do_not_delete_during_merge Sun Nov 21 21:36:05 CST 2010
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ACTOAH
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}