package cbs.repository.account.maininfo.model;

import java.util.Date;

public class Actouf {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTOUF.SYSIDT
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    private String sysidt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTOUF.ORGIDT
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    private String orgidt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTOUF.CUSIDT
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    private String cusidt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTOUF.APCODE
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    private String apcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTOUF.CURCDE
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    private String curcde;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTOUF.CRNYER
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    private Short crnyer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTOUF.REGNUM
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    private String regnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTOUF.OSTAMT
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    private Long ostamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTOUF.BOKDAT
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    private Date bokdat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTOUF.BOKVCH
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    private String bokvch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTOUF.BOKREM
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    private String bokrem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTOUF.CRSDUR
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    private Short crsdur;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTOUF.BOKAUT
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    private String bokaut;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTOUF.BOKANO
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    private String bokano;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTOUF.CRSDAT
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    private Date crsdat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTOUF.CRSVCH
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    private String crsvch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTOUF.CRSAUT
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    private String crsaut;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTOUF.CRSANO
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    private String crsano;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTOUF.CRSREM
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    private String crsrem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTOUF.REFNUM
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    private Integer refnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTOUF.AMDTLR
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    private String amdtlr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTOUF.UPDDAT
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    private Date upddat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTOUF.RECSTS
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    private String recsts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTOUF.SYSIDT
     *
     * @return the value of ACTOUF.SYSIDT
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public String getSysidt() {
        return sysidt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTOUF.SYSIDT
     *
     * @param sysidt the value for ACTOUF.SYSIDT
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public void setSysidt(String sysidt) {
        this.sysidt = sysidt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTOUF.ORGIDT
     *
     * @return the value of ACTOUF.ORGIDT
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public String getOrgidt() {
        return orgidt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTOUF.ORGIDT
     *
     * @param orgidt the value for ACTOUF.ORGIDT
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public void setOrgidt(String orgidt) {
        this.orgidt = orgidt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTOUF.CUSIDT
     *
     * @return the value of ACTOUF.CUSIDT
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public String getCusidt() {
        return cusidt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTOUF.CUSIDT
     *
     * @param cusidt the value for ACTOUF.CUSIDT
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public void setCusidt(String cusidt) {
        this.cusidt = cusidt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTOUF.APCODE
     *
     * @return the value of ACTOUF.APCODE
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public String getApcode() {
        return apcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTOUF.APCODE
     *
     * @param apcode the value for ACTOUF.APCODE
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public void setApcode(String apcode) {
        this.apcode = apcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTOUF.CURCDE
     *
     * @return the value of ACTOUF.CURCDE
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public String getCurcde() {
        return curcde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTOUF.CURCDE
     *
     * @param curcde the value for ACTOUF.CURCDE
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public void setCurcde(String curcde) {
        this.curcde = curcde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTOUF.CRNYER
     *
     * @return the value of ACTOUF.CRNYER
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public Short getCrnyer() {
        return crnyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTOUF.CRNYER
     *
     * @param crnyer the value for ACTOUF.CRNYER
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public void setCrnyer(Short crnyer) {
        this.crnyer = crnyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTOUF.REGNUM
     *
     * @return the value of ACTOUF.REGNUM
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public String getRegnum() {
        return regnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTOUF.REGNUM
     *
     * @param regnum the value for ACTOUF.REGNUM
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public void setRegnum(String regnum) {
        this.regnum = regnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTOUF.OSTAMT
     *
     * @return the value of ACTOUF.OSTAMT
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public Long getOstamt() {
        return ostamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTOUF.OSTAMT
     *
     * @param ostamt the value for ACTOUF.OSTAMT
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public void setOstamt(Long ostamt) {
        this.ostamt = ostamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTOUF.BOKDAT
     *
     * @return the value of ACTOUF.BOKDAT
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public Date getBokdat() {
        return bokdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTOUF.BOKDAT
     *
     * @param bokdat the value for ACTOUF.BOKDAT
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public void setBokdat(Date bokdat) {
        this.bokdat = bokdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTOUF.BOKVCH
     *
     * @return the value of ACTOUF.BOKVCH
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public String getBokvch() {
        return bokvch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTOUF.BOKVCH
     *
     * @param bokvch the value for ACTOUF.BOKVCH
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public void setBokvch(String bokvch) {
        this.bokvch = bokvch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTOUF.BOKREM
     *
     * @return the value of ACTOUF.BOKREM
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public String getBokrem() {
        return bokrem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTOUF.BOKREM
     *
     * @param bokrem the value for ACTOUF.BOKREM
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public void setBokrem(String bokrem) {
        this.bokrem = bokrem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTOUF.CRSDUR
     *
     * @return the value of ACTOUF.CRSDUR
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public Short getCrsdur() {
        return crsdur;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTOUF.CRSDUR
     *
     * @param crsdur the value for ACTOUF.CRSDUR
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public void setCrsdur(Short crsdur) {
        this.crsdur = crsdur;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTOUF.BOKAUT
     *
     * @return the value of ACTOUF.BOKAUT
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public String getBokaut() {
        return bokaut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTOUF.BOKAUT
     *
     * @param bokaut the value for ACTOUF.BOKAUT
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public void setBokaut(String bokaut) {
        this.bokaut = bokaut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTOUF.BOKANO
     *
     * @return the value of ACTOUF.BOKANO
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public String getBokano() {
        return bokano;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTOUF.BOKANO
     *
     * @param bokano the value for ACTOUF.BOKANO
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public void setBokano(String bokano) {
        this.bokano = bokano;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTOUF.CRSDAT
     *
     * @return the value of ACTOUF.CRSDAT
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public Date getCrsdat() {
        return crsdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTOUF.CRSDAT
     *
     * @param crsdat the value for ACTOUF.CRSDAT
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public void setCrsdat(Date crsdat) {
        this.crsdat = crsdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTOUF.CRSVCH
     *
     * @return the value of ACTOUF.CRSVCH
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public String getCrsvch() {
        return crsvch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTOUF.CRSVCH
     *
     * @param crsvch the value for ACTOUF.CRSVCH
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public void setCrsvch(String crsvch) {
        this.crsvch = crsvch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTOUF.CRSAUT
     *
     * @return the value of ACTOUF.CRSAUT
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public String getCrsaut() {
        return crsaut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTOUF.CRSAUT
     *
     * @param crsaut the value for ACTOUF.CRSAUT
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public void setCrsaut(String crsaut) {
        this.crsaut = crsaut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTOUF.CRSANO
     *
     * @return the value of ACTOUF.CRSANO
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public String getCrsano() {
        return crsano;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTOUF.CRSANO
     *
     * @param crsano the value for ACTOUF.CRSANO
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public void setCrsano(String crsano) {
        this.crsano = crsano;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTOUF.CRSREM
     *
     * @return the value of ACTOUF.CRSREM
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public String getCrsrem() {
        return crsrem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTOUF.CRSREM
     *
     * @param crsrem the value for ACTOUF.CRSREM
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public void setCrsrem(String crsrem) {
        this.crsrem = crsrem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTOUF.REFNUM
     *
     * @return the value of ACTOUF.REFNUM
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public Integer getRefnum() {
        return refnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTOUF.REFNUM
     *
     * @param refnum the value for ACTOUF.REFNUM
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public void setRefnum(Integer refnum) {
        this.refnum = refnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTOUF.AMDTLR
     *
     * @return the value of ACTOUF.AMDTLR
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public String getAmdtlr() {
        return amdtlr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTOUF.AMDTLR
     *
     * @param amdtlr the value for ACTOUF.AMDTLR
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public void setAmdtlr(String amdtlr) {
        this.amdtlr = amdtlr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTOUF.UPDDAT
     *
     * @return the value of ACTOUF.UPDDAT
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public Date getUpddat() {
        return upddat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTOUF.UPDDAT
     *
     * @param upddat the value for ACTOUF.UPDDAT
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public void setUpddat(Date upddat) {
        this.upddat = upddat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTOUF.RECSTS
     *
     * @return the value of ACTOUF.RECSTS
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public String getRecsts() {
        return recsts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTOUF.RECSTS
     *
     * @param recsts the value for ACTOUF.RECSTS
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public void setRecsts(String recsts) {
        this.recsts = recsts;
    }
}