package cbs.repository.account.maininfo.model;

import java.util.Date;

public class Actplf {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTPLF.ORGIDT
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    private String orgidt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTPLF.DEPNUM
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    private String depnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTPLF.PLCODE
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    private String plcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTPLF.CURCDE
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    private String curcde;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTPLF.RECTYP
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    private String rectyp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTPLF.PLDATE
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    private Date pldate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTPLF.DRAMNT
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    private Long dramnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTPLF.CRAMNT
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    private Long cramnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTPLF.DRCUNT
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    private Integer drcunt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTPLF.CRCUNT
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    private Integer crcunt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTPLF.DRBALA
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    private Long drbala;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTPLF.CRBALA
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    private Long crbala;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTPLF.DAVBAL
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    private Long davbal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTPLF.CAVBAL
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    private Long cavbal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTPLF.CREDAT
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    private Date credat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTPLF.RECSTS
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    private String recsts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTPLF.ORGIDT
     *
     * @return the value of ACTPLF.ORGIDT
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public String getOrgidt() {
        return orgidt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTPLF.ORGIDT
     *
     * @param orgidt the value for ACTPLF.ORGIDT
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public void setOrgidt(String orgidt) {
        this.orgidt = orgidt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTPLF.DEPNUM
     *
     * @return the value of ACTPLF.DEPNUM
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public String getDepnum() {
        return depnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTPLF.DEPNUM
     *
     * @param depnum the value for ACTPLF.DEPNUM
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public void setDepnum(String depnum) {
        this.depnum = depnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTPLF.PLCODE
     *
     * @return the value of ACTPLF.PLCODE
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public String getPlcode() {
        return plcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTPLF.PLCODE
     *
     * @param plcode the value for ACTPLF.PLCODE
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public void setPlcode(String plcode) {
        this.plcode = plcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTPLF.CURCDE
     *
     * @return the value of ACTPLF.CURCDE
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public String getCurcde() {
        return curcde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTPLF.CURCDE
     *
     * @param curcde the value for ACTPLF.CURCDE
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public void setCurcde(String curcde) {
        this.curcde = curcde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTPLF.RECTYP
     *
     * @return the value of ACTPLF.RECTYP
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public String getRectyp() {
        return rectyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTPLF.RECTYP
     *
     * @param rectyp the value for ACTPLF.RECTYP
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public void setRectyp(String rectyp) {
        this.rectyp = rectyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTPLF.PLDATE
     *
     * @return the value of ACTPLF.PLDATE
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public Date getPldate() {
        return pldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTPLF.PLDATE
     *
     * @param pldate the value for ACTPLF.PLDATE
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public void setPldate(Date pldate) {
        this.pldate = pldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTPLF.DRAMNT
     *
     * @return the value of ACTPLF.DRAMNT
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public Long getDramnt() {
        return dramnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTPLF.DRAMNT
     *
     * @param dramnt the value for ACTPLF.DRAMNT
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public void setDramnt(Long dramnt) {
        this.dramnt = dramnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTPLF.CRAMNT
     *
     * @return the value of ACTPLF.CRAMNT
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public Long getCramnt() {
        return cramnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTPLF.CRAMNT
     *
     * @param cramnt the value for ACTPLF.CRAMNT
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public void setCramnt(Long cramnt) {
        this.cramnt = cramnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTPLF.DRCUNT
     *
     * @return the value of ACTPLF.DRCUNT
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public Integer getDrcunt() {
        return drcunt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTPLF.DRCUNT
     *
     * @param drcunt the value for ACTPLF.DRCUNT
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public void setDrcunt(Integer drcunt) {
        this.drcunt = drcunt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTPLF.CRCUNT
     *
     * @return the value of ACTPLF.CRCUNT
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public Integer getCrcunt() {
        return crcunt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTPLF.CRCUNT
     *
     * @param crcunt the value for ACTPLF.CRCUNT
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public void setCrcunt(Integer crcunt) {
        this.crcunt = crcunt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTPLF.DRBALA
     *
     * @return the value of ACTPLF.DRBALA
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public Long getDrbala() {
        return drbala;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTPLF.DRBALA
     *
     * @param drbala the value for ACTPLF.DRBALA
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public void setDrbala(Long drbala) {
        this.drbala = drbala;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTPLF.CRBALA
     *
     * @return the value of ACTPLF.CRBALA
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public Long getCrbala() {
        return crbala;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTPLF.CRBALA
     *
     * @param crbala the value for ACTPLF.CRBALA
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public void setCrbala(Long crbala) {
        this.crbala = crbala;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTPLF.DAVBAL
     *
     * @return the value of ACTPLF.DAVBAL
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public Long getDavbal() {
        return davbal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTPLF.DAVBAL
     *
     * @param davbal the value for ACTPLF.DAVBAL
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public void setDavbal(Long davbal) {
        this.davbal = davbal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTPLF.CAVBAL
     *
     * @return the value of ACTPLF.CAVBAL
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public Long getCavbal() {
        return cavbal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTPLF.CAVBAL
     *
     * @param cavbal the value for ACTPLF.CAVBAL
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public void setCavbal(Long cavbal) {
        this.cavbal = cavbal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTPLF.CREDAT
     *
     * @return the value of ACTPLF.CREDAT
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public Date getCredat() {
        return credat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTPLF.CREDAT
     *
     * @param credat the value for ACTPLF.CREDAT
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public void setCredat(Date credat) {
        this.credat = credat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTPLF.RECSTS
     *
     * @return the value of ACTPLF.RECSTS
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public String getRecsts() {
        return recsts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTPLF.RECSTS
     *
     * @param recsts the value for ACTPLF.RECSTS
     *
     * @mbggenerated Sun Nov 21 21:36:05 CST 2010
     */
    public void setRecsts(String recsts) {
        this.recsts = recsts;
    }
}